### ISSUE TITLE
OBJECT::Berekening - Plek in het model en relaties

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#107]
# Samenvatting

Voor hoofdspoor wil je twee verschillende typen instanties van het object **_Berekening_** kunnen hanteren: één voor rekeninstelling één voor rekeninstelling hoofdspoor en één voor rekeninstellingen industrie (HRMI) (zie onderaan issue #22).

Het model legt nu per GPP (of BGE) een berekening vast. 

- En berekening heeft tenminste 1, maar mogelijk meerdere GPP"s waarop die instellingen van toepassing zijn. 
- Omgekeerd heeft een GPP altijd één en tevens maximaal één Berekening.

Klopt dat? Of is het één rekeninstelling voor de gehele geluidgegevenscollectie? In het huidige model kan je bovenstraande vraagstuk m.b.t. spoor kwijt. 

# Voorgestelde oplossing

- Plek in het model zo laten indien er niet één rekeninstelling is die voor de hele geluidgegevenscollectie geld. 
- Indien dat laatste wel het geval is, moet er nagedacht worden om een oplossing te bieden aan het vraagstuk rondom spooremplacementen waarvoor een andere rekeninstelling gebruikt wordt.

**Comment by joerivanes** [comment]
Vraagstuk voor berichtenmodel, waarschijnlijk ligt meest voor de hand om apart bericht voor hoofdspoor en opstelterreinen op te stellen.

**Comment by joerivanes** [comment]
Is niet meer relevant. Na consultatie is ervoor gekozen alles in 1 schema op te leveren. Daarnaast kunnen aparte aanleveringen worden gedaan via industie (met apart rekenobject) conform de rekenregels voor industie
