### ISSUE TITLE
MIM verplichte metadata

### ISSUE THREAD

**Issue by joerivanes** [Geonovum/IMG#109]
# Samenvatting

Na een check van het MIM meta-model lijkt het erop dat nog niet alle verplichte meta-data attributen in het model staan. 

# voorgestelde oplossing

Ieder domein, ieder Object en ieder attribuut moet gecheckt worden aan de hand van het volgende meta-model: https://geonovum.github.io/MIM-Werkomgeving/#modelelementen-en-metagegevens-als-diagram

**Comment by joerivanes** [comment]
Authenticiteit | Definitie
-- | --
mim:Authentiek | In een basisregistratie opgenomen gegeven dat bij wettelijk voorschrift als authentiek is aangemerkt.
mim:Basisgegeven | Een in een basisregistratie opgenomen gegeven.
mim:WettelijkGegeven | Gegeven behorende bij een wettelijke registratie, niet zijnde een basisregistratie
mim:LandelijkKerngegeven | Indien het een gegeven of een als relatiesoort gemodelleerd gegeven is in een landelijk sector- en domein-overstijgend informatiemodel en geen authentiek gegeven en geen basisgegeven is.
mim:OverigeAuthenticiteit | Indien het géén van de voorgaande categorieën betreft. Veelal gaat het dan om proces-, taakveld- of domeinspecifieke gegevens.



Bij welke categorie hoort IMGeluid? Waarschijnlijk Wettelijk of landelijk? @lvdbrink

**Comment by lvdbrink** [comment]
De bovenstaande lijst komt uit een werkversie van MIM 1.1, wij hanteren MIM 1.0. De lijst voor Authenticiteit die wij moeten hanteren staat hier: https://docs.geostandaarden.nl/mim/mim10/#authentieke-gegevens

Welke waarden we moeten gebruiken hangt af van wat er juridisch gezegd is (in wet/besluit/regeling) voor de CVGG gegevens: wordt daar onderscheid gemaakt tussen authentiek en niet-authentiek? Dan moeten wij dat in het informatiemodel ook doen en dus kiezen voor elk gegeven tussen de bovenste twee (Authentiek / Basisgegeven). 

Anders is alles volgens mij Landelijk kerngegeven. Maar dat zou ik dan nog even willen dubbelchecken met @PalmJanssen

**Comment by joerivanes** [comment]
Opgelost. Alle metadata toegevoegd Imvertor gaf akkoord.
