### ISSUE TITLE
OBJECT::Kunstwerken - Relevante objecten/attributen/datatypen en definities

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#11]
# Samenvatting
Welke gegevens zijn akoestisch relevant voor GPP-weg en -spoor en BGE-weg en spoor?

Infraobjecttypen
- Brug
- (Brugwand)
- Tunnel
- Tunnelbak
- Overkapping
- Overkappingszijwand
- Perronrand 
- Geluidschermen

# Voorgestelde oplossing

- In principe zijn kunstwerken neit relevant voor de GPP-berekening, maar helpen de geometrieën ervan wel om de data beter te begrijpen. Daarom wel meenemen.
- Verder geldt voor stalen bruggen geluidtoeslag die voor de GPP-berekening relevant is, dus meenemen.
- Alle wandtypen kunnen als scherm gemodelleerd worden, maar het onderscheid naar schermtypen is niet relevant voor het berekenen van het GPP, maar helpen wel voor een belangrijk deel om de data beter te begrijpen. Daarom wel meenemen.

In het model onderscheiden de volgende objecten (kunstwerken) en lijstwaarden (Schermtypen):

**Kunstwerken**
- Brug
- Overkapping
- Tunnelbak
- Tunnel

**Schermtypen**
- Brugwand
- Geluidscherm
- Overkappingszijwand
- Perronrand
- Tunnelbakwand

**Comment by joerivanes** [comment]
Verholpen door herziening van model
