### ISSUE TITLE
uitleg bij UML diagrammen

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/IMG#115]
Het helpt de lezer om onderaan elk uml diagram een tekst met uitleg te hebben. Dan gaat het diagram meer leven. Een diagram is een verhaal.

Bijvoorbeeld bij 5.1.

Algemeen diagram van de opbouw van een geluidgegevenscollectie. Een geluidsgegevenscollectie bevat de gegevens van alle relevante geluidsobjecten binnen een geluidsaandachtsgebied. De collectie   kan verwijzen naar een document waarin het besluit is opgenomen........ De basisgeluidemissie en het geluidproductieplafond zijn gekoppeld aan informatie over de berekening....

**Comment by joerivanes** [comment]
Bij ieder diagram staat nu een tekst met uitleg! Resultaat valt te zien in [de catalogus](https://geonovum.github.io/IMG/#global_package_Algemeen):

**Comment by PalmJanssen** [comment]
Mooi. Leest heel fijn.

Van: joerivanes <notifications@github.com>
Verzonden: woensdag 22 april 2020 14:37
Aan: Geonovum/IMG <IMG@noreply.github.com>
CC: Paul Janssen <p.janssen@geonovum.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Geonovum/IMG] uitleg bij UML diagrammen (#115)


Bij ieder diagram staat nu een tekst met uitleg! Resultaat valt te zien in de catalogus<https://geonovum.github.io/IMG/#global_package_Algemeen>:
