### ISSUE TITLE
industrieRekeninstelling als subtype

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/IMG#116]
IndustrieRekeninstelling is eerder een groepsattribuut dan een subtype van Berekening.

voorstel:

maak een abstract groepsattribuut: Standaardrekeninstelling, met voor nu één subtype IndustrieRekeninstelling.

Bij Berekening een attribuut: standaardRekeninstelling met als datatype StandaardRekeninstelling

**Comment by PalmJanssen** [comment]
excuses, ik bedoel Gegevensgroeptype. Die wordt vervolgens gekoppeld met een gegevensgroep

**Comment by joerivanes** [comment]
Aangepast in model
