### ISSUE TITLE
REDACTIE: verbeterpunten ReSpec document

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/IMG#118]
- Oplossen van HTML validatiefouten (vnl dubbele ID's en problemen met tabellen)
- Toepassen van ReSpec functionaliteit voor het refereren naar documenten in een bibliografie
- Toepassen van ReSpec functionaliteit voor het opsommen van afkortingen en termen en definities

**Comment by joerivanes** [comment]
1.0 versie van catalogus is opgeleverd met deze functionaliteiten
