### ISSUE TITLE
xsd's uit GML distributie importeren nog GML 3.2.1

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/IMG#119]
IMG is overgegaan van gml 3.2.1 naar 3.2.2, maar allerlei xsd's (gco, gmx etc.) importeren nog steeds gml 3.2.1, waardoor het een beetje door elkaar gaat lopen. Dat geeft binnen sommige tooling conflicten.

**Comment by joerivanes** [comment]
@lvdbrink is dit verwerkt voor versie 1.0 van het IMGeluid?

**Comment by lvdbrink** [comment]
Ja, is verwerkt, kan gesloten worden.
