### ISSUE TITLE
Kardinaliteit aanpassen Brug.geluidtoeslag naar [0..12]

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#121]
Omschrijving 
Kardinaliteit aanpassen Brug.geluidtoeslag naar [0..12] + bijhorende beschrijvingen voor alles wat met brug te maken heeft. 

Ingediend door Jan Skornsek

Motivatie
De geluidtoeslag dient alleen opgenomen te worden in het geval het een stalen brug betreft [indicatieToeslag = 0].  In dat geval moet je per spoorvoertuigcategorie [maximaal 12x] een toeslag per octaafband kunnen opnemen. In versie IMGeluid_v1_1_0RC3.xsd moet je altijd een  geluidtoeslag opnemen en bovendien is  de kardinaliteit [1] en kun je dus maar voor één spoorvoertuigcategorie een toeslag opnenem, en niet voor alle voorkomende spoorvoertuigcategorieen."

**Comment by PB-GNM** [comment]
Toevoeging Jan Skornshek: indicatieToeslag. Toelichting aanpassen. 0 moet beton zijn en 1 moet moet staal zijn. De toeslag geldt immers juist bij een stalen brug. Nu onlogisch

**Comment by wilkoquak** [comment]
Opgelost::
- De definitie aangepast zodat duidelijk is dat inidicatieToeslag een boolean is die aangeeft of de toeslag geldt of niet. Daarnaast zet ik in de toelichting dat de waarde 0 een betonnen brug impliceert en 1 een stalen brug.
- kardinaliteit van attribuut geluidtoeslag veranderd van [1] naar [0..12].
- documentatie aangepast zodat duidelijk is dat per spoorvoertuigcategorie een toeslag per octaafband kan worden opgenomen.
