### ISSUE TITLE
Het afronden van waardes in IMGeluid

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#123]
In het IMGeluid worden veervuldig (meet)waardes uitgewisseld. Hierbij is het van belang dat in het model correct beschreven is wat de toegestane waardes zijn en hoeveel cijfers er achter de komma worden uitgewisseld. Bij een volgende oplevering van het xml-schema zullen facets (minInclusive,maxInclusive,fractioDigits) die controleren of de uitgewisselde waardes voldoen aan het model. Daarom is het extra van belang dat in het UML model de correcte waardes staan. Hiervoor heb ik een inventarisatie van alle plaatsen in het model gemaakt waar waardes voorkomen (zie bijlage). Deze inventarisatie moet gevalideerd worden met de opdrachtgever. Een punt van aandacht is dat  in sommige gevallen geldt een maximum van .99 en in andere gevallen juist weer van 1.00. Dit kan leiden tot verwarring bij het aanleveren van data. Wellicht kan dit rechtgetrokken worden.

[2021-06-14-IMGeluidOverzichtFloatingPoints.xlsx](https://github.com/Geonovum/IMG/files/6671414/2021-06-14-IMGeluidOverzichtFloatingPoints.xlsx)

**Comment by PB-GNM** [comment]
Jan Skornsek schrijft:

Mijn collega Dorien constateerde onderstaande 'gebrek'
* Plafondcorrectie WegdeelGPP heeft een patroon. 
* Plafondcorrectie SpoordeelGPP heeft geen patroon.  
In beide gevallen geldt hier hetzelfde patroon, en wel zoals opgenomen bij  de plafondcorrectie WegdeelGPP:  Toegestane waarde: -9,9 t/m 9,9

**Comment by wilkoquak** [comment]
Inmiddels de volgende wijzigingen doorgevoerd in de werkversie
	• Alle attributen van het type Real omgezet naar Decimal. 
	• Interne opschoning: aantal legenda objecten teruggebracht naar 2. Geen impact op model.
	• Op alle plekken waar waardes gebruikt worden staan de maximale waarde, de mimimale waarde, het type en het maximale aantal cijfers achter de komma nu duidelijk in de standaard.
	• Waar mogelijk zijn deze waardes als tagged values in het model opgenomen zodat ze ook in het xsd terechtkomen waardoor er automatisch op gevalideerd kan worden.
	• GeluidproductieplafondobjectIndustrie.geluidproductieplafondLnight:  Maximumwaarde in lijn gebracht met geluidproductieplafond waarde (99.9).
	• MonitoringresultaatIndustrie.monitoringwaardeLnight: Maximumwaarde op 99.9 gezet en daardoor in lijn gebracht met geluidproductieplafond waarde.
	• Basisgeluidemissieobject.basisgeluidemissiewaarde max aangepast naar 99.9.
	• IndustrieRekeninstellingen.standaardBodemabsorptiefractie: Aantal cijfers achter de komma veranderd van 2  naar 1.  Db weggehaald, want een fractie heeft geen eenheid. Het verwarrende woord quotient vervangen door fractie.
	• GeluidbronIndustrie.reflectiepuntHoogte . Omdat het ten opzicht van NAP is ook negatieve waardes toestaan. 
	• WegdeelGPP.wegdeelhoogte: Meeteenheid toegevoegd.
	• VerkeergegevensWeg.representatieveSnelheid:  Aantal cijfers achter de komma op 0 gezet.
	• SpoordeelGPP.plafondcorrectie: Gelijkgetrokken met WegdeelGPP.plafondcorrectie.
Geluidschermdeel.hellingshoek: maximum en minimum aangepast naar 45 graden.

**Comment by PB-GNM** [comment]
Het is opgelost in IMG 1.2

Het xml-schema is aangepast zodanig dat het mogelijk is om op basis van facets (minInclusive,maxInclusive,fractioDigits) te controleren of de uitgewisselde waardes voldoen aan het model. Daarom is het extra van belang dat in het UML model de correcte waardes staan. Hiervoor is een inventarisatie van alle plaatsen in het model gemaakt waar waardes voorkomen en waar nodig aangepast. De inventarisatie heeft plaatsgevonden en is doorgevoerd zoals hierboven beschreven.
