### ISSUE TITLE
GeluidschermSpoor (SDIMG-20)

### ISSUE THREAD

**Issue by TheoVerheij** [Geonovum/IMG#124]
Bij spoorwegen kan nu middels "geluidschermSpoor" worden aangegeven wat het type van een geluidscherm is.
Het is echter in het geheel niet dujidelijk wat de akoestische waarde van deze toevoeging is. Hangt de berekening af van het type scherm?

**Comment by PB-GNM** [comment]
Beste Theo,

Dank voor het stellen van deze en andere vragen.
Sinds kort is er een speciale IMG-helpdesk ( IMG@geonovum.nl ) voor de het indienen van vragen en wijzigingsverzoeken.
Zou je het daar in het vervolg willen doorgeven. Wanneer het een wijzigingsverzoek of inhoudelijk discussiepunt is, dan zullen wij dat als issue vervolgens hier opnemen, zodat er wel over gediscussieerd kan worden.

Dorien gaat navraag doen bij collega's voor deze vraag.

**Comment by DorienLolkema** [comment]
Van collega Arnaud Kok:
De gekozen methode sluit aan bij het geluidregister spoor, waar dit verschillende elementen zijn.

**Comment by TheoVerheij** [comment]
Dit veld zal echter niet bij alle bronhouders een relevant veld zijn. Ook is niet duidelijk of en wat dan de akoestische betekenis van dit veld is. Als dit veld voor sommige bronhouders wel van belang is, maak er dan een facultatief veld van.

Geomilieu ondersteund het veld niet en zal dan altijd "geluidscherm" in het veld zetten. Het lijkt me dan beter om het veld weg te mogen laten en deze alleen te gebruiken als er iets zinnigs in gezet wordt.

**Comment by wilkoquak** [comment]
Besluit adviesgroep 13-12-2021: Het hele subtype geluidschermspoor kan er uit. Aan het Objecttype Geluidschermdeel wordt dan de attribuutsoort schermtype toegevoegd met kardinalitet [0..1]. De directe relatie met Overkapping, Tunnelbak en Brug vervalt hiermee. Indirect bestaat deze relatie nog wel via geometrie.

**Comment by wilkoquak** [comment]
Voor uitvoering heb ik het volgende gedaan:
- attribuut schermtype verplaatst van GeluidschermSpoor naar Geluidscherm.
- Inkomende relaties van Brug, Tunnelbak en Overkapping verplaatst. De naamgeving van deze relaties heb ik niet veranderd hoewel dit wellicht wel logischer zou zijn.
- Regels verplaatst van GeluidschermSpoor naar Geluidsherm en tekstueel kloppend gemaakt.
- Klasse GeluidschermSpoor verwijderd.
- entry in changelog toegevoegd
- De relaties met Overkapping, Tunnelbak en Brug zijn verwijderd

**Comment by wilkoquak** [comment]
Extra acties n.a.v review @TheoVerheij :
 - attribuut schermtype optioneel gemaakt.
 - Tekstuele verwijzing vanuit Tunnelbak naar niet meer bestaande GeluidschermSpoor aangepast.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
