### ISSUE TITLE
HoogtelijnSpecificatie

### ISSUE THREAD

**Issue by TheoVerheij** [Geonovum/IMG#125]
Bij een hoogtelijn kan middels "HoogtelijnSpecificatie" de hoogtelijn verder worden gespecificeerd middels "hoogtelijnobjecttype" en "hoogtelijntype". Het is in het geheel niet duuidelijk wat de akoestiasche relevantie is. Hangt de berekening af van de inhoud van de attributen?

Wat is de toeveoegde waarde van de classificatie: ballastbedlijn, kantaardebaanlijn,  referentiepuntenlijn en tunnelbaklijn.
Hetzelfde geldt voor tunnelbakmaaiveld en tunnelbakvloerlijn

**Comment by PB-GNM** [comment]
Dorien gaat navraag doen bij collega's voor deze vraag.

**Comment by DorienLolkema** [comment]
Van collega Arnaud Kok:
Voor geluidberekeingen is een hoogtelijn een hoogtelijn. Maar het leveren van hoogtelijnen en deze opslitsing is optioneel. Dus volgens mij kun je dat prima zo laten. Het is niet strict noodzakelijk dat software deze attibuten inlees al kan dat voor een modelmaker wel handig zijn als die met die data aan de gang wil gaan.

**Comment by PB-GNM** [comment]
De vraag is beantwoord door Arnaud Kok.
Omdat het lang geleden is en er geen wedervraag is gekomen hebben besloten dit issue te sluiten.
