### ISSUE TITLE
Optrektoeslagpunt 

### ISSUE THREAD

**Issue by TheoVerheij** [Geonovum/IMG#126]
Zijn er nog voorwaarden verbonden aan de ligging van een Optrektoeslagpunt?
Moet deze op een wegdeel liggen of is de referentie voldoende? 

In Geomilieu kan een minirotonde als vlak worden ingevoerd en voor alle wegdelen welke geheel of gedeeltelijk binnen dit vlak liggen wordt dan een optrekcorrectie berekend. Voor de afstandsberekening wordt het middelpunt van de minirotonde gebruikt.

Er is dus geen relatie met wegdelen, deze wordt geometrisch bepaald.

**Comment by DorienLolkema** [comment]
@TheoVerheij Hoewel er in het IMG een relatie bestaat tussen de objecten Optrektoeslagpunt en WegdeelGPP wordt er niet gevalideerd of de geometrie van het Optrektoeslagpunt onderdeel is van geluidbronregisterlijn van WegdeelGPP. Vanuit het IMG bezien kun je de ligging van het Optrektoeslagpunt dus vrij kiezen.

Beantwoord dit je vraag, of gaat je vraag ook nog over de interpretatie van het MRG?

**Comment by TheoVerheij** [comment]
@DorienLolkema Bedankt voor de reactie. Dat betekent in ieder geval dat we minirotondes kunnen wegschrijven naar het CVGG met behulp van een punt in het midden en een verwijzing naar een vlak.
Jammer is wel dat er een verwijzing is naar minimaal 1 WegdeelGPP. Maar goed, in dit geval zullen dit alle wegdelen zijn waarvoor de optrektoeslag mogelijk in rekening is gebracht.
Als dit er geen is, bijvoorbeeld door foute modellering, dan zal deze niet worden weggeschreven. Dat geldt dan ook voor obstakels en kruisingen.

**Comment by PB-GNM** [comment]
We gaan er van uit dat het antwoord van Dorien voldoende is. In overleg met Dorien en Pieter wordt het issue gesloten.
