### ISSUE TITLE
Tijdelijke ontheffing toevoegen voor GPPNight

### ISSUE THREAD

**Issue by DorienLolkema** [Geonovum/IMG#127]
GPPNight kan ook een tijdelijke ontheffing hebben. Om dit mogelijk te maken moet het GeluidproductieplafondobjectIndustrie uitgebreid worden met:
- beginTijdelijkeOntheffingGPPNight;
- tijdelijkeOntheffingswaardeGPPNight;
- eindTijdelijkeOntheffingGPPNight.

**Comment by TheoVerheij** [comment]
Is/kan de tijdsperiode voor een tijdelijke ontheffing voor de nachtperiode anders zijn dan die voor de Lden-waarde? Als dat niet zo is, dan is toevoeging van "tijdelijkeOntheffingswaardeGPPNight" voldoende en kan begin/eind achterwege blijven.

**Comment by DorienLolkema** [comment]
Een ontheffingswaarde geldt per omgevingswaarde. Je zult ze dus apart moeten behandelen.

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is nu: 
" Het uitbreiden van GeluidproductieplafondobjectIndustrie met:
- beginTijdelijkeOntheffingGPPNight;
- tijdelijkeOntheffingswaardeGPPNight;
- eindTijdelijkeOntheffingGPPNight."

**Comment by wilkoquak** [comment]
Er is in de klasse GeluidproductieplafondobjectIndustrie al een attribuut geluidproductieplafondLnight het is logischer om de nieuwe kenmerken anders te noemen:
 - beginTijdelijkeOntheffingLnight.
 - tijdelijkeOntheffingswaardeLnight.
 - eindTijdelijkeOntheffingLnight.

**Comment by DorienLolkema** [comment]
Klinkt logisch. Bespreken we verder 20 september met de adviesgroep.

**Comment by PB-GNM** [comment]
Het is opgelost in IMG 1.2 conform voorstel.
