### ISSUE TITLE
Overwegen om verbindings-s bij verkeer[...] toe te voegen

### ISSUE THREAD

**Issue by DorienLolkema** [Geonovum/IMG#128]
In het IMG zijn alle verbindings-s-en weggehaald. Voor geluid[...] klopt dit. Voor verkeer[...] niet.
Als we de verbinding-s voor verkeers[...] terug willen zouden we dat zo spoedig mogelijk moeten doen zodat zo min mogelijk systemen aangepast hoeven te worden.

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is nu: "Het toevoegen van de verbindings-s bij verkeer[...] in het hele model."

**Comment by wilkoquak** [comment]
Deze wijziging moet in het model (UML) en documentatie.

**Comment by wilkoquak** [comment]
In klasses en kenmerken in het UML zijn er drie gevallen. deze pas ik aan
 -  VerkeergegevensWeg --> VerkeersgegevensWeg
 - WegdeelGPP.verkeergegevens --> WegdeelGPP.verkeersgegevens
 - WegdeelBGE.verkeergegevens --> WegdeelBGE.verkeersgegevens
In documentatie lijkt de verbindings-s nauwelijks te ontbreken.

**Comment by DorienLolkema** [comment]
Ha ha, die documentatie had ik al eerder onder handen genomen ;-).

**Comment by PB-GNM** [comment]
Deze is opgelost in IMG 1.2.
Een naamswijziging is doorgevoerd voor elemeten die het woord "verkeer" door toevoeging van verbindings-s
