### ISSUE TITLE
Taludlijnen als afschermende objecten in het IMG (wijzigingsverzoek) (SDIMG-28)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#133]
Ik heb nog even een vraag over het voorbeeldbestand. Zoals je weet hebben we voor de fly-overs afschermende objecten opgenomen die de akoestisch afschermende werking vertegenwoordigen van het asfalt naar de omgeving. Wij noemen deze objecten de taludlijnen maar het zijn in kleine schermen in de rekensoftware (schermhoogte van 1 meter op een maaiveldhoogte weg – 1 meter) . Deze afschermende objecten zijn  geen geluidwerende maatregel en passen daarom niet in het item Geluidschermdeel van het IMGeluid. Destijds gaf je aan dat we ze toch in het geluidschermdeel konden opnemen. Maar volgens mij conflicteert dit met de nog geldende definitie volgens IMGeluid. In het voorbeeldbestand kan ik hier ook nog geen correcte locatie voor vinden. Kunnen we hier een oplossing voor bedenken. Een los item taludlijn of iets dergelijks zou kunnen helpen of een vinkje in het geluidschermdeel = taludlijn.  

drs. D.E. Lolkema

**Comment by DorienLolkema** [comment]
Een taludlijn zoals je hier beschrijft is een Geluidoverdrachtsobject. Wanneer deze in de akoestische berekening gebruikt wordt als geluidscherm, dan lijkt het mij het meest logisch deze op te nemen in het object Geluidschermdeel. Dit betekent voor de bronhouder dan wel dat alle attributen behorende bij het object Geluidschermdeel ingevuld moeten worden voor de taludlijn. Ook moet de enumeratie van ProfieltypeGeluidscherm uitgebreid worden met Taludlijn.

Vraag aan de meelezers: is dit de wenselijke oplossing?
(Zo ja, dan kan ook de beschrijving van het object Geluidschermdeel aangepast worden zodanig dat taludlijn hier ook onder valt.)

**Comment by TheoVerheij** [comment]
Naar mijn mening is een extra enumeratie "Taludlijn" overbodig. 
Voor de situatie dat onder het viaduct of fly-over een andere bron ligt, is het de optie 'zwevend' toegevoegd. Dus het viaduct is een zwevend item welke alleen afschermt voor bronnen waarvan de totale hoogte groter is dan de onderzijde van dit zwevende item. Op deze wijze kun je dan ook een scherm op een fly-over modelleren.

**Comment by DorienLolkema** [comment]
Hmm... ik geloof je dat gelijk hebt @TheoVerheij ;-).
Als dat idd klopt dan wordt het dus: taludlijn wordt Geluidschermdeel met statusZwevend. Beschrijving van het object Geluidschermdeel moet aangepast worden.

**Comment by ThijsRuiterRWS** [comment]
@DorienLolkema @TheoVerheij 

Het gaat er hier om dat het Geluidschermdeel volgens het IMGeluid alleen toegepast kan worden als deze "geplaatst is als een geluidwerende maatregel". Onze taludlijnen (schermen van 1 meter hoog startend 1 meter onder het rijlijn maaiveld als zwevend object) voldoen niet aan deze definitie. De taludlijnen zijn volwaardige akoestische schermen en kunnen ook in het Geluidschermdeel opgenomen worden echter worden deze items dan geformaliseerd terwijl deze items rond de fly-overs alleen een akoestische functie hebben om de overdracht correct te bepalen (geluid kan immers niet door het asfalt van de betreffende weg). Het zijn dus geen schermen die vastgesteld zijn en waar rechten aan ontleend kunnen worden. 

De taludlijnen zijn vergelijkbaar met de hoogtelijnen en bodemgebieden. Deze zijn facultatief want ze worden niet vast gelegd in een besluit maar wel nodig om een correcte berekening uit te voeren. Voor onze taludlijnen ten hoogte van fly-overs hebben we dus een vinkje of iets dergelijks nodig bij het Geluidschermdeel waarin staat dat deze geen juridische status hebben zoals een scherm langs de weg of op een fly-over die daar geplaatst is als maatregel. 

Hopelijk schept dit duidelijkheid.

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is: "Het aanpassen van de definitie van Geluidschermdeel, zodanig dat de hier bedoelde "taludlijn" er ook onder valt."

**Comment by ArnaudYK** [comment]
Ik volg deze toch niet helemaal. Waar in het huidige register zijn zulke objecten opgenomen? Ik lees bij Thijs dat dit dit net als hoogtelijnen facultatief is, maar dat ze het wel willen kunnen leveren omdat intern RWS er wel mee rekent? Dan zou dus betekenen dat een vink taludlijn (kan dat geen andere naam krijgen, want die heb je ook bij hoogtelijnen?) betekent dat het geen echt formeel afschermend object is. Op zich prima, maar denk wel even na over de naam.

**Comment by ThijsRuiterRWS** [comment]
@ArnaudYK Deze zijn opgenomen in het toekomstige register ten hoogte van fly-overs (waar 2 rijkswegen elkaar kruisen). In het huidige register (Wm, Silence) zijn ze ook aanwezig maar daar hebben we geen hoogtelijnen. Alle lijnen in het huidige register hebben "mini schermen" langs de wegen liggen voor de berekening. Onder de Ow gaan we dit logischer maken omdat onze rekensoftware er ook mee om kan gaan. Op dit moment kan Silence niet met hoogtelijnen omgaan. De nieuwe software (Geomilieu) kan dit wel. Daarom stappen we af van de algehele taludlijn (mini schermen) zoals van toepassing is in Silence en stappen we over naar hoogtelijnen voor de rijkswegen die niet kruisen met andere rijkswegen en zijn er taludlijnen nodig voor de kruisende rijkswegen welke niet op maaiveld niveau liggen. 

Op dit moment publiceren we de bodemgebieden en taludlijnen niet in het register maar gebruiken we deze wel voor onze berekening. Formeel gezien is het nu dus niet mogelijk om de berekende waarde op de referentiepunten te controleren als externe. Door onder de Ow deze items (bodemgebieden, taludlijnen en hoogtelijnen) wel te publiceren kunnen externe ons register controleren.

**Comment by wilkoquak** [comment]
@PB-GNM gaat een tekstvoorstel schrijven voor een nieuwe voorgestelde defintie.

**Comment by PB-GNM** [comment]
Het tekstvoorstel voor de definitie van geluidsschermdeel is:

> Deel van een geluidscherm of wal dat geplaatst is als een geluidwerende maatregel binnen een geluidaandachtsgebied waar de geluidproductieplafond regeling geldig is _of dat geplaatst is om andere redenen, maar ook geluidswerend is_."

**Comment by DorienLolkema** [comment]
En dan zonder verbindings-s, dus geluidwerend ;-)

**Comment by ArnaudYK** [comment]
Het eerste deel stond er al, maar wat is "de geluidproductieplafond regeling"? We hebben een omgevingsregeling met rekenregels voor GPP, maar geen aparte regeling voor GPP en dan nog zou je eerder een verwijzing naar een besluit verwachten als je zo'n tekst leest.

**Comment by PB-GNM** [comment]
Naar welk besluit zou het dan moeten verwijzen?

**Comment by DorienLolkema** [comment]
Het tekstvoorstel voor de definitie van geluidsschermdeel is:

Deel van een geluidscherm of wal dat geplaatst is als een geluidwerende maatregel binnen een geluidaandachtsgebied (zie Omgevingswet) of dat geplaatst is om andere redenen, maar ook geluidwerend is."

**Comment by DorienLolkema** [comment]
Het object geluidaandachtsgebied is gedefinieerd in de Omgevingswet. De term geluidaandachtsgebied verwijst dus in zichzelf al naar de Omgevingswet. Door tussen haakjes 'zie Omgevingswet' toe te voegen wordt dit nog eens expliciet gemaakt.
Volgens mij zijn we er zo wel.

**Comment by PB-GNM** [comment]
Deze is opgelost in IMG 1.2.
De definitie is aangepast, zodanig dat de hier bedoelde "taludlijn" er ook onder valt.
Er is ook een attribuut ‘geluidwerende maatregel’ toegevoegd zodat het voor afnemers helder is of het afschermende object valt onder de categorie ‘geluidwerende maatregel’ valt of niet.
