### ISSUE TITLE
Graag andere attribuutnaam voor featureMember van Geluidgegevenscollectie. (SDIMG-30 )

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#134]
Hallo Dorien, 

We zijn bezig met de import van de GML-bestanden en zijn nu zo ver dat we deze kunnen lezen, op één feature na: “Geluidgegevenscollectie”. 

In deze feature is een lijst opgenomen met referenties naar alle andere features in het bestand. Alleen is de naam van het attribuutveld “featureMember” en daar kunnen onze inleesroutines niet zo goed tegen. Ik denk dat dit komt omdat dit voor onze routines eigenlijk een namespace is.  

Als er in plaats van <img:featureMember> een willekeurige andere naam wordt gebruik, dan werkt het bij ons allemaal wel. 

Alle andere features worden prima gelezen, dus in principe hebben we de data, maar deze feature bevat wel wat interessante meta-informatie (type, geluidbron, herkomstCollectie en systematiek) en het lukt me nu niet om die te lezen. 

Is het mogelijk dit in IM Geluid aan te passen? Of moet ik hiervoor bij Jan aankloppen? 

Hieronder een voorbeeld van zo’n feature (uit Aanleverbestand_provinciale_weg_vaststelling.gml). 

<gml:featureMember> 

<img:Geluidgegevenscollectie gml:id="NL.img.44441111.Geluidgegevenscollectie-M_Provincieweg.1"> 

<img:identificatie> 

<img:NEN3610ID> 

...  

</img:NEN3610ID> 

</img:identificatie> 

<img:type>vaststelling</img:type> 

<img:geluidbron>provinciale weg</img:geluidbron> 

<img:herkomstCollectie> 

... 

</img:herkomstCollectie> 

<img:systematiek>GPP</img:systematiek> 

<img:geluidaandachtsgebied xlink:href="#NL.img.44441111.Geluidaandachtsgebied-873.1"></img:geluidaandachtsgebied> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-2.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-3.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-1.1"></img:featureMember> 

... 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-8.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-4.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-7.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagpunt-6.1"></img:featureMember> 

<img:featureMember xlink:href="#NL.img.44441111.Optrektoeslagvlak-2.1"></img:featureMember> 

</img:Geluidgegevenscollectie> 

</gml:featureMember> 

Met vriendelijke groet, 

  

Th.J.B. (Theo) Verheij

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is: "Het doorvoeren van een andere naam voor attribuut 'FeatureMember'  in Geluidgegevenscollectie."

**Comment by wilkoquak** [comment]
In de vergadering van de adviesgroep van 20 september 2021 is besloten dit wijzigingsverzoek niet door te voeren. De indiener had inmiddels ook een workaround gevonden.
