### ISSUE TITLE
SpoordeelGPP/spoordeelBGE: definitie ruwheid voor trams (SDIMG-35)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#135]
Hallo Pieter, 

In het geval van trams (trajecten met bb=13..16) moet de spoorconditie worden aangegeven. 

Voor de overige bovenbouwcondities wordt deze berekend op basis van de mate van railonderbrekingen, maar niet voor trambanen. 

Daar heb je 2 keuzes: 

trambaan in normale spoorconditie: Cspoorconditie = 5 dB

geslepen trambaan: Cspoorconditie = 3 dB

 

Ik zie geen optie om dit in het model aan te geven. 

Met vriendelijke groet, 

  

Th.J.B. (Theo) Verheij

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is "Het opnemen van spoorcondities bij trambanen"

**Comment by ArnaudYK** [comment]
Mee eens

**Comment by wilkoquak** [comment]
Ik ben even aan het zoeken wat de beste plek is om dit toe te voegen. Ik stel voor de SporstaafruwheidwaardeCatagorie uit te breiden met: 'trambaan in normale conditie' en 'geslepen trambaan'. Is dit een goede implementatie?

**Comment by PB-GNM** [comment]
Deze is opgelost in IMG 1.2.
De geslepenTrambaan en tranbaanInNormaleConditie zijn hierin toegevoegd aan SpoorstaafruwheidWaardeCategegorie
