### ISSUE TITLE
Spoor GPP: 31 Hz ontbreekt (SDIMG-38)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#137]
Bij spoor GPP worden rangeerterreinen met industrielawaai berekend en in industrielawaai wordt ook de 31 Hz berekend. Alleen ontbreekt deze octaafband bij onder andere reflectiefactoren van geluidschermen. 

Met vriendelijke groet, 

  

Th.J.B. (Theo) Verheij

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is "Het aanpassen van de documentatie zodat 31 Hz in meer gevallen mag worden gebruikt."

**Comment by ArnaudYK** [comment]
Dit is een lastige. In het rekenvoorschrift wordt L_overstand,i berekend conform rekenmethode idustrie, maar dus alleen voor octaafbanden 63-8kHz. Dus voor het berekenen van GPP of geluid van railverkeer is die 31.5 Hz niet nodig. 
![image](https://user-images.githubusercontent.com/62339673/130777824-cd712ab2-41b4-49e1-a57b-0bf3db8a5d61.png)

Het kan mogelijk handig zijn als je hetzelfde scherm hanteert voor de rest van je IL model van een emplacement.

**Comment by DorienLolkema** [comment]
Nu kijk ik in het IMG, maar waar staat dat de 31 Hz band niet gebruikt mag worden?

**Comment by ArnaudYK** [comment]
Volgens mij heb je gelijk. Bij geluidschermdeel wordt verwezen naar factor per octaafband. Dus 31hz t/m 8Khz

**Comment by PB-GNM** [comment]
Er is geen beperking in het model voor het gebruik van octaafband 31HZ dus is er geen aanpassing nodig aan het model.
