### ISSUE TITLE
Bouwwerken: relatieveHoogte is nu een DoubleList. Liever 1 waarde wat overeenkomt met een plat dak (SDIMG-39)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#138]
Hallo Pieter, 

Waarom kan bij een gebouw met een DoubleList de hoogte per hoekpunt worden opgegeven? 

Ik kan me dit niet uit eerdere overleggen herinneren en Geomilieu ondersteund dit niet. Ook de internationale software welke ik ken (CadnaA, IMMI, SoundPlan, LimA, iNoise, Predictor, TNM, ENM, Mithra) ondersteunen dit niet. 

In alle modellen voor het berekenen van omgevingsgeluid hebben gebouwen platte daken. 

Uit een lijst van Doubles is het dakvlak ook niet af te leiden. 

Bijvoorbeeld bij een vierkant gebouw met 1e en 3e hoekpunt op 5m en 2e en 4e hoekpunt op 10m is het dakvlak niet gedefinieerd. 

Mijn dringende verzoek is dan ook: gebouwen altijd plat dak. 

Met vriendelijke groet, 

  

Th.J.B. (Theo) Verheij

**Comment by TheoVerheij** [comment]
Nog een kleine toevoeging: 
In Geomilieu kun je uitstralende daken modelleren als vlakbron met een hoogte ten opzichte van het gebouw. Als het dak van het gebouw niet is gedefinieerd, is ook de hoogte van het uitstralende dak niet gedefinieerd.

**Comment by PB-GNM** [comment]
Het wijzigingsvoorstel is: "Het hanteren van 1 hoogte per gebouw wat neerkomt op het hanteren van platte daken. In de geometrie worden de z-coördinaten allen gelijk, maar wat doe je dan met een gebouw op een helling?"

**Comment by ArnaudYK** [comment]
In (vrijwel) alle software zijn gebouwen blokjes met een platte onder en bovenkant. Dat is er sprake 1 maaiveldhoogte en 1 hoogte van het gebouw. In feite zijn het dan 2d objecten met 2 attributen. Als je op een helling kijkt en je zegt dat het relatief is tov het lokale maaiveld dan weet ik van een bekende softwareleverancier dattie voor het maaiveld de eerste node van de polygoon gebruikt. 

Als je kijkt naar het rekenvoorschrift dan zegt ie daar niks over. Het omgaan met deze dingen heeft te maken met de pathfinder (van 3d naar een 2d dwarsdoorsnede), Het rekenvoorschrift gaat (voornamelijk) uit van die 2d doorsnedes en zegt weinig hoe je die moet vinden. In theorie zouden schuine muren kunnen (en bij bijvorbeeld een geluidsscherm kan dat gewoon), maar historisch is het lastig met polygonen zeker in de bekende shape files e.d. Dus ik zou het zo eenvoudig mogelijk houden nu. In het oude RMG stond voor railverkeer nog: "_De gemiddelde verdiepingshoogte van woningen wordt gesteld op 3 meter. Een schuine kap wordt hierbij meegenomen als een volledige verdiepingshoogte. De modellering van een schuine kap als recht blok mag echter niet leiden tot niet reële reflecties naar waarneempunten_." Deze is in de AREG geschrapt.

**Comment by PB-GNM** [comment]
Deze is opgelost in IMG 1.2.

Er is een regel toegevoegd bij de geometrie van het Bouwwerk dat de z waarde voor het hele bouwwerk overal hetzelfde moet zijn.
