### ISSUE TITLE
Geluidschermhoogte verplicht (SDIMG-14)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#140]
Leon Bemmelmans stelt voor om bij geluischermdeelSpoor (maar zelfde geldt in principe ook voor geluidscherm) om de schermhoogte verplicht te stellen. 

Beetje achtergrond: 

Eerder hebben we dat niet gedaan. De z-waarde in de geometrie is wel verplicht en met die waarde moet je uiteindelijk rekenen. De hoogte van scherm optioneel, want niet perse nodig om te kunnen rekenen. Redeneerlijn. We willen alleen echt noodzakelijk attributen verplicht stellen, om de bronhouder niet onnodig te belasten. Daarom is deze dus optioneel.

**Comment by ArnaudYK** [comment]
Naar aanleiding van de discussie net. De afmeting van een object is nodig om te kunnen rekenen. Dit omdat hoge objecten meer reflecteren dan lage objecten (nieuw in het voorschrift). Verder lees ik in de omgevingsregeling als geluidbrongegeven:

"_de afmetingen en locatie van geluidbeperkende werken of bouwwerken die zijn geplaatst om het geluid door de weg op een geluidgevoelig gebouw te beperken, vastgelegd in x-, y- en z- coördinaten, uitgedrukt in het stelsel van de Rijksdriehoeksmeting;_"

Im het IM model lever je als ik het goed lees de x,y van de voet en de z van de top? In dat geval denk ik dat de omgevingsregeling eist dat je ook hoogteschermdeel toevoegt.

**Comment by wilkoquak** [comment]
Besluit adviesgroep 15-11-2021: Er komt een regel bij: Indien de status zwevend is wordt het verplicht gesteld.

**Comment by wilkoquak** [comment]
In versie 1.2 van de standaard staat deze regel al (zie: https://docs.geostandaarden.nl/cvgg/img/#detail_attribute_IMGeluidAlgemeen_Geluidschermdeel_schermhoogte ). Er is dus geen verdere actie nodig.

**Comment by PB-GNM** [comment]
Gesloten, omdat die al verwerkt was in versie 1.2.
