### ISSUE TITLE
Enumeratie details Wegdektype - Cwegdek zoals bekend in RMG2012 (SDIMG-52)

### ISSUE THREAD

**Issue by ThijsRuiterRWS** [Geonovum/IMG#142]
In het informatie model staat de lijst met type deklagen. Hiervan kunnen de volgende wegdektype niet gekoppeld worden aan de Cwegdek type zoals beschreven op Infomil (https://www.infomil.nl/onderwerpen/geluid/regelgeving/wet-geluidhinder/wegverkeerslawaai/akoestisch-rapport/cwegdek/#Overzichtwegdekcorrecties) 

Wegdektype die niet gelinkt kunnen worden:
- akoestisch geoptimaliseerd 1L ZOAB
- akoestisch geoptimaliseerd SMA

Kan er in de enumeratie details de koppeling opgenomen worden met de wegdektypes zoals gehanteerd worden in Infomil. Naar deze lijst wordt verwezen in het RMG2012.

**Comment by DorienLolkema** [comment]
@ThijsRuiterRWS Het IMG sluit aan op de Omgevingswet, en daarmee dus ook op het nieuwe Meet- en Rekenvoorschrift Geluid. In de Aanvullingsregeling Geluid bij de Omgevingswet, bijlage IVe, tabel 2.3a vind je de nieuwe lijst met wegdektypen. InfoMil verwijst alleen naar de huidige regelgeving.

**Comment by PB-GNM** [comment]
Thijs heeft aangegeven dat de vraag hiermee voldoende is beantwoord.
