### ISSUE TITLE
meerdere geluidberekeningobjecten (SDIMG-46)

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#143]
In hoofdstuk 4.8.10 staat dat bij spoor 2 verschillende geluidberekeningobjecten voorkomen: een Geluidberekeningobject voor normale sporen en een IndustrieRekeninstellingen voor emplacementen. 

Is ook logisch omdat deze ene volgens de railverkeerslawaai methode berekend moet worden en de ander volgens industrielawaai. 

Maar: 
 - In het voorbeeldbestanden “Aanleverbestand_hoofdspoor_vaststelling.gml” en “Aanleverbestand_hoofdspoor_monitoringresultaat.gml” ontbreekt de 2e.
 - Zoals ik het begrijp is een GPP-waarde voor spoor is de spectrale sommatie van de bijdragen van spoorbanen en de bijdragen van de industriële bronnen van de emplacementen.
     Vanuit een Geluidproductieplafondobject wordt verwezen naar excact één Geluidberekeningobject. Dat betekent dan dat de waarde voor de geluidproductieplafond of met railverkeer is berekend, of met industrielawaai, maar niet met beide.
 - Hetzelfde geldt voor een aandachtsgebied: deze kan ook verwijzen naar maximaal één Geluidberekeningobject. Dus ook dan is het aandachtsgebied niet de sommatie van spoor en emplacement.

**Comment by DorienLolkema** [comment]
Dit is goed opgemerkt. Het IMG zal aangepast moeten worden. (En na aanpassing van het IMG zullen ook de voorbeeldbestanden hierop aangepast worden.)

**Gevraagde wijziging**
De relatie tussen Geluidaandachtsgebied / GPPproject met Geluidberekeningsobject moet aangepast worden. Er mogen een of twee Geluidberekeningsobjecten bij een Geluidaandachtsgebied of GPPproject horen.

**Opties om dit in te passen**
1. Een nieuw object als generalisatie toevoegen onder Geluidproductieplafondobject, met bijvoorbeeld de naam GeluidproductieplafondobjectSpoorIndustrie. Dat object moet vervolgens altijd twee geluidberekeningsobjecten bevatten, een voor Industrierekeninstellingen en een voor Geluidberekingobject. In het geval je voor het berekenen van een GPP spoor zowel conform het MRG Industrie als Spoor gerekend hebt, moet deze GeluidproductieplafondobjectSpoorIndustrie gebruikt worden. In alle andere gevallen kun je een gewoon Geluidaandachtsgebied gebruiken.  Dat laatste is het theoretisch geval er een GPPspoor wordt vastgesteld zonder emplacementen.
2. Een nieuw object als generalisatie toevoegen onder Geluidaandachtsgebied, met bijvoorbeeld de naam GeluidaandachtsgebiedGPPSpoor. Dat object moet vervolgens altijd twee geluidberekingsobjecten bevatten, een voor Industrierekeninstellingen en een Geluidberekingobject. In het geval je voor het berekenen van het geluidaandachtgebiedGPPspoor zowel conform het MRG Industrie als Spoor gerekend hebt, moet je GeluidaandachtsgebiedGPPSpoor gebruiken . In alle andere gevallen kun je een gewoon Geluidaandachtsgebied gebruiken.  Dat laatste is het theoretisch geval er een GPPspoor wordt vastgesteld zonder emplacementen.
3. Een andere optie is de de variant waarbij zowel bij Geluidaandachtsgebied als bij Geluidproductieplafondobject de relatie met Geluidberekeningsobject uitbreid wordt van "exact één" naar "één of twee". [1..2]. Nadeel is dat dit dan voor alle GPPobjecten geldt. Toevoegen van een extra objecten maakt het IMgeluid wat explicieter.
4. ??

**Comment by wilkoquak** [comment]
Het wijzigings verzoek: Bij spoor moet het mogelijk zijn twee geluidberekeningsobjecten toe te voegen. Een voor spoor, en een voor industrie (want emplacementen vallen onder ‘industrie’.

**Comment by PB-GNM** [comment]
Aangepast conform besluit 15 november:
![image](https://user-images.githubusercontent.com/80040145/157636816-3fe1958b-b433-440d-82b8-d0c11fa282df.png)

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.

**Comment by wilkoquak** [comment]
Logischerwijs had deze wijziging wellicht ook doorgevoerd moeten worden voor de link van Monitoringresultaat een Geluidberekeningobject.

Ik heropen het issue om deze vraag op te helderen.

**Comment by wilkoquak** [comment]
Ik ga ook de relatie vanuit Monitoringresultaat de kardinaliteit 1..2 geven:
![image](https://user-images.githubusercontent.com/2814052/193777891-375e6a92-bb7c-4b35-9e70-51eadeae5815.png)

**Comment by wilkoquak** [comment]
Overigens betekent deze wijziging wel dat er een nieuw GML-Applicatieschema gepubliceerd moet worden. Deze is WEL backwards compatible omdat bestaande content geldig blijft.
