### ISSUE TITLE
Enumeration SporstaafruwheidwaardeCategorie hernoemen naar SpoorstaafruwheidwaardeCatagorie

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#146]
Dit is een typefout die nog niemand is opgevallen.

**Comment by PB-GNM** [comment]
Hoi Wilko,
Mij was het toevallig vorige week opgevallen toen ik er mee bezig was. 
Dus los van jouw melding. Ik heb hem dus al aangepast in versie 1.2.
Ik sluit de melding.
groet,
Pieter
