### ISSUE TITLE
Snelheid op het spoor per dagdeel (SDIMG-48)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#147]
Er is behoefte aan uitsplitsen van de snelheid op het spoor per dagdeel. 

Dit issue is voortgekomen uit issue https://github.com/Geonovum/IMG/issues/132

**Comment by PB-GNM** [comment]
Suggestie van Jan Skornsek:
Een oplossing zou kunnen zijn om een 'keuze' (choice) element gebruiken, zoals we in versie 1.1 voor staafruwheid hebben gebruikt. Het huidige attribuut 'dagdeel' -in de huidige functie- hernoemen we dan naar iets van 'tijdsperiode' of 'tijdsperiodeeenheid' worden. Daarbinnen heb je de keuze uit: dagdeel (dag, avond, nacht) of etmaal (altijd vaste waarde 'etmaal')  In dat geval heeft de CVGG geen extra validatieregels nodig, en je ondersteunt beide opties. De de leveranciers moeten wel extra check uitvoeren. Hun software werk uiteindelijk altijd met dagdelen. Geen idee of dat vanuit infomatiemodellering zou kunnen, maar geef het idee even mee, voordat ik het vergeet.

**Comment by TheoVerheij** [comment]
In het overleg van 13 december werd als argument aangevoerd dat met "dagdeel" bij de snelheid het bestand 3x zo groot zou worden. Dat is uiteraard niet zo, alleen het blokje "snelheid" komt telkens 3x voor in plaats van 1x.
Dat betekent in het voorbeeldbestand dat deze in bytes 12% groter wordt en in aantal regels 13%.
Dat is niet niks, maar valt volgens mij wel mee.

**Comment by wilkoquak** [comment]
Als we dit doen komt er weer een validatieregel bij dus misschien meteen kijken hoe we dit met #150 oplossen

**Comment by wilkoquak** [comment]
18-01-2022 Adviesgroep IMG: Om te voldoen aan de reken- en meetvoorschriften is besloten om dagdelen toe te voegen aan het informatiemodel. Het is namelijk wettelijk verplicht van geluidbrongegevens de intensiteit en snelheid per etmaalperiode te leveren.

**Comment by wilkoquak** [comment]
Via wijzigingsvoorstel #173 gaat het mogelijk worden om een blokje snelheidgegevens voor meerdere dagdelen te laten gelden.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
