### ISSUE TITLE
Geluidbronindustrie geometrietype van GM_POINT naar GM_MultiPoint (SDIMG-55)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#148]
Voorstel Theo Verheij:

> Bronnen welke onderdeel uitmaken van een lijnbron of een vlakbron worden geschreven als “Geluidbronindustrie” met een verwijzing naar “LijnbronIndustrie” of “VlakbronIndustrie”. 
> 
> Nu is het zo dat een vlakbron (en ook lijnbron) uit heel veel puntbronnen kan bestaan. Al deze puntbronnen hebben afgezien van de “geometrie” identieke attributen. 
> 
> Is het niet mogelijk om het geometrietype van “GM_POINT” te wijzigen in “GM_MultiPoint”? 
> 
> Dat scheelt enorm veel data, beperkt het aantal (unieke) NEN3610 identificaties en dit maakt in een keer duidelijk dat deze bronnen onderdeel vormen van een lijn- of vlakbron. Een enkele puntbron kan nog steeds geschreven worden, aangezien een “GM_MultiPoint” ook uit 1 punt kan bestaan.

**Comment by PB-GNM** [comment]
Het is als volgt verwerkt in v1.3:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/80040145/155496627-740e8c14-b10c-4d84-a6bf-cdc5f87df203.png">

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
