### ISSUE TITLE
Voorstel invoeren objecttype GeluidcontourSet (SDIMG-58)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#149]
Ingebracht door Edwin Verheijen:

Het voorstel is het invoeren van objecttype GeluidcontourSet in het domein Cumulatief, omdat de gegevens voor veel geluidcontouren hetzelfde zijn.
Door ze dan aan de GeluidcontourSet te koppelen hoeven er minder gegevens opgeslagen te worden.

**Comment by PB-GNM** [comment]
Toelichting:
![image](https://user-images.githubusercontent.com/80040145/138881880-f18c8a3c-2362-4f9e-a9e7-78a6ebc99b0a.png)
Waar nu geluidcontour staat komt in het model volgens het voorstel geluidcontourSet te staan en links daarvan de geluidcontour. Attributen die per set gelden komen daar terecht en die per geluidcontour gelden blijven bij de geluidcontour.

**Comment by PB-GNM** [comment]
De voorgestelde oplossing is uitgebeeld in onderstaande afbeelding. Kan iemand vast aangeven of de onderstaande attributen van GeluidContour dan nog nodig zijn?:
-typeMaat
-naam
-omschrijving
<img width="569" alt="image" src="https://user-images.githubusercontent.com/80040145/152322012-c6a7b917-b84d-4f56-8462-97e35d84672a.png">

**Comment by Gtrouborst** [comment]
## Aanpassingen 15-03-2022
 - Nieuw object `GeluidcontourSet` aangemaakt
 - Bestaande **definitie** en **toelichting** van `Geluidcontour` onaangepast
 - Voorstel **definitie** en **toelichting**  `GeluidcontourSet` toegevoegd
 - Attributen opgesplitst en verdeeld over beide objecten
 - Relatie **source**:`GeluidcontourSet`, **target**: `Geluidcontour`
### 1 Objecten + relatie
![image](https://user-images.githubusercontent.com/36916421/158359189-e75ece44-7ed6-4323-ad56-8a4e5721fd40.png)
### 2 Geluidcontour
![image](https://user-images.githubusercontent.com/36916421/158359656-187bcaa4-613d-46a2-b0f4-f1f900f7eae9.png)
### 3 GeluidcontourSet (voorstel)
![image](https://user-images.githubusercontent.com/36916421/158359860-9887561a-8aa1-4948-9067-d67b1408db48.png)
### 4 Opmerking
De voorgestelde relatie stelt dat een `GeluidcontourSet` één of meer `Geluidcontour`-objecten kan hebben. Omdat het er dus ook **één** kan zijn, vind ik het **suffix '_set_' verwarrend**. 
#### Voorstel:

1. De **naamgeving** van beide objecten beter op elkaar **afstemmen**.
2. Of de **multipliciteit** van aan de **target-kant** veranderen in `2..*`, indien geluidcontouren per definitie als set voorkomen.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
