### ISSUE TITLE
Wijzigingsverzoek: verminderen regels (SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#150]
Hierbij het volgende wijzigingsverzoek voor het IMG: 

Graag uitzoeken welke regels vervangen kunnen worden door deze te modelleren waardoor ze opgenomen worden in het xsd. 

Hartelijke groet, 

Dorien

**Comment by wilkoquak** [comment]
De regels in IMGeluid zijn geïnventariseerd. Hieruit is gebleken dat er een tiental regels is die door een aanpassing in het UML gevalideerd kunnen worden in het XSD. Voor deze regels worden individuele wijzigingsvoorstellen gemaakt.

**Comment by wilkoquak** [comment]
Voorstel. Maak van Hoogtelijnspecificatie een gegevensgroep. Maak deze gegevensgroep een optionele eigenschap van Hoogtelijn.

**Comment by wilkoquak** [comment]
Alle issues die naar aanleiding van dit bovenliggende issue nodig waren zijn aangemaakt. Voor het bovenliggende issue is geen werk meer nodig. Deze sluit ik dus.
