### ISSUE TITLE
Wijzigingsverzoek: volgorde attributen (SDIMG-57)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#151]
Hierbij een wijzigingsverzoek om de volgorde van de attributen consequenter en daarmee logischer te maken. Voorstel voor de volgorde is dan: 

ID
Geometrie
….
Xlink

Hartelijke groet, 
Dorien

**Comment by PB-GNM** [comment]
13-12-2021 is besloten dat de volgorde wordt:
ID – naam – omschrijving – geometrie – attribuutsoorten die vaker voorkomen – rest. 
Attribuutsoorten uit overerving staan altijd bovenaan.

**Comment by Gtrouborst** [comment]
#### 14-03-2022
Volgorde attributen bij **Objecten** en **Gegevensgroeptypen** aangepast o.b.v. van bovenstaande volgorde. 
Als aanvulling hierop zijn de volgende principes toegepast:

- Attributen met het datatype `DoubleList` direct _na_ het attribuut `geometrie` gezet, omdat zij feitelijk bij elkaar horen.
- Dat geldt ook voor andere hoogte-attributen (bijv. `hoogteReferentiepunt`)
- Na de `geometrie` of `hoogte` is indien aanwezig de ‘waarde’ (bijvoorbeeld: `geluidproductieplafond`) geplaatst.

#### Volgorde

1. ID
2. naam
3. omschrijving
4. geometrie
5. hoogte/DoubleList
6. waarde
7. attributen die vaker voorkomen
8. rest

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
