### ISSUE TITLE
Inkapselen van objecten uitzetten (SDIMG-61)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#152]
Namens Dorien Lolkema:
Graag de mogelijkheid voor hetinkapselen van objecten uitzetten, zodat objecten alleen byReference meegegeven kunnen worden.

**Comment by PB-GNM** [comment]
Met inkapselen wordt bedoeld dat een gegeven in een GML bestand bij de eerste instantie waar het voorkomt in het object waar het bij hoort inline opgenomen wordt, in plaats van via een referentie link (byReference) op een eigen plek.
Bij de Inline variant wordt dan voor een volgende instantie met hetzelfde gegeven verwezen naar  het gegeven in de eerste instantie. Bij de byReference variant wordt er bij de eerste instantie alleen een link gegeven. Het gegeven staat dan apart elders in het GML bestand.

**Comment by wilkoquak** [comment]
Het inkapselen is een feature van GML.  Bij het genereren van het GML applicatieschema uit het UML diagram zou je deze feature uit of aan moeten kunnen zetten met een switch. Deze switch is momenteel nog niet geïmplementeerd in de transformatiesoftware, maar is wel aangevraagd bij de ontwikkelaar. Zodra de switch werkt zal ik hem in de juiste stand zetten en de gewenste schema's genereren. In de standaard staat nu in tekst dat de genoemde feature niet gebruikt mag worden. Het schema dwingt dat dus nog niet af.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
