### ISSUE TITLE
Geluidberekeningsobjecten voor spoor en industrie mogelijk maken bij Spoor (SDIMG-46)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#153]
Namens Dorien Lolkema en Theo Verheij,

Het wijzigingsverzoek is:
Bij spoor moet het mogelijk zijn twee geluidberekeningsobjecten toe te voegen. Een voor spoor, en een voor industrie (want emplacementen vallen onder ‘industrie’.

De aanleiding is de volgende vraag van Theo:

In hoofdstuk 4.8.10 staat dat bij spoor 2 verschillende geluidberekeningobjecten voorkomen: een Geluidberekeningobject voor normale sporen en een IndustrieRekeninstellingen voor emplacementen. 
Is ook logisch omdat deze ene volgens de railverkeerslawaai methode berekend moet worden en de ander volgens industrielawaai. 

Maar: 

-  In het voorbeeldbestanden “Aanleverbestand_hoofdspoor_vaststelling.gml” en “Aanleverbestand_hoofdspoor_monitoringresultaat.gml” ontbreekt de 2e.
- Zoals ik het begrijp is een GPP-waarde voor spoor is de spectrale sommatie van de bijdragen van spoorbanen en de bijdragen van de industriële bronnen van de emplacementen. Vanuit een Geluidproductieplafondobject wordt verwezen naar excact één Geluidberekeningobject. Dat betekent dan dat de waarde voor de geluidproductieplafond of met railverkeer is berekend, of met industrielawaai, maar niet met beide.
- Hetzelfde geldt voor een aandachtsgebied: deze kan ook verwijzen naar maximaal één Geluidberekeningobject. Dus ook dan is het aandachtsgebied niet de sommatie van spoor en emplacement.

**Comment by wilkoquak** [comment]
Duplicate of: 143

**Comment by wilkoquak** [comment]
Duplicate of #143
