### ISSUE TITLE
geluidafschermSpoor --> geluidschermSpoor

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#154]
De uitgaande relatie vanuit Brug heet geluidafschermSpoor, dat zou geluidschermSpoor moeten zijn.

**Comment by wilkoquak** [comment]
De uitgaande relatie vanuit Brug hernoemd van geluidafschermSpoor naar geluidschermSpoor.

**Comment by PB-GNM** [comment]
Toch nog even weer geopend tot versie 2.0 goedgekeurd is.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
