### ISSUE TITLE
Toevoegen naam en omschrijving bij Optrektoeslagvlak (SDIMG-54)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#155]
Het object “Optrektoeslagvlak” heeft geen velden “naam” en “omschrijving”.
Het wijzigingsvoorstel is om deze toe te voegen. 
Het is een kwestie van consequent zijn. Lijn- en vlakbronnen hebben wel een naam en omschrijving, waarom een optrektoeslagvalk niet. Lijkt mij logisch om alle FeatureMembers (met geometrie) een naam en omschrijving te geven.

**Comment by rbalkema1965** [comment]
Het object ‘Optrektoeslagvak’ komt waarschijnlijk uit de systematiek van Geomilieu want in Winhavik gebruik je geen optrektoeslagvlakken maar moet je een optrektoeslag met een punt aan een rijlijn koppelen. Zijn hierover afspraken gemaakt met beide softwareleveranciers?

**Comment by skornsekj** [comment]
@rbalkema1965 Ter toelichting op je vraag. Dit is afgestemd met softwareleveranciers. In de modellering vorm een punt steeds de basis (Optrektoeslagpunt). Facultatief kun je een vlak toevoegen (Optrektoelsagpunt). Je opmerking en deze toelichting staat trouwens los van dit specifieke wijzigingsverzoek zelf.

**Comment by PB-GNM** [comment]
Het is verwerkt in v1.3 en ziet er nu als volgt uit:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/80040145/155487551-cf944762-6fb5-4766-8d4f-be3435601762.png">

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
