### ISSUE TITLE
W3C Validaties doen op laatste versie

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#156]
De versie 1.2 van IMG voldoet nog niet aan alle W3C eisen.

**Comment by wilkoquak** [comment]
Oplossingsvoorstel:
- We draaien de validatie voor de volgende publicatie en lossen de relevantie dingen op.
- We nemen het aanroepen van de validaties op in het werkproces voor publicatie.

**Comment by wilkoquak** [comment]
Ik heb de W3C markup validatie gedraaid. Dat was niet zo heel nuttig om de HTML van de standaard gegenereerd is. De fouten en waarschuwing die gevonden worden zijn niet van een soort dat ze de bruikbaarheid van de standaard beïnvloeden. Hier ga ik niet mee verder. Wel ga ik nog de validatie op broken links doen dat is nuttiger.

**Comment by wilkoquak** [comment]
Met de broken link checker heb ik een paar fouten verwijderd. Verder heb ik in onze workflow voor het publiceren van de standaard een stap toegevoegd voor het uitvoeren van de broken link validatie.
