### ISSUE TITLE
Versienummer van de standaard opnemen in titel van document

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#157]
Bij het gebruik van de standaard spreekt met wel eens van versie 1.2 van de standaard.  Echter, momenteel heeft de standaard zelf geen versienummer, maar wordt er in de standaard verwezen naar een bijbehorend xsd (en die heeft wel een versienummer). Het is het overwegen waard om in de titel van het informatiemodel het versienummer op te nemen, zodat je tenminstel kan spreken over versie 1.2 van het informatiemodel.

**Comment by wilkoquak** [comment]
Hoewel dit issue niet besproken is bleek tijdens de vergadering van de adviesgroep wel dat een duidelijke versienummer van het document wenselijk is. Ik ga deze uitvoeren. Overigens komt er binnenkort een nieuwe versie van de software waarmee we de standaarden schrijven/beheren. In deze versieis ruimte gereserveerd op het voorblad voor een versienummer. Vooruitlopend hierop zet ik het versienummer in de titel.

**Comment by PB-GNM** [comment]
Nog even weer geopend totdat v2.0 goed gekeurd is.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
