### ISSUE TITLE
Mogelijk maken dat 2 besluiten gelijktijdig van toepassing kunnen zijn op een luchthaven (SDIMG-62)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#158]
Als ik het IMGeluid goed begrijp, is er voor luchthavens altijd één luchthavenbesluit. Dit komt niet overeen met de wettelijke situatie voor Schiphol. Schiphol kent twee besluiten: één besluit waarmee het luchthavengebied is vastgelegd. Een ander besluit op basis waarvan je bij benadering zou kunnen stellen dat het de geluidcontouren ‘vastlegd’. 

Met vriendelijke groet, 

ir. Maarten van der Niet

**Comment by PB-GNM** [comment]
https://docs.geostandaarden.nl/cvgg/img/#EAID_0C92279C_28A6_4454_84DC_4ACAECE11937

![image](https://user-images.githubusercontent.com/80040145/142207189-0b1c00b9-eeff-4e25-96a6-4d1f4fdc11c2.png)

**Comment by skornsekj** [comment]
@maarten

* in principe willen we alleen relatie leggen met het besluit dat de geluidcontouren heeft bepaald. Vooral in het kader van herleidbaarheid. Besluiten die te maken hebben met grondgebonden geluid, vallen daar buiten. Dat valt - als ik het goed begrijp - onder een industrieterrein met GPP. In jouw tekst doel je volgens mij bij het 1ste type besluit op de vastlegging van het luchthavengebied. De grenzen van het luchthaven terrein nemen we alleen op voor visualisatie doeleinden. En is ook geen verplicht element. 

Gaat jou opmerkingen dan nog steeds op? Of zijn toch beiden besluiten toch bruikbaar, om voor een burger te achterhalen welke besluit tot deze geluidcontouren geleid hebben? 

Groet,
Jan Skornsek

**Comment by MaartenVanDerNiet** [comment]
Als je alleen de herkomst van de geluidcontouren wil vastleggen, is deze wijziging niet nodig. Uit de toelichting op het datamodel zou duidelijk moeten blijken, dat de herkomst van het luchthavengebied alleen voor visualisatie doeleinden wordt gebruikt en om die reden geen verwijzing is opgenomen van de herkomst van de grenzen van het gebied.

Overigens hangt dit wijzigingsverzoek inmiddels samen met https://github.com/Geonovum/IMG/issues/159. Hierin staat dat het opnemen van de herkomst van geluidcontouren niet verplicht zou moeten zijn.

Mvg,
Maarten

**Comment by Gtrouborst** [comment]
## Aanpassingen 15-03-2022
 - De **«Enumeratiewaarde»** `luchthaventerrein` van de **«Enumeratie»** `Terreintype` aangepast naar `luchthavengebied`
 - Aan de **«Enumeratiewaarde»** `luchthavengebied` een toelichting toegevoegd

### Luchthavengebied
 - **Definitie**: Een aangewezen terrein ingericht voor het opstijgen en landen van luchtvaartuigen.
 - **Toelichting**: Een luchthavengebied wordt alleen voor visualisatie-doeleinden gebruikt. Om die reden is er geen verwijzing opgenomen naar de herkomst van de grenzen van het gebied.
![image](https://user-images.githubusercontent.com/36916421/158370826-e9fd1c15-cf60-46d3-8313-58dc9bb16caa.png)

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
