### ISSUE TITLE
Verplicht veld in datamodel over luchthavenbesluit optioneel maken (SDIMG-63) 

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#159]
Dit verzoek is afkomstig van Maarten van der Niet (I&W, Directie Luchtvaart):

In het IMGeluid staat dat er voor luchthavens altijd een luchthavenbesluit (=object Documentverwijzing in het [Cumulatief overzicht](https://docs.geostandaarden.nl/cvgg/img/#EAID_0C92279C_28A6_4454_84DC_4ACAECE11937)) is, waarop de contouren zijn gebaseerd. Dit is niet overeenkomstig de regelgeving. Er kunnen ook contouren in de CVGG worden opgenomen zonder dat deze zijn gebaseerd op een luchthavenbesluit. Dit invoerveld moet daarom optioneel zijn en niet verplicht.

De tekst hieronder is afkomstig van mijn collega Joris Broers die bij BZK (straks VRO) aan de regelgeving onder de Omgevingswet meewerkt. Het Bold en Italic gemarkeerde deel is hierbij relevant.

Begin citaat

We hebben dit vrij laat voor publicatie nog aangepast in het Aanvullingsbesluit geluid. Wat er in de CVGG moet komen te staan is niet informatie uit het LIB, maar gegevens over de luchthaven waarvoor het LIB vereist is. Er hoeven geen gegevens te worden geleverd voor luchthavens waarvoor volstaan kan worden met een luchthavenregeling (ondanks dat de 48 Lden-contour buiten het luchthaventerrein kan liggen). Voor luchthavens waarvoor de luchthavenbesluiten of hun voorlopers nog in Kosteneenheden zijn uitgedrukt moeten toch contouren in dB worden geleverd.
Van het datamodel heb ik geen verstand.

Art. 3.38 Bkl kun je inmiddels vast dromen (als je er geen nachtmerries aan overhoudt):

3. Bij het bepalen van het gecumuleerde geluid wordt in ieder geval betrokken:
...
b. voor een geluidgevoelig gebouw binnen de 48 Lden geluidcontour of, voor zover de geldende geluidcontouren in Kosteneenheden zijn uitgedrukt, binnen de 20 Kosteneenheden geluidcontour van een luchthaven waarvoor op grond van de Wet luchtvaart een luchthavenindelingbesluit, een luchthavenbesluit of een besluit beperkingengebied buitenlandse luchthaven is vereist: het geluid door luchtvaart;
...

Zie ook de toelichting daarop:

In onderdeel b is voor de luchtvaart aangesloten op de contouren uit de luchtvaartwetgeving. Als voor een luchthaven contouren zijn vastgesteld in Lden, geldt de cumulatieverplichting vanaf 48 Lden. Zijn contouren nog vastgesteld in Kosteneenheden, dan geldt de cumulatieverplichting vanaf 20 Kosteneenheden. _**Die contouren zijn niet altijd te vinden in de besluiten op grond van de Wet luchtvaart, maar zij zullen wel worden opgenomen in de Centrale voorziening geluidgegevens.**_ De formulering «van een luchthaven waarvoor op grond van de Wet luchtvaart een luchthavenindelingbesluit, luchthavenbesluit, of besluit beperkingengebied buitenlandse luchthaven is vereist» sluit ook de luchthavens in waarvoor nog geen luchthavenbesluit is vastgesteld, maar nog een overgangsrechtelijke regeling geldt (een omzettingsregeling, aanwijzing op grond van de Luchtvaartwet of een besluit zonering buitenlands luchtvaartterrein). De beoordeling van gecumuleerd geluid daarvoor was voorheen niet geregeld in artikel 110f van de Wet geluidhinder, maar in artikel V, onder B, van de Wet van 18 maart 2010 tot wijziging van de Wet luchtvaart en enkele andere wetten, houdende diverse wijzigingen met betrekking tot de luchtvaart (Stb. 2010, 149) en artikel III, tweede lid, van de Wet van 8 november 2012 tot wijziging van de Wet luchtvaart met betrekking tot de gevolgen van buitenlandse luchthavens voor de ruimtelijke ordening op Nederlands grondgebied (Beperkingengebied buitenlandse luchthaven) (Stb. 2012, 582). Omdat deze overgangsrechtelijke bepalingen naar de ingetrokken Wet geluidhinder verwijzen, grijpen zij niet langer aan en is de verplichting naar dit besluit verplaatst. De term «luchthavenindelingbesluit» wordt nog gebruikt omdat inmiddels verwacht wordt dat artikel 2.44 van de Invoeringswet Omgevingswet – waarmee de benaming luchthavenindelingbesluit komt te vervallen – niet tegelijk met de Omgevingswet in werking zal treden.

Einde citaat

**Comment by DorienLolkema** [comment]
Er wordt gezegd dat de geluidcontouren niet altijd opgenomen zijn in besluiten op grond van de Wet luchtvaart. Zijn de contouren wel in andere besluiten/documenten opgenomen? Zo ja, dan kan er dus wel een documentverwijzing opgenomen worden. Alleen zal de beschrijving van het veld aangepast moeten worden.

Mijn zeer sterke voorkeur is om wel **altijd** een documentverwijzing op te nemen.

**Comment by skornsekj** [comment]
Voor Luchtvaart moet een documentverwijzing worden opgenomen. Daar kun je een keuze maken uit een t[ype document. ](https://docs.geostandaarden.nl/cvgg/img/#detail_class_IMGeluidAlgemeen_Documenttype). Dat hoef niet altijd een besluit (wat voor soort besluit dan ook) te zijn, maar bijv ook een melding.

**Comment by GerdadeVries23** [comment]
Voorstel aanpassing definitie Documenttype
(en ongewijzigd laten van het verplichte veld Documentverwijzing bij aanlevering luchthavencontouren)

In het Informatiemodel Geluid (IMG) is verplicht gesteld dat bij een aanlevering van de geluidcontouren van een luchthaven ook een link naar een document wordt opgenomen. Een document is een besluit, melding of monitoringsrapportage. Een luchthaven(verkeers)besluit wordt niet expliciet genoemd, de definitie is onterecht beperkt tot besluiten over gpp’s (5.14).
De achtergrond van deze verplichting is het volgende.
De bedoelde contouren in artikel 11.52 Bkl (geluidregister) zijn de contouren van het toegestane geluid. Het gegeven is gerelateerd aan een bepaald doel, namelijk het kunnen uitvoeren van artikel 3.38 Bkl over cumulatie van geluid. De gegevens moeten verplicht gebruikt worden op grond van artikel 3.27 Omgevingsregeling, en daarom moet de status van de gegevens in de Cvgg onbetwistbaar zijn. Dat kan alleen als de gegevens zijn gebaseerd op een rechtsgeldig besluit. Daarom vraagt het Informatiemodel Geluid naar een (link naar een) besluit. Het besluit hoeft niet de 1 dB-contouren te bevatten, maar wel de wettelijke contouren, en de 1 dB contouren moeten met dezelfde uitgangspunten als voor deze wettelijke contouren worden bepaald.
Bij luchthavens die nog geen Luchthavenbesluit hebben, maar waarvoor wel contouren gelden op basis van een overgangsrechtelijke regeling (een omzettingsregeling, aanwijzing op grond van de Luchtvaartwet of een besluit zonering buitenlands luchtvaartterrein), kan wel worden gesproken van toegestaan geluid. Bij de aanlevering van geluidcontouren voor zo’n luchthaven kan dan naar zo’n document verwezen worden.
Voor Schiphol is er echter nog geen Luchthavenbesluit en de bestaande besluiten (Luchthavenindelingsbesluit LIB en Luchthavenverkeersbesluit LVB) zijn sterk verouderd en ongewenst om van uit te gaan (veel meer geluidruimte dan waarop nu gehandhaafd wordt). Als tijdelijke oplossing kan het MER voor het voorgenomen  Luchthavenverkeersbesluit als basis worden gebruikt voor de geluidcontouren in de Cvgg. Het voornemen is om dit ook wettelijk te regelen, maar dit heeft enige doorlooptijd. Zodra het nieuwe Luchthavenverkeersbesluit is vastgesteld, kunnen dan de nieuwe geluidcontouren (identiek of gewijzigd) aangeleverd worden met een link naar dit besluit.

Voorstel aanpassing definitie Documenttype 'Besluit':
Het meest actuele juridische besluit waarin een geluidproductieplafond of de wijziging daarvan als omgevingswaarde is vastgelegd.
Het meest actuele juridische besluit waarin het toegestane geluid voor een windturbinepark, een schietterrein of een luchthaven is vastgelegd.
Tijdelijke afspraak voor Schiphol: het MER van december 2020 waarin de geluidcontouren voor het voorgenomen Luchthavenverkeersbesluit zijn vastgelegd.

Voorstel aanpassing definitie Documenttype 'Melding': 
Verwijzing naar een melding in geval het geval van een windturbine of geluidcontouren van een schiet- of springterrein.

**Comment by PB-GNM** [comment]
Dat betekent dus een aanpassing in : https://geonovum.github.io/IMG/#detail_class_IMGeluidAlgemeen_Documenttype
Dit is hoe het was in versie 1.2:
![image](https://user-images.githubusercontent.com/80040145/157020183-577545bd-0a41-413f-8bdc-cdd94a3bb25e.png)

**Comment by PB-GNM** [comment]
Verwerkt conform bovenstaande voorstel.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
