### ISSUE TITLE
Regel bij klasse Documentverwijzing verplaatsen naar toelichting (CVGG037 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#160]
Wijzigingsverzoek vanuit #150 is:
De regel bij klasse Documentverwijzing "Het is toegestaan om meerdere besluiten bij een GPP op te nemen, inclusief een tijdelijk ontheffingsbesluit." verplaatsten naar toelichting.
![image](https://user-images.githubusercontent.com/80040145/155989461-31c2accb-51d0-453d-b93c-4494c9e5de29.png)

**Comment by PB-GNM** [comment]
Komt voort uit #150

**Comment by PB-GNM** [comment]
Besluit 25-4-2022: doen zoals voorgesteld.

**Comment by PB-GNM** [comment]
Uiteindelijk zijn de eerste en de laatste regel verplaats naar de toelichting, omdat ze al door de kardinaliteiten worden afgedwongen.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
