### ISSUE TITLE
Terreintypen uitsplitsen (CVGG043 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#161]
Wijzigingsverzoek vanuit https://github.com/Geonovum/IMG/issues/150 is: 
vervang:
![image](https://user-images.githubusercontent.com/80040145/155994360-23285e02-30c2-45fa-bfbb-28b0b84a703a.png)
door:
![image](https://user-images.githubusercontent.com/80040145/156014439-6420eab1-e655-4e16-ae66-f0632b55fd2e.png)

**Comment by wilkoquak** [comment]
Dit zijn een beetje veel extra klasses om 1 validatie weg te krijgen. Dat is een beetje teveel van het goede. We behouden de regel. Een uitzoekpuntje is of we het attribuut niet verplicht kunnen maken voor alle klasses!  Dit issue blijft hangen tot we antwoord hebben op deze vraag, die per email is gesteld aan de expert.

**Comment by PB-GNM** [comment]
**Vraag Thomas aan Arnaud:**
Voor GPP industrie objecttype: terrein is het nu optioneel om een geometrie toe te voegen. We vroegen ons af of we het ook verplicht kunnen stellen om voor een terrein een geometrie in te vullen.

**Antwoord Arnaud:**
Dit is niet echt iets van het RMG. Is er uit het verleden een reden geweest om dit optioneel te maken? Het probleem is dat de afbakening van een industrieterrein niet als geluidbrongegeven is opgenomen in de omgevingsregeling. Dit zou dus inhouden dat wij meer verplicht gaan stellen dan wat er in de regelgeving staat. Dus dit is wel iets dat ook met IenW besproken zou moeten worden.

**Comment by wilkoquak** [comment]
Bij industrieterrein is er sprake van een bodemfactor (#144) . Als die bodemfactor in het model komt is het sowieso verstandig om af te splitsen. Anders niet. SchietOfSprintterrein en Luchthaventerrein mogen geschrapt als losse klasse.

**Comment by PB-GNM** [comment]
Besluit 25-4-2022: alleen subtype industrieterrein en die andere krijgen dan geen geometrie.

**Comment by PB-GNM** [comment]
Dit is verwerkt in versie 1.3 tot het volgende:
![image](https://user-images.githubusercontent.com/80040145/166215516-f042f080-738b-45a9-b8c9-0237a12ed10d.png)
De regel dat de geometrie verplicht is voor industrieterreinen is hiermee komen te vervallen.

**Comment by PB-GNM** [comment]
Dit heeft wel tot gevolg dat er een nieuwe regel bij is gekomen: Bij een Industrieterrein moet het terreinType industrieterrein zijn.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.

**Comment by wilkoquak** [comment]
Het doorvoeren van de deze wijziging levert een extra regel op, dat was al geconstateerd. Maar er is ook nog een onduidelijkheid:
- Mag een gewoon Terrein nog wel gelabelled worden als industrieterrein?

**Comment by wilkoquak** [comment]
Ik beantwoord deze vraag met NEE want dan zou je een indudstrieterrein kunnen maken zonder standaardbodemabsorptiefractie.

**Comment by wilkoquak** [comment]
Ik ga bij Terrein een regel toevoegen met als inhoud: De waarde 'industrieterrein' voor typeTerrein mag alleen gebruikt worden bij instanties van de subklasse Industrieterrein.
