### ISSUE TITLE
Combinaties van attributen van gegevensgroep "VerkeersgegevensWeg" omzetten in aparte gegevensgroepen (CVGG047/48 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#162]
Naar aanleiding van #150 wordt het volgende voorgesteld:

De situatie was:
![image](https://user-images.githubusercontent.com/80040145/156170359-51f0cd76-9640-4ae9-84b1-64434b7731f5.png)

De gegevensgroep "VerkeergegevensWeg" wordt vervangen door de volgende 9 gegevensgroepen waarin de attributen dagdeel en voertuigklassificatie vervallen:

1. VerkeersgegevensWegDagLicht
2. VerkeersgegevensWegDagMiddelzwaar
3. VerkeersgegevensWegDagZwaar
4. VerkeersgegevensWegAvondLicht
5. VerkeersgegevensWegAvondMiddelzwaar
6. VerkeesrgegevensWegAvondZwaar
7. VerkeersgegevensWegNachtLicht
8. VerkeersgegevensWegNachtMiddelzwaar
9. VerkeergegevensWegNachtZwaar

WegdeelGPP en WegdeelBGE krijgen dan deze 9 attributen i.p.v. alleen "verkeersgegevensWeg".
Omdat ze allemaal kardinaliteit 1 hebben kan de regel dat elke combinatie 1x voor moet komen vervallen.

**Comment by skornsekj** [comment]
Detail. Let even op de schrijfwijze. Die was net verandert naar Verkeer**s**gegevensweg

**Comment by wilkoquak** [comment]
Je kunt het ook nog in twee stukken doen door een klasse VerkeersgegevensPerDagdeel te maken. dan heb je drie keer drie klasses. Dit is het voorstel wat we gaan voorleggen met een UML plaatje erbij.

**Comment by wilkoquak** [comment]
Het zou er dan bijvoorbeeld zo uit kunnen zien:

![image](https://user-images.githubusercontent.com/2814052/159680356-4fb47be7-9a2e-41f3-8633-ea487f04c9ad.png)

**Comment by PB-GNM** [comment]
Dit moet dan ook voor WegdeelBGE doorgevoerd worden.
![image](https://user-images.githubusercontent.com/80040145/159716545-fa630f01-39c7-4101-961e-6df19bda33d5.png)

**Comment by PB-GNM** [comment]
Besluit 25-4-2022: 18 attributen (9 maal snelheid en 9 maal aantal)

**Comment by PB-GNM** [comment]
Verwerkt in versie 1.3. De enumeratie voertuigklasse is verwijderd. Dagdeel niet, want die wordt nog elders in het model gebruikt.
De kardinaliteit van de gegevensgroep was 9 en is nu verwijderd. 
![image](https://user-images.githubusercontent.com/80040145/166238267-494df18d-7e4a-454b-b6c0-44638ef5fde3.png)

Hierna zij de regels bij WegdeelGPP en WegdeelBGE verwijderd die stelden dat elke combinatie van dagdeel en motorvoertuigklasse voor moesten komen voor de snelheid en het aantal motorvoertuigen.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
