### ISSUE TITLE
Drie subklasses maken bij GeluidbronIndustrie: GeluidbronGevel GeluidbronDak en GeluidbronNormaalPunt (CVGG084 en SDIMG59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#163]
Wijzigingsverzoek vanuit #150 is:

Drie subklasses maken bij GeluidbronIndustrie: GeluidbronGevel GeluidbronDak en GeluidbronNormaalPunt
Op die manier kan de uitstralingsrichting dan verplicht gesteld worden, behalve bij de GeluidbronNormaalPunt.

De situatie was:

![image](https://user-images.githubusercontent.com/80040145/156173240-8bf51693-950b-4e70-be6f-f84db7d7f4ac.png)
![image](https://user-images.githubusercontent.com/80040145/156172847-5a571274-58ee-4266-8d48-a13fce5d1be2.png)

**Comment by TheoVerheij** [comment]
Gaan we nu het pad op dat iedere variatie van attribuut een aparte subklasse oplevert? Schieten we niet een beetje door?
En wordt hierbij ook gedacht aan de wijze waarop bronhouders hun gegevens beheren?

**Comment by wilkoquak** [comment]
Overigens is er per email nog een andere discussie geweest (naar aanleiding van de cvgg validatieregel CVGG046). De conclusie daarvan was dat uitstralingsrichting optioneel kan blijven indien er bij een niet ingevulde uitstralingsrichting als default 360 geldt.  Dat zou dus betekenen dat we ook door het stellen van deze default van de validatieregel afkunnen.

**Comment by wilkoquak** [comment]
De regel waar het over gaat is: 'uitstralingrichting kan optioneel aangeleverd worden alleen in het geval dat bron­Type "normale­Puntbron"is'.  Dit is niet helemaal eenduidig, we moeten dus even terug naar de plaats van de regel vandaan komt.

**Comment by PB-GNM** [comment]
**Vraag Thomas aan Arnaud:**
Voor geluidbron industrie is de volgende regel opgenomen: 'uitstralingrichting kan optioneel aangeleverd worden alleen in het geval dat bronType "normale-Puntbron" is'. Hier is de vraag: kunnen we uitstraalrichting verplicht stellen? Als je nu geen uitstraalrichting opgeeft, is de richting dan automatisch 360 graden?

**Antwoord Arnaud:**
Je zou dit verplicht kunnen stellen. In principe is dat als er niks aangegeven wordt het gelijk is aan 360 graden.

**Comment by PB-GNM** [comment]
Besluit 25-4-2022: overal verplicht stellen. Dat kan dan in de toelichting opgenomen worden dat 360 gekozen kan worden als het niet duidelijk is. Er komen dus geen 3 nieuwe subklassen.

**Comment by PB-GNM** [comment]
Verwerkt in versie 2.0. De regel *"uitstralingsrichting kan optioneel aangeleverd worden alleen in het geval dat bronType "normalePuntbron"is."* is verwijderd bij de GeluidbronIndustrie. De kardinaliteit van de uitstralingsrichting is van [0..1] naar 1 gegaan. De volgende toelichting is opgenomen bij het attribuut uitstralingsrichting van objecttype Geluidbronindustrie, en bij objecttype UitstralingsrichtingWaarde: *Wanneer geen uitstralingsrichting bekend is, wordt default 360 graden ingevuld bij de openingshoek van de UitstralingsrichtingWaarde en 0 graden bij de uitstralingsrichting.*

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
