### ISSUE TITLE
Verwijder regel uit Bodemvlak.absorptiefractie (CVGG096 SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#165]
# Aanleiding
Dit is een wijzigingsverzoek dat voortkomt uit #150 voor het verminderen van het aantal regels. In dit geval gaat het om een overbodige regel betreffende de absorbtiefractie van een BodemvlakType.

# Wijzigingsverzoek
De onderstaande geel gemarkeerde regel kan verwijderd worden:

   ![image](https://user-images.githubusercontent.com/80040145/156185373-3e493531-28ef-4935-b0ed-ef7040cd821d.png)

Het staat namelijk al in de tagged value, waardoor de regel automatisch afgedwongen wordt in het xsd-schema.
Hieronder is aangegeven hoe het in Enterprise Architect in de tagged value staat:

   ![image](https://user-images.githubusercontent.com/80040145/156185822-857e2af4-d74d-4825-8028-a912633e7406.png)

In het schema ziet dat er als volgt uit:

   ![image](https://user-images.githubusercontent.com/80040145/169770022-c50127b2-b763-4fc7-936c-5c3ff4e977a0.png)

# Impactanalyse
Dit heeft geen impact.

**Comment by PB-GNM** [comment]
Advies van adviesgroep 30-5-2022: wijziging doorvoeren.

**Comment by PB-GNM** [comment]
De wijziging is in versie 2.0 verwerkt zoals beschreven in het wijzigingsverzoek.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
