### ISSUE TITLE
Alle objecten moeten gerelateerd zijn aan de geluidgegevenscollectie (CVGG103 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#166]
Dit is nog geen wijzigingsverzoek, maar wel een mogelijk discussiepunt dat voortkomt uit #150.

Het koppelen van alle objecten aan de Geluidgegevenscollectie is lastig. Je zou alle objecten kunnen embedden in de Geluidgegevenscollectie. Dan maak je daar het root-element van. Maar dat matcht niet met het issue om alles byReference te doen. #152.  Er zijn ook veel objecten die niet in een collectie kunnen (geen subklasse van Collectieelement) wat moet daarmee? Een voorbeeld daarvan is het Geluidberekeningsobject:
![image](https://user-images.githubusercontent.com/80040145/157072982-20262899-9252-42ce-8bd5-04948a514ece.png)

**Comment by wilkoquak** [comment]
Dit is alleen modelmatig op te lossen door alle elementen te embedden. Dan zou het het probleem uit de wereld zijn. Dat leidt weer tot andere problemen  (zie hiervoor issue #152). Omdat het de bedoeling is elementen juist niet te embedden is het niet mogelijk validatieregels te verminderen op de voorgestelde wijze. Het heeft dus geen nut dit voorstel voort te zetten.
