### ISSUE TITLE
Modelmatig vastleggen dat bij een GeluidschermSpoor de reflectiefactor links en rechts altijd hetzelfde zijn

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#168]
Bij Geluidschermdelen is een reflectiefactorLinks en een reflectiefactorRechts gemodelleerd. Bij spoor moeten deze altijd hetzelfde zijn.  Momenteel wordt met een validatieregels afgedwongen dat deze gelijk zijn door alle waardes te vergelijken. Je kan het ook modelmatig implementeren door bij een GeluidschermdeelSpoor slechts 1 reflectiefactor mee te leveren. De modellering verandert dan van het huidige model:
![image](https://user-images.githubusercontent.com/2814052/156654087-703e1ec8-d2b5-4809-96ac-41ad508fe7f9.png)

naar:
![image](https://user-images.githubusercontent.com/2814052/156654708-a2d3e5f1-e734-443f-b0fa-1daab638c2da.png)

**Comment by wilkoquak** [comment]
Let op! Er is ook sprake van het splitsen van Geluidschermdeel in GeluidschermdeelZwevend en GeluidschermdeelNietzweven. Als je beide doorvoert zou je dus vier klasses krijgen: GeluidchermSpoorZwevend etc. Dit lijkt me niet wenselijk.  Ik word daar niet vrolijk van.  Naar mijn mening moet je alleen een nieuwe klasse splitsen als de afgesplitste klasses intrinsiek verschillend zijn. In dit geval is dat niet zo.

**Comment by TheoVerheij** [comment]
Waar staat vastgelegd dat schermen bij spoor altijd dezelfde reflectiefactor voor de linker- en rechterzijde hebben?
Ook mijn collega's van DGMR IVM klinkt dit vreemd in de oren.

**Comment by wilkoquak** [comment]
Actie: vraag van Theo beantwoorden en als het nergens staat dan hoeft er ook niet gevalideerd te worden.

**Comment by PB-GNM** [comment]
**Vraag Thomas aan Arnaud:**
Voor geluidschermdelen spoor is nu de regel opgenomen dat de reflectiefactor links en rechts altijd gelijk moet zijn. Moet dit ook echt? Het leek ons logisch dat de reflectiefactor wel kan verschillen.

**Antwoord Arnaud:**
Eens met Theo in die discussie. Ze zijn veelal gelijk, maar in theorie hoeft dat niet.

**Comment by PB-GNM** [comment]
Voorstel:
Regel verwijderen, want deze regel is niet van toepassing.

In de toelichting wordt dit verduidelijkt.

**Comment by PB-GNM** [comment]
# Aanleiding
Dit is een wijzigingsverzoek dat voortkomt uit #150 voor het verminderen van het aantal regels. In dit geval gaat het om een overbodige regel betreffende de klasse Geluidschermdeel en zijn attributen reflectiefactorLinks en reflectiefactorRecht.

# Wijzigingsverzoek
De onderstaande geel gemarkeerde regel kan verwijderd worden:

  ![image](https://user-images.githubusercontent.com/80040145/169785720-10859973-fc76-4fba-8b8f-0dc974544c01.png)

Uit de discussie hierboven blijkt dat deze regel overbodig is. 
In deze afbeelding gaat het om reflectiefactorRechts, maar dezelfde regel kan ook verwijderd worden bij reflectiefactorLinks.
In de toelichting zal dit verduidelijkt worden.

# Impactanalyse
Dit heeft geen impact.

**Comment by PB-GNM** [comment]
**Advies van adviesgroep 30-5-2022:** wijziging doorvoeren.

**Comment by PB-GNM** [comment]
De wijziging is in versie 2.0 verwerkt zoals beschreven in het wijzigingsverzoek.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
