### ISSUE TITLE
Gegevensgroep jaargemiddeldeGeluidemissie van Windturbine opsplitsen in 3 attributen (CVGG112 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#170]
Dit wijzigingsvoorstel komt voort uit #150 om het aantal regels te verminderen.
Het voorstel is om de gegevensgroep jaargemiddeldeGeluidemissie van Windturbine opsplitsen in 3 verplichte attributen:
- jaargemiddeldeGeluidemissieDag
- jaargemiddeldeGeluidemissieAvond
- jaargemiddeldeGeluidemissieNacht

Hiermee kan de regel dat ze allemaal 1x moeten voorkomen weg.
De situatie was:
![image](https://user-images.githubusercontent.com/80040145/159702236-5cc5aaf5-4e26-485f-9804-9b97326e6565.png)

**Comment by PB-GNM** [comment]
# Aanleiding
Wijzigingsverzoek dat voortkomt uit #150 om het aantal regels in het model te verminderen.
Het gaat om de regel dat elke combinatie van waardes uit attribuutsoort dagdeel en attribuutsoort jaargemiddeldeGeluidemissiewaarde 1 keer voor moet komen binnen een instantie van Windturbine.

De huidige situatie is:

![image](https://user-images.githubusercontent.com/80040145/169788821-2535d1ce-f9f5-4882-9708-0655de1d0863.png)

# Wijzigingsverzoek
Het verzoek is om de drie mogelijke emissies per dagdeel als aparte attributen bij de klasse Windturbine op te nemen:

Het resulterende model ziet er dan als volgt uit:

In het onderstaande plaatje staat ten onrechte Decimal dit had WaardePerOctaafband moeten zijn.

![image](https://user-images.githubusercontent.com/80040145/169791459-16f718fe-1586-4347-8aa3-5bfd70927820.png)

# Impactanalyse

 - Deze wijziging heeft alleen impact op partijen die windturbines aanleveren: Rijk en Provincies
 - Deze wijziging heeft geen impact op de semantiek van het model
 - De wijziging resulteert wel in niet backwards-compatible wijziging in het xml-schema.

**Comment by ArnaudYK** [comment]
Decimal bij de jaargemiddeldegeluidemissie moet dan wel waardeperoctaafband zijn

**Comment by wilkoquak** [comment]
Dank @ArnaudYK ik heb het in de tekst van het voorstel aangepast.

**Comment by PB-GNM** [comment]
**Discussie van adviesgroep 30-5-2022:** Waarde omzetten naar WaardeperOctaafband in plaats van Decimal

**Advies van adviesgroep 30-5-2022:** wijziging doorvoeren met bovengenoemde aanpassing.

**Comment by PB-GNM** [comment]
De wijziging is in versie 2.0 verwerkt zoals beschreven in het wijzigingsverzoek.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
