### ISSUE TITLE
Subklassen aan OptrektoeslagPunt toevoegen (CVGG113 en SDIMG-59)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#171]
# Aanleiding

Dit wijzigingsvoorstel komt voort uit https://github.com/Geonovum/IMG/issues/150 om het aantal regels te verminderen. Het gaat om de hieronder geel gemarkeerde regel die zou moeten worden verwijderd.
Het voorstel is om de Subklassen OptrektoeslagKruispunt en OptrektoeslagObstakel toe te voegen als subtype van OptrektoeslagPunt.

De situatie was:
![image](https://user-images.githubusercontent.com/80040145/159704526-81c82909-93b3-46d3-b62c-6af5198ab40a.png)

# Wijzigingsverzoek
- Maak twee subklasses van OptrektoeslagPunt: OptrektoeslagKruispunt en OptrektoeslagObstakel
- verplaats het attribuut kruispuntkental naar OptrektoeslagKruispunt en maak het verplicht
- Verwijder het attribuut 'type'.
- Verwijder de regel: 'Alleen als het punt van type 'kruispunt' is, dan is het kruispuntkental verplicht.'.

Het resulterende model ziet er dan als volgt uit:

![image](https://user-images.githubusercontent.com/2814052/169294494-6374f813-45b0-4b27-8f76-f4f947a18933.png)

# Impactanalyse
- Vooral RWS zal wat van deze wijziging merken.
- Semantisch blijft het model ongewijzigd.
- Deze wijziging resulteert wel in een niet backward-compatible change van het xml-schema.

**Comment by PB-GNM** [comment]
**Advies van adviesgroep 30-5-2022:** wijziging doorvoeren

**Comment by PB-GNM** [comment]
De wijziging is in versie 2.0 verwerkt zoals beschreven in het wijzigingsverzoek.

**Comment by wilkoquak** [comment]
Uit een review van het resulterende model gerold dat de klasse OptrektoeslagObstakel geen toegevoegde waarde heeft. Deze klasse is semantisch equivalent met Optrektoeslagpunt. Deze klasse wordt dus verwijderd. Het resultaat ziet er dan als volgt uit...

![image](https://user-images.githubusercontent.com/2814052/174251737-5e85be32-70ae-4b32-a70c-ef30d3d41789.png)

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
