### ISSUE TITLE
Flyover als objecttype toevoegen

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#172]
# Aanleiding wijziging

Fly-overs zijn niet als Objecttype gemodelleerd in het IMGeluid, maar hebben wel een acoustische werking. Daarom worden fly-overs door Rijkswaterstaat als een zwevend geluidscherm uitgewisseld (omdat deze acoustisch dezelfde eigenschappen hebben). Deze oplossing begint echter steeds meer te knellen. 

# Voorgestelde wijziging
Het toevoegen van een nieuwe objecttype FlyoverZijkant aan de standaard. Dit objecttype is een subklasse van Kunstwerk en beschrijft 1 van de zijkanten van een fly-over. Een fly-over wordt dus beschreven door twee zijkanten. In UML ziet dit er als volg uit:

![image](https://user-images.githubusercontent.com/2814052/176963084-b8776fd0-d735-4d3c-a131-dab2245a7491.png)

De geometrie van de FlyoverZijkant beschrijft één zijkant van een fly-over. Het attribuut hoogte geeft de hoogte van de fly-over aan.

# Impactanalyse
 - Voor aanleverende partijen is deze wijziging backwards compatible omdat bestaande bestanden nog steeds geldig zijn.
 - Ontvangende partijen zullen moeten begrijpen wat een Flyover is.

# Toelichting
Het voorstel van het toevoegen van deze klasse komt bij Rijkswaterstaat vandaag omdat de oplossing om Flyovers uit te wisselen als twee zwevende geluidschermendelen steeds meer knelde. Rijkswaterstaat zal dan ook de enige partij zijn die deze objecten aanlevert. Een paar puntjes van de modellering zijn nog niet helemaal duidelijk:
- Er is nog enige onduidelijkheid of de onderkant van de fly-over wordt gemodelleerd en de hoogte naarboven steekt of andersom. Bij uiteindelijke definitie moet dit opgelost worden.

**Comment by skornsekj** [comment]
@wilkoquak 

-  is het nog wenselijk / nodig om te beschrijven wat de z-waarde bij een fly-over precies betekent
- door de introductie van het object 'flyover' geldt voor 'Geluidschermdeel' dat het altijd een geluidwerendeMaatregel betreft. Het attribuut 'geluidwerendeMaartegel' wordt uit Geluidschermdeel verwijderd.
-

**Comment by ThijsRuiterRWS** [comment]
De objecten flyover zijn 2 lijnen aan iedere zijde van de weg. De lijnen beschrijven de onderkant van het object in XYZ en hebben een attribuut met hoogte waar de waarde 1 (meter) in staat. De locatie XY is 5 meter uit het WegdeelGPP en de Z is 1 meter onder het maaiveld van het WegdeelGPP

Zodoende krijg je een de volgende situatie. 

Legenda:
![image](https://user-images.githubusercontent.com/88136917/176881074-c6270a55-d55c-474c-b00a-9e12be91c6bc.png)

Bovenaanzicht:
![image](https://user-images.githubusercontent.com/88136917/176881142-c49a098e-b3dc-4b43-aebe-a945de834fb9.png)

Zijaanzicht:
![image](https://user-images.githubusercontent.com/88136917/176881926-0bf65384-b62d-4930-a3b1-317193791688.png)

het is niet de bedoeling dat het object fly-over of hoe je het ook wil noemen een vlak wordt want dat levert onze tool niet uit. Die levert akoestisch gezien een scherm uit waarbij de hellingshoek op 0 staat, geluidwerendemaatregel niet waar, vaste reflectiefactoren links/rechts en een hoogte van 1. De tool levert dus een schermdeel conform IMG1.2.

**Comment by wilkoquak** [comment]
Ik ga het voorstel aanpassen en zorgen dat het duidelijk lijn-objecten worden. Met de naamgeving zit ik nog een beetje. Het is wat mij betreft geen talud, en geen scherm. Ik neig naar een naam die dicht ligt bij wat je in de werkelijkheid beschrijft: de zijkant van een fly-over: FlyoverZijde.

**Comment by wilkoquak** [comment]
Wat betreft de hoogte: overal in IMGeluid representeert de geometrie de bovenkant van het object en wordt middels andere attributen (of in de definitie) vastgelegd waar de onderkant ligt.

**Comment by ThijsRuiterRWS** [comment]
@wilkoquak voor de geometrie zijn we uitgegaan van de definitie zoals deze in het IMG staat bij geluidschermdeel. hier staat "Als 3D-lijn gemodelleerde meetkundige representatie van de **voet** en de hoogte van de top van het afschermende object." Omdat in het geluidschermdeel ook het attribuut "schermhoogte" staat waarbij gemeten wordt als een loodrechte lijn ten opzichte van het maaiveld uitgedrukt in meters. Beschrijft het in mijn oogpunt duidelijk dat de XYZ als maaiveld gehanteerd wordt. Daarnaast is de "FlyoverZijde" ook een afgeleide van de hoogtelijn. Zodoende kijken we dus "omhoog". Als niet de voet/onderkant maar de top als basis wordt genomen moet onze tool aangepast worden en dat gaat niet lukken ivm de doorloop tijd.  

De naamgeving FlyoverZijde is prima.

**Comment by wilkoquak** [comment]
Bij het uitwerken van dit model blijkt het lastig te zijn deze als subklasse van Kunstwerk te modelleren (omdat Kunstwerk al een vlakgeometrie had die dan verschoven moet worden). Ook is de zijkant van een fly-over slechts een onderdeel van een Kunstwerk en is het logischer om FlyoverZijkant als subklasse van  Geluidoverdrachtobject te modelleren. In de uiteindelijke uitwisseling maakt het niets uit.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.
