### ISSUE TITLE
oplossing voor DoubleList op alle plekken doorvoeren

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#174]
# Aanleiding wijziging
In issue #72 is een oplossing voorgesteld voor het leveren van de onderkant van een geluidscherm zonder gebruik te maken van de DoubleList. Deze DoubleList blijkt lastig in de implementatie. Echter dezelfde DoubleList wordt ook op een flink aantal andere plaatsen in het model gebruikt. Er zijn nu twee redenen om de oplossing voor DoubleList op alle plekken door te voeren:
 - Orthogonaliteit: door de voorgestelde oplossing slechts op één plaats door te voeren zouden in het model twee verschillende oplossingen voor hetzelfde probleem gebruikt worden. Dit is een extra last voor ontwikkelaars die beide zullen moeten implementeren.
 - Als de DoubleList op 1 plaats problemen oplevert is de kans groot dat dat op andere plekken ook gaat gebeuren, we kunnen dit maar beter voor zijn.

# Voorgestelde wijziging
Er zijn (naast geluidScherm) vijf plekken waar een DoubleList gebruikt wordt om per coördinaat het hoogteverschil van het object met het maaiveld op te nemen. In al die gevallen willen we nu in plaats van het hoogteverschil per punt van de hoofgeometrie een extra geometrie opnemen die net zoveel punten heeft  als de hoofgeometrie en dezelfde xy-coördinaten, maar dan op maaiveldhoogte ligt. Het gaat hier om de volgende objecten:
- WegdeelGPP.wegdeelhoogte:DoubleList --> WegdeelGPP.maaiveldhoogte:GM_Curve. 
- SpoordeelGPP.spoordeelhoogte:DoubleList --> SpoordeelGPP.maaiveldhoogte:GM_Curve. 
- Bouwwerk.relatieveHoogte:DoubleList --> Bouwwerk.maaiveldhoogte:GM_Surface
- Procesinstallatiegebied.relatieveHoogte --> Procesinstallatiegebied.maaiveldhoogte:GM_Surface
- Vegetatiegebied.relatieveHoogte:DoubleList --> Vegetatiegebied.maaiveldhoogte:GM_Surface

# Impactanalyse
- Informatietechnisch verandert er niets: dezelfde informatie wordt doorgegeven.
- Het GML uitwisselformaat verandert op een niet backward compatible wijze: lees- en schrijfsoftware moet worden aangepast.

# Toelichting
Modeltechnisch gezien is het een verstandige keuze om deze wijziging door te voeren. Mogelijk redenen om het niet te doen liggen meer in de haalbaarheid om op tijd klaar te zijn met de implementatie.

**Comment by ThijsRuiterRWS** [comment]
@wilkoquak Zoals je al aangeeft is het model technisch een verstandige keuzen alleen is dit wijzigingsvoorstel **niet** uitvoerbaar in de beschikbare tijd voor het onderdeel WegdeelGPP. De wijzigingen betekenen namelijk dat de tool voor de hoogtelijnen, die afgeleid zijn van het WegdeelGPP, herschreven moeten worden en dus ook opnieuw getest moeten worden. De wijziging naar een multipart voor WegdeelGPP kan wel plaats vinden bij een reguliere update van het model richting IMG2.1. 

Op dit moment voeren wij het WegdeelGPP in als absolute waarde tov NAP in de Z coördinaat en is de double list dus helemaal niet nodig vandaar dat wij er ook geen problemen mee ervaren. Ik vraag mij dus af waarom er überhaupt een double list aanwezig is. Maar dat is voor dit vraagstuk niet relevant.

**Comment by wilkoquak** [comment]
Uiteindelijk is besloten dit voorstel niet door te voeren omdat de impact op partijen die de bestaande oplossing gebruik makend van de doubleList te groot was.
