### ISSUE TITLE
LijnbronIndustrie en VlakbronIndustrie onderdeel van  geluidgegevenscollectie (SDIMG-81, WELT-214)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#181]
# Aanleiding wijziging
De objecten “LijnbronIndustrie” en “VlakbronIndustrie” zijn niet in de geluidgegevenscollectie opgenomen, omdat deze geen specialisatie zijn van “GeluidgegevenscollectieElement”.
Melder vindt dat een fout omdat “VlakbronIndustrie” een eigenschap heeft welke essentieel is om berekende waarden te kunnen reproduceren, namelijk “negeerOverdrachtsobjecten”.
Je hebt in de berekening dan namelijk de geometrie van de vlakbron nodig om te kunnen achterhalen of een gebouw of scherm op deze vlakbron staat en je de bijbehorende reflectie en afscherming moet negeren.
Je kunt dus niet volstaan met alleen het inlezen van gegevens uit de GeluidgegevensCollectie en ik dacht dat dit de bedoeling was van de GeluidGegevensCollectie. 
Aangezien een geluidgegevenscollectie nu geen vlakbronnen meer kan bevatten, is het niet meer mogelijk om op basis van de collectie de berekende resultaten te reproduceren. 

# Oorspronkelijk voorgestelde wijziging
LijnbronIndustrie en VlakbronIndustrie subtypes van  geluidgegevenscollectieElement maken.
![image](https://user-images.githubusercontent.com/80040145/230294290-f9597289-c905-418a-91e8-865890901f85.png)

# Nieuwe voorstel 30-3
In de toelichtingen van objecten die volgens het model geen subtype van geluidgegevenscollectieElement zijn, duidelijk maken dat alle objecten in het GML bestand belangrijk zijn en dus ook degenen die niet rechtstreeks in de geluidgegevenscollectie zitten.

# Impactanalyse nieuwe voorstel 30-3
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? De gebruikers van het model
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? Nee
- Heeft het impact op het xml-schema? Nee

**Comment by wilkoquak** [comment]
De elementen van een Geluidgegevenscollectie zijn zo gekozen dat alle belangrijke objecten te vinden zijn via de collectie. Omdat LijnbronIndustrie en VlakbronIndustrie altijd aan een GeluidbronIndustrie hangen en GeluidbronIndustrie WEL in de Geluidgegevenscollectie zit zijn deze objecten dus wel altijd vindbaar vanuit de collectie.

Wellicht kunnen en bij Geluidgegevenscollectie een definitie opnemen waarin staat dat de relevante gegevens direct of indirect (via een relatie) onderdeel zijn van de collectie.

**Comment by TheoVerheij** [comment]
Ben het niet helemal eens met de redenatie van Wilko. Hij heeft wel gelijk dat je via de relaties de vlakbron wel kunt vinden.
Dit geldt namelijk ook voor WegdeelBGE welke je via de relaties van de basisgeluidemissies kunt vinden, maar toch zitten deze wel in de geluidgegevenscollectie.
Een vlakbron is nu eenmaal een heel belangrijk item omdat deze mede het berekende resultaat bepaald.

**Comment by PB-GNM** [comment]
20-12-22: Expert navragen om criteria aan te geven wanneer een object wel of geen geluidgegevenscollectieElement is.

**Comment by wilkoquak** [comment]
Het is nogal een rare situatie: je levert een GML bestand in en daarin zitten allerlei objecten. De meeste daarvan zin geluidgegevenscollectieElement maar een paar niet. Die objecten zijn wel altijd te vinden via een geluidgegevenscollectieElement. Maar het onderscheid is niet altijd duidelijk ik heb nog even gegraven in de documentatie en het gevraagd aan de  oorspronkelijke ontwikkelaars. Dat  leverde me het beeld op dat het inderdaad de bedoeling was dat belangrijke objecten een collectieElement werden en andere niet. Maar een eenduidige definitie van belangrijkheid is niet gegeven. Ondertussen kun je ook zeggen dat alle objecten belangrijk zijn, anders waren ze niet in het IMGeluid opgenomen.

Samenvattend: het onderscheid tussen opgenomen zijn in het GML bestand en deel uitmaken van geluidgegevenscollectie is nooit lekker uit de verf gekomen en volgens zou de standaard zonder kunnen.  Dit zou echter een niet backwards compatibele wijziging van de standaard zijn en het feit dat LijnbronIndustrie en Vlakbronindustrie geen onderdeel zijn van de geluidgegevenscollectie maakt de standaard niet minder bruikbaar.   Om die reden zou ik het willen laten zoals het is.

**Comment by wilkoquak** [comment]
Hallo @TheoVerheij, om het probleem op te lossen zonder de hele standaard overhoop te gooien wil ik graag duidelijk maken dat alle objecten in het GML bestand belangrijk zijn ook degenen die niet rechtstreeks in de geluidgegevenscollectie zitten. Ik ga dan de formulering zodanig aanpassen zodat duidelijk is dat ook de objecten die indirect verbonden zijn aan de collectie van belang zijn. Zou dat voldoende voor je zijn?

**Comment by TheoVerheij** [comment]
Hallo Wilko,

Is akkoord. Ik werk er wel omheen.

Met vriendelijke groet,

Th.J.B. (Theo) Verheij
Senior Adviseur Software en IT

**Comment by PB-GNM** [comment]
De volgende toelichting is bij de beide objecten toegevoegd om dit duidelijk te maken:
_De LijnbronIndustrie is geen onderdeel van de Geluidsgegevenscollectie, maar kan wel gevonden worden via de relatie met de GeluidsbronIndustrie die wel onderdeel is van de Geluidsgegevenscollectie._

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
