### ISSUE TITLE
Toevoegen objecttype DiffractorOpScherm (SDIMG-84, WELT-213)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#182]
# Aanleiding wijziging
Er is behoefte aan een nieuw objecttype voor geluidschermdelen met een diffractor voortkomend uit een wijziging in de reken- en meetvoorschriften. 

# Voorgestelde wijziging OUD
•	Nieuw abstract objecttype “ GeluidschermdeelAbstract ” met de velden welke een “ Geluidschermdeel ” nu heeft: bovenkantScherm, onderkantScherm, reflectiefactorLinks, reflectiefactorRechts, hellingshoek en statusZwevend. Dus zonder profietype en schermtype. 
Dit abstracte type is een specialisatie van “ Geluidoverdrachtobject ”.
Het schermtype is altijd diffractor op scherm en hoeft dus niet apart opgegeven te worden, lijkt mij.
•	Het bestaande objecttype “ Geluidschermdeel ” wordt nu een specialisatie van “ GeluidschermdeelAbstract ”, met als extra velden profietype en schermtype.
•	Het nieuwe objecttype “ DiffractorOpScherm ” is een specialisatie van “ GeluidschermdeelAbstract ”, met als extra veld diffractoreffect van het type “ WaardePerOctaafband ”.

# Impactanalyse OUD
Geef hier een indicatie van de impact van de wijziging:
- Wie gaat er wat van merken? Iedereen die iets met geluidschermen doet.
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? Ja 
- Heeft het impact op het xml-schema? Ja
- Wat gaat er mis als we de wijziging niet doorvoeren? Het IMG kan niet omgaan met diffractors op geluidschermen. 

# Toelichting
Dit heeft alleen invloed op wegen, maar wat is het effect op spoorwegen?

**Comment by PB-GNM** [comment]
20-12-22: Om het backwards compatible te maken stellen we voor om niet een abstract supertype te gebruiken, maar om er alleen een type DiffractorOpGeluidschermdeel bij te zetten.
![image](https://user-images.githubusercontent.com/80040145/209111384-3a161954-29b9-4763-be9b-387ae8d486af.png)

**Comment by PB-GNM** [comment]
# Aanleiding wijziging
Er is behoefte aan een nieuw objecttype voor geluidschermdelen met een diffractor voortkomend uit een wijziging in de reken- en meetvoorschriften.

# Voorgestelde wijziging

- Nieuw objecttype “DiffractorOpGeluidschermdeel” met dezelfde velden welke een “ Geluidschermdeel ” nu heeft: bovenkantScherm, onderkantScherm, reflectiefactorLinks, reflectiefactorRechts, hellingshoek en statusZwevend, maar zonder profietype en schermtype. Het schermtype is altijd diffractor op scherm en hoeft dus niet apart opgegeven te worden.
- Het nieuwe objecttype heeft daarnaast als extra veld "diffractoreffect" van het type “ WaardePerOctaafband ”.
- Dit objecttype is een specialisatie van “Geluidoverdrachtobject ”.
![image](https://user-images.githubusercontent.com/80040145/209111384-3a161954-29b9-4763-be9b-387ae8d486af.png)

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
- Wat betekent het voor de software van de CVGG, softwareleveranciers en bronhouders? Alle software dient hierop aangepast te worden. Ook de validatieregels in de CVGG moeten bijgewerkt worden.
- Wie gaat er wat van merken? Diegene die een diffractor op een geluidscherm wil aanleveren of gebruiken.
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? Ja 
- Heeft het impact op het xml-schema? Ja
- Wat gaat er mis als we de wijziging niet doorvoeren? Het IMG ondersteunt dan niet het reken- en meetvoorschrift en daardoor kunnen bronhouders dan geen diffractors op geluidschermen aanleveren aan de CVGG, conform IMG. 
- X,Y,Z-wijziging: **Y**, want er wordt alleen iets toegevoegd.

# Toelichting
Dit heeft alleen invloed op wegen, maar wat is het effect op spoorwegen?

**Comment by wilkoquak** [comment]
Notities tijden Adviesgroep 16-5:
- Dit speelt sowieso bij Wegen en Spoorwegen.
- Geen bezwaar tegen Y-wijziging.
- Bij Prorail zijn alle diffractors hoge diffractors en dus eigenlijk diffractors op geluidsherm. Hoe dit precies zit wordt nog nagevraagd. (Hier nog een voorbehoud)
- Voorstel om het GeluidschermMetDiffractor te noemen.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0 (zowel in het GPPSpoor-diagram als bij GPPWeg).

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
