### ISSUE TITLE
Doublelists uit het model (SDIMG-86, WELT-229)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#183]
# Aanleiding wijziging
Gebruik van doublelists wordt gezien als inconsistentie in het model nu het voor het geluidscherm is vervangen door een 2e geometrie (bovenkantscherm). 

# Voorgestelde wijziging
Voor andere objecten die nog wel een doublelist gebruiken moet een vergelijkbare oplossing gekozen worden als voor geluidscherm. Zie https://github.com/Geonovum/IMG/issues/72 en in het bijzonder https://github.com/Geonovum/IMG/issues/72#issuecomment-1054138731. Het betreft nu de volgende objecten:
- WegdeelGPP, 
- SpoordeelGPP, 
- Bouwwerk, 
- Vegetatiegebied,
- Procesinstallatiegebied.

**Voor Geluidscherm is het volgende veranderd van de versie voor 2.0:**
![image](https://user-images.githubusercontent.com/80040145/230082905-0db9aa54-9321-47b9-a8bf-0c469f3609e8.png)
**Naar versie 2.1:**
![image](https://user-images.githubusercontent.com/80040145/229833572-fb4a3f8b-cbc2-493e-bf1d-10db29c6729d.png)

**Let op:** Door deze wijziging zijn er ook nieuwe regels toegevoegd: Zie de rood aangegeven regels onderaan in deze tabel: [RegelsVanVersie2.1Naar3.0_20230717.xlsx](https://github.com/Geonovum/IMG/files/12068403/RegelsVanVersie2.1Naar3.0_20230717.xlsx)
Het betreft de regels voor het 4x toegevoegde nieuwe attribuut maaiveld waarvoor geld:
_Als maaiveld gevuld is moet deze evenveel punten bevatten als de geometrie met dezelfde x- en y-coördinaten in dezelfde volgorde._
Daarnaast is voor het attribuut geometrie van de volgende objecten gesteld dat alle z-coördinaten hetzelfde moeten zijn:
- Brug
- Vegetatiegebied
- Procesinstallatiegebied
- VlakbronIndustrie

# Impactanalyse
Deze wijziging heeft impact op partijen die bovengenoemde objecten aanleveren en op software die met deze objecten werkt.
Deze wijziging heeft geen impact op de semantiek van het model.
De wijziging resulteert in een niet backwards-compatible wijziging in het xml-schema als de attributen waar de doublelists in stonden ook echt verwijderd worden uit het model. Eerder aangemaakte aanleverbestanden volgen versie 2.1 van IMG waar deze doublelist in voorkwamen, komen dan niet door een validatie op basis van het nieuwe xml-schema.
Het betreft een X-wijziging omdat reeds aangemaakte data als input voor de CVGG aangepast zal moeten worden.

**Let op:** Omdat door deze wijziging ook regels zijn toegevoegd of aangepast (zie hierboven), heeft dat impact op software die hierop valideert.

**Comment by PB-GNM** [comment]
20-12-22: er is relatie met #174 waarin besloten is het voorlopig niet te doen vanwege impact. We gaan het toch nog een keer bespreken in de expertgroep.

**Comment by PB-GNM** [comment]
Bij alle 5 de objecten zal ook de volgende regel toegevoegd moeten worden:
_Als de geometrie van de onderkant gevuld is heeft die geometrie evenveel punten als de geometrie van de bovenkant met dezelfde x- en y-coördinaten in dezelfde volgorde._
Hier is een relatie met #192.

**Comment by wilkoquak** [comment]
In adviesgroep 16-5 besproken:
- Hier speelt een discussie bij WegdeelGPP. De vraag of het kenmerk daar wel nodig is. Na discussie is consensus dat het kenmerk mogelijk in de toekomst nut heeft en dat het niet geschrapt kan worden.
- Akkoord over x-wijziging.
- Onduidelijkheid of het voor 1 januari te doen is. Maar RWS en Prorail hebben nog even ruggespraak nodig.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0 onder voorbehoud van instemming RWS en Prorail.

**Comment by TheoVerheij** [comment]
Toch nog een vraag over de (eventuele) implementatie.
De velden "wegdeelhoogte", "spoordeelHoogte" en "relatieveHoogte" bevatten nu de relatieve hoogte, d.w.z. het hoogteverschil tussen de top en de bodem/onderkant.
In alle geometrieen (GM_Curve en GM_Surface) is de Z-waarde de absolute hoogte (t.o.v. NAP). Gaat deze logica consequent gebruikt worden? Dus wordt de relatieve hoogte vervangen door de hoogte van de onderkant?

**Comment by PB-GNM** [comment]
Het is nu zo aangepast dat de nieuwe 2e optionele geometrieën een z-waarde op maaiveldhoogte hebben.

**Comment by wilkoquak** [comment]
In het IPO overleg is een besluit genomen over de wegdeelhoogte: Wegdeelhoogte mag uit het model.

**Comment by wilkoquak** [comment]
Als 



> Toch nog een vraag over de (eventuele) implementatie.
> De velden "wegdeelhoogte", "spoordeelHoogte" en "relatieveHoogte" bevatten nu de relatieve hoogte, d.w.z. het hoogteverschil tussen de top en de bodem/onderkant.
> In alle geometrieen (GM_Curve en GM_Surface) is de Z-waarde de absolute hoogte (t.o.v. NAP). Gaat deze logica consequent gebruikt worden? Dus wordt de relatieve hoogte vervangen door de hoogte van de onderkant?

Als antwoord op de vraag van Theo: het lijkt me wel veel logischer om de absolute hoogte van het maaiveld te gebruiken. Vooral voor gebouwen is het wel erg raar als je de hoogte van het maaiveld t.o.v. een akoestisch berekende hoogte berekent. Ik ga definities aanpassen.

**Comment by wilkoquak** [comment]
Ook ga ik het datatype van de onderkant matchen met dat van de bovenkant:
- Bouwwerk.onderkantBouwwerk wordt een GM_Surface.
- Vegetatiegebied.onderkantVegetatiegebied wordt een GM_Surface.
- Procesinstallatiegebied.onderkantProcesinstallatiegebied wordt een GM_Surface.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
