### ISSUE TITLE
geluidbronsoort heeft "/" voor attribuutnaam van Geluidaandachtsgebied

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#184]
## Waar zit de fout?

Geluidaandachtsgebied

## Wat is de fout?

geluidbronsoort heeft "/" voor attribuutnaam

## Wat moet het worden? [optioneel]

"/" moet weg

**Comment by PB-GNM** [comment]
20-12-2022: we halen streepje weg

**Comment by wilkoquak** [comment]
Het /-teken geeft aan dat het een afgeleid attribuut is en (in principe) berekend kan worden uit de andere attributen. Het heeft dus wel enige betekenis, maar inmiddels zijn we er ook achter dat die afleiding niet altijd kan. Daarom is weghalen van het /-teken inderdaad een goede optie,

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
