### ISSUE TITLE
Tussen 1.2 en 2.0 is de precisie op etmaalintensiteit weggevallen in VerkeersgegevensWeg

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#187]
## Waar zit de fout?

Zie [versie 1.2](https://docs.geostandaarden.nl/cvgg/def-im-img-20211115/#detail_attribute_IMGeluidAlgemeen_VerkeersgegevensWeg_voertuigAantal)
Zie [versie huidig](https://docs.geostandaarden.nl/cvgg/img/#detail_attribute_IMGeluidAlgemeen_VerkeersgegevensWeg_aantalVerkeersgegevensWegDagLicht)

## Wat is de fout?

In de huidige versie mist het patroon met 'Toegestane waarde: van 0,0 tot en met 99999,99'

Dit patroon had er wel bijgeomoeten.

## Wat moet het worden? 

Aan alle attributen van VerkeersgegevensWeg dit patroon toevoegen.

**Comment by PB-GNM** [comment]
In versie 1.2 stond wel in de tagged vallues 0 als mininimum en 100000 als maximum waarde.
Dat leidt in het xml-schema tot het volgende:

> <xs:restriction base="xs:decimal">
> <xs:minInclusive value="0"/>
> <xs:maxInclusive value="100000"/>
> <xs:fractionDigits value="2"/>
> </xs:restriction>

Moeten die waarden dan ook niet aangepast worden? naar 0,00 en 99999,99

**Comment by wilkoquak** [comment]
Het zou eigenlijk maxExclusive 100000 moeten zijn ipv maxInclusive. Ik ga daar nog even naar kijken.

**Comment by wilkoquak** [comment]
Ik zie dat er in versie 1.2 van de standaard een verschil is tussen het XSD en wat er in de tekst staat. Welke van de twee nu leidend is is niet helemaal formeel vastgelegd. Echt heel veel uitmaken doet het ook niet omdat die maximumwaarde zo hoog gekozen is dat de waarde in praktijk nooit ingevuld zal worden. Voor de veiligheid kies ik het ruimste maximum (100000)  en zorg ervoor dat het in versie 3.0 van de standaard in het XSD en tekst beide gelijk is.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
