### ISSUE TITLE
spoorgegevensblokken intensiteit en snelheid samenvoegen (SDIMG-107)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#188]
# Aanleiding wijziging
Het aanleveren van twee gegevensgroepen voor intensiteit en snelheid bij SpoordeelGPP en SpoordeelBGE was toegespitst op aanleveringen van Prorail, maar niet handig voor andere leveranciers. Niet alle gegevens zijn relevant en er zit overlap in voor wat betreft snelheid. 

# Voorgestelde wijziging
Het samenvoegen van de 2 gegevensgroepen IntensiteitgegevensSpoor en SnelheidgegegevensSpoor tot 1 groep IntensiteitgegevensSpoor met de volgende attributen:

<<img:intensiteit>>
&ensp;   <<img:intensiteit>>0</img:intensiteit>
&ensp;   <<img:profieltypeSnelheid>>doorgaand</img:profieltypeSnelheid>
&ensp;   <<img:spoorvoertuigcategorie>>2</img:spoorvoertuigcategorie>
&ensp;   <<img:dagdeel>>nacht</img:dagdeel>
&ensp;   <<img:snelheid>>67</img:snelheid>
&ensp;    <<img:remindicatie>>false</img:remindicatie>
&ensp;    _<<img:treintype>>reizigers</img:treintype>
&ensp;    <<img:rijrichting>>oplopend</img:rijrichting>
&ensp;    <<img:materieelnaam>>MAT64</img:materieelnaam>_
</img:intensiteit>

De laatste 3 zijn optioneel en krijgen dus kardinaliteit {0..1}.

# Impactanalyse

- Wie gaat er wat van merken? **Data providers, software leveranciers, de API, gebruikers**
- Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Niet echt, behalve dat de gegevensgroep intensiteit meer omvattend wordt.**
- Heeft het impact op het xml-schema? **Ja**
- Is het backward compatible in de zin van validatie op het schema? **Nee, want er verdwijnt een gegevensgroep.**
- Heeft het impact op de validatieregels in IMG? **Nee**
- Heeft het impact op de omgevingsregeling? **Ja**
- X,Y,Z-wijziging: **X, want er verdwijnt een gegevensgroep**

# Toelichting

**Comment by skornsekj** [comment]
@PB-GNM in de impact analyse staat 'Heeft het impact op de validatieregels in IMG? Nee'.  Bedoel je hier de 'regels' in IMGeluid of de extra validatieregels die de CVGG moet implementeren, bovenop de de xsd validatie?

**Comment by PB-GNM** [comment]
> @PB-GNM in de impact analyse staat 'Heeft het impact op de validatieregels in IMG? Nee'. Bedoel je hier de 'regels' in IMGeluid of de extra validatieregels die de CVGG moet implementeren, bovenop de de xsd validatie?

Ik bedoel hier de (op dit moment 57) regels zoals die in het IMGeluid staan, maar die staan ook bovenop de xsd validatie.

**Comment by wilkoquak** [comment]
Commentaar van adviesgroep 16-5:
- Prorail is in principe akkoord maar er is nog discussie over 1 treintype (mat64) die dan anders uitgeleverd zou moeten worden. Er wordt intern aan gewerkt om dit op te lossen. Hierover komt binnenkort meer duidelijkheid.
- Op zich een goed voorstel maar er is niet voor iedereen duidelijkheid of dit voor 1 januari is te implementeren. Als dat niet kan is dat heel vervelend dus dat moet eerst uitgezocht.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0. onder voorbehoud van instemming Prorail.

**Comment by PB-GNM** [comment]
Prorail heeft instemming verleend.
Opgelost in versie 3.0.0.
