### ISSUE TITLE
OBJECT::Geospoortak.booggeluid - Booggeluid: afleiden uit geometrie?

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#19]
# Samenvatting
Een **boog** in een spoortak geeft 5dB geluidtoeslag. Daarvoor moet je weten of een geospoortak een boog is of niet.

**Vraag**
Moeten het informatiemodel hiervoor een attribuut opnemen, of is het mogelijk dit uit de geometrie af te leiden?

# Voorgestelde oplossing
 - Booggeluid is niet uit de geometrie af te leiden bij homogene baanvakken;
 - Voor de berekening van de GPP's wordt het _linear referenced_ model van ProRail opgeknipt in homogene baanvakken.
 - Attribuut opnemen, bijv.: **_indicatieBoog_**?
 - Met name voor lokaal spoor is Booggeluid een cruciaal gegeven. Het verzoek is om dit op te nemen. Omdat je dit mee wilt kunnen nemen in de berekening van je BGE, loopt dit verzoek via het AREG.

**Comment by joerivanes** [comment]
Verholpen door herziening van model
