### ISSUE TITLE
Verwijzing naar Terrein in een aanlevering van een Monitoringresultaat (SDIMG-104)

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#191]
# Aanleiding wijziging
Bij het aanleveren van een Monitorresultaat van een geluidbron industrieterrein moet in de huidige standaard een object van het type Industrieterrein worden meegeleverd. Dit was niet de bedoeling. Het was de bedoeling dat in de aanlevering van het Monitorrresultaat een xlink zou zitten naar het Industrieterrein zoals aangeleverd in de vaststelling. Dit wijzigingsverzoek beschrijft een wijzing die het Terrein in plaats van het Industrieterrein zelf een link ernaar kan worden opgenomen,

# Voorgestelde wijziging

In plaats van dat een Geluidgegevenscollectie het terrein opneemt als GeluidgegevenscollectieElement krijgt de klasse Geluidgegevenscollectie een optionele relatie naar een Terrein. In alle geval dat een collectie over een terrein gaat moet deze relatie gebruikt worden. Als het gaat om een Monitoringresultaat over een Terrein dan moet een link naar het eerder aangelverde terrein worden opgenomen. In andere gevallen het terrein zelf.

![afbeelding](https://user-images.githubusercontent.com/2814052/230328798-99b164b6-13b0-474f-b4f3-ea8f9accb560.png)

# Impactanalyse

- Deze wijziging heeft impact op iedereen die iets met Terreinen doet omdat de plaats van Terrein in het model verandert.
- Ook het XML-schema verandert dus data providers en softwareleveranciers zullen hun software moeten aanpassen.
- De verandering leidt niet tot nieuw in te winnen gegevens.
- De wijziging heeft vooral impact op de aanlevering van monitoringresultaten die met het huidige schema nog niet mogelijk zit. Er hoeft dus iet opnieuw aangeleverd te worden.
- Als je een monitoringresultaat gaat indienen zullen die er anders uitzien dus is het een x-wijziging.

**Comment by wilkoquak** [comment]
In de Expertgroepmeeting werd voorgesteld om Terrein dan ook andere gevallen niet meer op te nemen in de Geluidgegevenscollectie en het element buiten de Geluidgegevenscollectie te houden. Dat ga ik in het voorstel verwerken.

**Comment by TheoVerheij** [comment]
Volgens mij heb je bij het aanleveren van monitoringsresultaten 2 opties: alleen de monitoringsgegevens (=geluidproductieplafondobjecten) of deze inclusief de overige brongegevens.

In het 1e geval leverde Geomilieu het betreffende terrein toch al niet mee, waardoor deze NIET in de geluidgegevenscollectie stond, maar wel een verwijzing vanuit het geluidproductieplafondobject.
Worden ook alle brongegevens uitgevoerd, dan wordt ook het terrein uitgevoerd en dan staat deze referentie ook in de collectie.

Waar ik nu mee zit, is het volgende: op dit moment leest Geomilieu alleen de gegevens in welke in een geluidgegevenscollectie staan. Nu wordt het dus noodzakelijk om ook objecten te zoeken buiten deze collectie waarnaar verwezen wordt vanuit de collectie. Dat is extra complexiteit en vergroot de kans op fouten. Deze complexiteit speelt helaas ook al bij vlakbronnen, lijnbronnen en optrektoeslagen.

**Comment by PB-GNM** [comment]
In adviesgroep 16-5 besproken: Er waren geen bezwaren.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
