### ISSUE TITLE
Aanpassen regels n.a.v. kwaliteitstoets

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#192]
# Aanleiding wijziging
In het informatiemodel IMG versie 2.1.0 staan 57 regels opgeschreven. 
Het is gewenst dat deze regels allemaal logisch, leesbaar en eenduidig zijn. Het blijkt echter dat deze regels dat nog lang niet allemaal zijn. Zeker wanneer de richtlijn van [Rulespeak](https://www.rulespeak.com/en/) hierover gevolgd wordt.
De regels zijn geïnventariseerd. Waar ze eenduidig waren maar nog niet conform Rulespeak, zijn verbeterde regels voorgesteld.
Waar ze niet eenduidig waren is aan RIVM gevraagd de regels zodanig aan te passen dat ze wel eenduidig zijn.
Sommige regels bleken geen regel, overbodig of eerder een toelichting te zijn.

# Voorgestelde wijziging
Alle regels waar nodig aanpassen zodanig dat ze logisch, leesbaar en eenduidig worden.

# Impactanalyse
-Wie gaat er wat van merken? **Gebruikers van het model krijgen regels aangeboden die logischer, leesbaarder en eenduidiger zijn. Aangenomen wordt dat de software die de regels nu toepast voor het inlezen van de data niet aangepast hoeft te worden, tenzij deze software de verkeerde betekenis heeft geïnterpreteerd bij niet eenduidige regels, maar daar wordt nog niet van uitgegaan.**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
-Is er een herlevering nodig naar de CVGG? **Nee**
-Heeft het impact op het xml-schema? **Nee**
-Is het backward compatible in de zin van validatie op het schema? **Ja**
-Heeft het impact op de validatieregels in IMG? **Ja**
-Heeft het impact op de omgevingsregeling? **Nee**
-Is het een X, Y, of Z wijziging? **Z**, maar wel veel werk

-**Let op!**: Buiten dit issue om, vanuit andere issues, zijn er nieuwe regels toegevoegd in versie 3.0. Er zijn ook regels verwijderd. Dat kan dus wel impact hebben op software.  Deze regels zijn in het rood te vinden in de tabel die te downloaden is via: https://github.com/Geonovum/IMG/issues/192#issuecomment-1563012892.

# Toelichting
Op dit moment wordt er nog gewerkt aan het bijwerken van de regels in een xls lijst met daarin de oude regel, de toetsing en de nieuwe regel. Als die bijgesteld is zal deze hier geüpload worden.

**Comment by skornsekj** [comment]
@PB-GNM kun je de lijst svp uploaden, zodat hiernaar gekeken kan worden. Vast bedankt!

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0 op basis van bijgevoegde xlsx-bestand.  

**Let op:** Er zijn niet alleen regels tekstueel aangepast maar ook regels toegevoegd en verwijderd. In het rood is in deze tabel aangegeven als een regel toegevoegd is of als een regel is verwijderd.
[RegelsVanVersie2.1Naar3.0_20230717.xlsx](https://github.com/Geonovum/IMG/files/12068403/RegelsVanVersie2.1Naar3.0_20230717.xlsx)

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
