### ISSUE TITLE
Monitoringresultaat hoort altijd bij Geluidproductieplafond of Basisgeluidemissie (SDIMG-111, Welt-259)

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#193]
# Aanleiding wijziging
Monitoringresultaat objecten moeten altijd naar 1 Geluidproductieplafond of naar 1 Basisgeluidemissie object verwijzen. Dit staat momenteel niet duidelijk in de standaard. 

# Voorgestelde wijziging
De standaard aanpassen zodat een Monitoringresultaat altijd de juiste verwijzing heeft door een nieuwe subklasse GemonitordObject toe te voegen. Het UML ziet er dan als volgt uit: 
![afbeelding](https://user-images.githubusercontent.com/2814052/231695841-5886df6d-8ee3-4af1-9b90-758fa56e0e64.png)

# Impactanalyse

- Inhoudelijk verandert de standaard niet: dezefde gegevens moeten worden aangeleverd.
- In de uitwisseling zullen de twee optionele verwijzingen die nu in Monitoringresultaat zitten (te weten: geluidproductieplafondobject en basisgeluidemissieobject) anders gaan heten (namelijk: gemonitordObject). Hiervoor moet de lees- en schrijffunctionaliteit voor het object Monitoringresultaat in software aangepast worden. Daarom is het een X wijziging.

# Alternatieven die we hebben overwogen waren

1. Bij het object Monitoringresultaat een regel toevoegen: 'Van de relaties basisgeluidemissieobject en geluidproductieplafondobject heeft er altijd precies 1 een waarde.'. Dit alternatief heeft als nadeel dat deze niet door een xsd kan worden afgedwongen en je hier dus pas een foutmelding op krijgt op het moment dat je gegevens aanbiedt aan de CVGG.
2. Een «keuze» object toevoegen aan het model waardoor het XML schema altijd afdwingt dat er 1 van de twee wordt ingevuld. In het UML ziet het er dan als volgt uit:
![afbeelding](https://user-images.githubusercontent.com/2814052/229795305-795ea026-b8bd-449e-a541-9baa8f3d3f5f.png). Technisch is dit alternatief bijna equivalent aan het voorgestelde alternatief alleen ziet de xml encoding er net iets exotischer uit.

**Comment by GosseBakker** [comment]
Een andere oplossing is wellicht deze:
- We maken een generalisatie (bijv. 'Referentieobject') van de twee specialisaties Basisgeluidemissieobject en GeluidproductieplafondObject.
- In Monitoringresultaat vervangen we de twee optionele releaties met Basisgeluidemissieobject en GeluidproductieplafondObject door een verplichte relatie met één zo'n ReferentieObject.

Voordeel van deze aanpak is, dat de xml er hetzelfde uitziet al nu.
![1680699095511](https://user-images.githubusercontent.com/5858242/230107083-761b1aa1-6d85-4fd2-b0c6-7241af3fcbca.JPEG)

**Comment by wilkoquak** [comment]
Allen, die mogelijk is er inderdaad ook nog. Eerder vond in het gebruik van de «keuze» mooier omdat ik daarbij een backwards compatibele xml-constructie had verwacht. Maar nu dat niet zo blijkt te zien is deze optie weer mogelijk.  Een tussenklasse toevoegen kan er soms voor zorgen dat de attributen van volgorde veranderen maar dat is in dit geval niet zo. Ik zal deze optie toevoegen als derde keuze. Dank!

**Comment by wilkoquak** [comment]
Ik heb het wijzigverzoek nu zodanig aangepast dat er een voorstel wordt gedaan voor 1 van de alternatieven.

**Comment by skornsekj** [comment]
@wilkoquak  zou je optie 3 nog willen toevoegen. Ik begreep dat die optie ervoor zorgt dat de gml ansich niet wijzigt.

**Comment by PB-GNM** [comment]
In adviesgroep 16-5 besproken: Er waren geen bezwaren.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.0.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
