### ISSUE TITLE
aantalVerkeersgegevensWegDagMiddelzwaar mist fractiondigits

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#194]
## Waar zit de fout?

In het IMGeluid-3.0.0-rc1.xsd

## Wat is de fout?

fractionDigits ontbreekt.

## Wat moet het worden? [optioneel]

<xs:fractionDigits value="2"/>

**Comment by wilkoquak** [comment]
Taggte value Lengte van 0.2 --> 0,2 ter oplossing van issue https://github.com/Geonovum/IMG/issues/194 . Hierdoor werd de fractiondigits niet toegevoegd in aantalVerkeersgegevensWegDagMiddelzwaar . Bleek ook zo te zijn in aantalVerkeersgegevensWegAvondLicht. Ook de minimumwaarde voor snelheidVerkeersgegevensWag bleek vaak te missen. Deze heb ik ook opgelost in de werkversie.

**Comment by PB-GNM** [comment]
Expertgroep 14-9 ondersteunt het aanpassen van deze bug.

**Comment by wilkoquak** [comment]
Nog een paar:
- SpoordeelGPPType.plafondcorrectie.maxInclusive = 9.9
-  VerkeersgegevensWeg.snelheidVerkeersgegevensWegDagLicht.mininclusive = 0
-  VerkeersgegevensWeg.snelheidVerkeersgegevensWegDagMiddelzwaar.mininclusive = 0
-  GeluidbronIndustrie.reflectiepuntHoogte.MogelijkGeenWaarde = nee
Deze 4 heb ik ook aangepast.

**Comment by PB-GNM** [comment]
Tijdens het adviesgroep overleg van 3-10 is afgesproken dat de plafondcorrectie min -199,9 en maximaal 199,9 zowel voor WegdeelGPP, als voor SpoordeelGPP. Voor de vier bullits hierboven worden 4 aparte wijzigingsverzoeken gemaakt.

**Comment by wilkoquak** [comment]
Duplicate of  #207. Duplicate of #209. Duplicate of #210.  Dit issue is vervangen door de hiervoor genoemde issues en kan daarom gesloten worden.
