### ISSUE TITLE
Verdwenen tekst over richtlijnen construeren NEN3610ID

### ISSUE THREAD

**Issue by wilkoquak** [Geonovum/IMG#195]
## Omschrijving

In  eerder versies van de standaard (https://docs.geostandaarden.nl/cvgg/def-im-img-20201029/#identificatie-binnen-het-informatiemodel ) stond in paragraaf 3.3.2.3 uitleg over het invullen van het NEN3610ID. Deze is (onbedoeld) verdwenen uit de standaard. Dat had niet gemoeten en de tekst moet teruggeplaatst.

## Wat moet het worden? 

Het gaat om de volgende tekst:

<ul>
<li>De namespace is altijd “NL.img”;</li>
<li>De lokaalID is opgebouwd uit:
<ul>
<li>Een unieke code van de bronhouder;</li>
<li>Een punt (“.”);</li>
<li>Een lokale identificatie zoals gebruikt door de bronhouder;</li>
</ul></li>
<li>Het versienummer</li>
</ul>

**Comment by wilkoquak** [comment]
Commit 5913fb9 lost dit issue op.

**Comment by PB-GNM** [comment]
Opgelost in versie 3.0.0.
