### ISSUE TITLE
Enumeratie: Dagdeel

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#2]
De datatypen **Intensiteiten** en **Snelheden** maken beiden gebruik van de enumeratie **Dagdeel**. 

1. Welke **definitie** hanteren we hier voor waarden uit de enumeratie **Dagdeel**?
2. Uit welke **bron** is de definitie afkomstig?
3. Optioneel ter verduidelijking een **omschrijving** toevoegen

**Comment by joerivanes** [comment]
Oud
