### ISSUE TITLE
OBJECT::Spoorwegemplacementen - objecten, attributen en datatypen

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#20]
# Samenvatting
De centrale voorziening zal ook informatie opnemen over de geluidproductie op spoorwegemplacementen. Deze geluidproductie wordt vervolgens (gewogen) _energetisch_ opgeteld bij de geluidproductie op het naastgelegen doorgaande geospoortak van het hoofdspoor. De optelling bepaalt het geluidproductieplafond.

**_L<sub>Overstand</sub>_ en _L<sub>Doorgaand</sub>_**
De geluidproductie op spoorwegemplacementen wordt op twee manieren berekend. De rijdende  treinen vallen onder het Reken- en Meetvoorschrift (GPP) spoor (_L<sub>Doorgaand</sub>_). Dit valt samen met het informatiemodel GPP Spoor. De geluidproductie van stilstaande treinen (_L<sub>Overstand</sub>_) wordt berekend volgens het HRMI (Reken- en Meetvoorschrift Industrielawaai) als puntbronnen. Voor de L<sub>_Overstand_</sub> kan per emplacement door verschillende bureaus worden uitgevoerd. En het optellen en berekenen van het GPP gebeurt in Soundbase (ProRail).

**Vragen**
- Welke informatie moet over spoorwegemplacementen worden vastgelegd?
- Kunnen daarbij onderdelen uit GPP-industrie en GPP-spoor hergebruikt worden?

# Voorgestelde oplossing
Als akoestisch modelleur wil je onderscheid kunnen maken tussen _L<sub>Doorgaand</sub>_ en _L<sub>Overstand</sub>_. Dit geeft namelijk in één oogopslag de duidelijkheid over de totstandkoming van de uitkomsten. Met ProRail zal overlegd moeten worden of zij beide waarden apart kunnen leveren. Vanuit de klankbordgroep is het advies om te waarborgen dat het puntbronnengedeelte echt aansluit op industrie

**Modellering**
Voor _L<sub>Doorgaand</sub>_ is het informatiemodel GPP Spoor dekkend
Voor _L<sub>Overstand</sub>_ moet uitgezocht worden of de manier waarop puntbronnen in het informatiemodel GPP Industrie hiervoor toereikend zijn

### Benodigde informatie
**1 Proceslocaties** (uit model GPP-industrie)
 - Bedrijfsduurcorrectie
 - Geometrie (puntbronnen)
 - Relevante uitstralingsrichting
 - Relevante Bronsterkte

**2 Rijdende treinen op rangeerterreinen**
 - Geometrie: lijnen, de treinen rijden tussen die punten),
 - Modelleren zoals als rijdende trein in GPP-spoor
 - Snelheid (rangeerbeweging van 40 km/u)
 - Intensitetiten
 - Type trein
 - Bovenbouw

**3 Snelheidsprofielen**
De vier bestaande snelheidsprofielen, worden uitgebreid met een nieuw profiel:
 - Doorgaand
 - Stoppend
 - Rangerend (_nieuw_)

**4 Projectie snelheidsprofielen L<sub>_Overstand_</sub> op GPP's hoofdspoor**
De activiteiten op de emplacementen moet je 'overzetten' naar het hoofdspoor. De uitkomsten uit model L<sub>_Overstand_</sub> op referentipunten van het hoofdspoor in GPP model opnemen. Het kan daarom voorkomen dat de doorgaande treinen op het hoofdspoor de bovenstaande profielen al bezetten, terwijl je de overstand nog bij die lijn op tellen. Daarom zijn twee nieuwe snelheidsprofielen toegevoegd.

**Overige activiteiten**
De overige activiteiten, zoals: wassen, reparatie, etc., komen niet in het register terecht.

**Aanvullingen**
 - Puntbronnen kunnen in het model optioneel directioneel gemaakt worden.
 - Standgeluid is altijd stilstaand en valt onder de rekenmethode industrie
 - Doorgaand valt onder de rekenmethode railverkeer

**Vragen**
 - Komen er gebouwen voor: waarschijnlijk niet (Arnaud gaat na bij ProRail)
 - Mogelijk als een afschermende voorziening, maar niet als het er zo maar staat
 - Puntbronnen als onderdeel van lijn- of vlakbronnen spelen bij spoor geen rol
 
**Object Berekening**
 - Er zijn wel twee verschillende rekenharten (dus ook twee verschillende softwarepakketten/versies)
 - Er zijn twee oplossingsrichtingen: of meerdere berekeningen toestaan voor GPP-spoor of meerdere waarden toestaan bij de attributen softwarepakkert en softwarepakketversie
 - Hiervoor moeten we bij ProRail navragen hoe ze de berekening en samenvoeging organisatorisch vormgeven
 - Blijven organisatie en berekenignsdatum hetzelfde, of kunnen ook die verschillen?
 - Het laatste geval zou pleiten voor kardinaliteit aanpassen op objectniveau (dus in relatie met GPP)
 - Regel toevoegen: voor dat er 1..1 rekenpakket is voor rijdende bronnen en 1..1 rekenpakker voor stilstaande bronnen

**Comment by joerivanes** [comment]
Verholpen door herziening van model
