### ISSUE TITLE
Regel bij Brug.geometrie verwijderen (SDIMG-120, WELT-269)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#200]
# Aanleiding wijziging
Het gaat om de regel: _Alle z-coördinaten in Brug.geometrie moeten dezelfde waarde hebben._
Deze regel had niet in IMGeluid 3.0 moeten staan, want er zijn ook bruggen die een helling hebben.

# Voorgestelde wijziging
Het voorstel is om de regel te verwijderen.  

![image](https://github.com/Geonovum/IMG/assets/80040145/d9ac62be-fc6a-465a-b742-59524ceb8169)

![image](https://github.com/Geonovum/IMG/assets/80040145/d5a9aff0-ea5a-4f2a-9c7a-a11927bebe14)

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
-Wie gaat er wat van merken? **softwareleveranciers**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
-Is er een herlevering nodig naar de CVGG? **Nee**
-Heeft het impact op het xml-schema? **Nee**
-Is het backward compatible in de zin van validatie op het schema? **Ja**
-Heeft het impact op de regels in IMG? **Ja**
-Heeft het impact op de validatieregels voor de CVGG? **Ja**
-Heeft het impact op de omgevingsregeling? **Nee**
-Is het een X, Y, of Z wijziging? **Z**

# Toelichting
Een alternatief is om de regel aan te passen tot: _"Alle z-coördinaten in Brug.geometrie moeten in hetzelfde vlak liggen. Dit mag een hellend vlak zijn."_ 
In dat geval is de impact groter, omdat het een extra validatie betekent in het geval het vlak wordt opgespannen door meer dan  3 punten. Elk extra punt moet dan liggen in het vlak dat wordt opgespannen door de eerste 3.

**Comment by wilkoquak** [comment]
Ik heb nog even zitten zoeken in de  GML simple feature standaard en daarin staat: 'Spatial properties are limited to being of type: point, curve with linear and/or circular arc interpolation, planar surface, or aggregates thereof'. Van de GML standaard moeten de punten van een Surface dus altijd in een vlak liggen, maar het hoeft geen horizontaal vlak te zijn.

**Comment by skornsekj** [comment]
CVGG en Prorail hebben issue besproken. Prorail gaat accoord met wijzigingsvoorstel. Dus verwijderen van de regel 'Alle z-coördinaten in Brug.geometrie moeten dezelfde waarde hebben.' Prorail gaat NIET accoord met alternatieve voorstel.

**Comment by PB-GNM** [comment]
Expertgroep 14-9 ondersteunt het doorvoeren van deze wijziging.
Er was nog wel een vraag over de definitie van Brug: Waarom alleen over een watervlakte of waterloop?
Een suggestie is om de definitie voor Overbruggingsdeel uit IMGEO te gebruiken, maar wel om de objectnaam Brug aan te houden, zodat de impact beperkt blijft. Dit wordt een apart issue voor een versie na versie 3.1.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.1.
