### ISSUE TITLE
Monitoringsresultaat aanpassen (SDIMG-125, WELT-270)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#203]
# Aanleiding wijziging
Toelichting

- Het object monitoringresulaat wordt zowel gebruikt voor een GPP als een BGE. In het geval van een BGE bevat de monitoringswaarde het verschil tussen de geluidemissie in Lden en de basisgeluidemissie, in het geval van een GPP bevat de monitoringwaarde de berekende geluidwaarde. Dat staat weliswaar beschreven in de toelichting, maar is niet duidelijk beschreven in de definitie van het attribuut monitoringwaarde ansich. Graag duidelijk beschrijven in de definitie, zodat dit eenduidig is voor de gebruiker. 
- De monitoringwaarde van een BGE bevat een verschil. Dat betekent dat de monitoringwaarde ook negatief kan zijn. In de xsd wordt echter afgedwongen dat de waarde 0 of groter moet dan. Dat klopt niet en moet worden aangepast. 

# Voorgestelde wijziging
***Wijzingen object Monitoringresulaat***

![image](https://github.com/Geonovum/IMG/assets/80040145/2475fc57-4404-446a-a79a-d643c5d26e4b)

- Verwijder de teksten die hieronder zijn doorgestreept

![image](https://github.com/Geonovum/IMG/assets/80040145/abf2f7cb-2239-411f-a570-3a300a41525b)

***Wijzingen attribuut monitoringwaarde***

- Aanpassen definitie: 

1. Indien de monitoringswaarde betrekking heeft op een geluidproductieplafond bevat de monitoringwaarde de berekende geluidwaarde van het jaar waarop de monitoring betrekking heeft in dB afgerond op 1 decimaal.
2. Indien de monitoringswaarde betrekking heeft op een basisgeluidemissiewaarde  bevat de monitoringwaarde het verschil tussen de geluidemissie in Lden en de basisgeluidemissie van het jaar waarop de monitoring betrekking heeft in dB afgerond op 1 decimaal.

***Wijzigingen applicatieschema (xsd)*** 

- Monitoringswaarde mag voor een BGE ook negatief mag zijn.  Het immers het verschil. In de huidige IMG3.0 xsd is de minimale waarde echter ‘0’.  Dat moet aangepast worden 
- Voorgestelde wijziging: min. waarde -99.9. De max waarde blijft 99.9  

![image](https://github.com/Geonovum/IMG/assets/80040145/7075f59a-d4f3-43b9-895e-084106bbb920)

***Aandachtpunt bij object MonitoringsresultaatIndustrie***

- Bij het wijziging van de teksten in de definitie van Monitoringresultaat moet de tekst van de definitie in het overzicht van de relaties ook aangepast worden.  

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
-Wie gaat er wat van merken? **Data providers, softwareleveranciers**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
-Is er een herlevering nodig naar de CVGG? **Nee**
-Heeft het impact op het xml-schema? **Ja**
-Is het backward compatible in de zin van validatie op het schema? **Ja**
-Heeft het impact op de regels in IMG? **Ja**
-Heeft het impact op de validatieregels voor de CVGG? **Ja**
-Heeft het impact op de omgevingsregeling? **Ja/Nee**
-Is het een X, Y, of Z wijziging? **Y**

# Toelichting
Ruimte voor extra toelichting. Bijvoorbeeld alternatieven die je overwogen hebt.

**Comment by skornsekj** [comment]
RWS geeft het volgende aan: 
_De kardinaliteit moet 0..1 blijven. De reden hiervoor is dat als we een vrijstelling hebben we de locatie niet kunnen berekenen en er dus ook geen monitoringswaarde bepaald kan worden._

**Comment by skornsekj** [comment]
CVGG en Prorail hebben issue besproken. Prorail heeft geen bezwaar tegen tekstuele wijzigingen en wijziging xsd.  Of de kardinaliteit naar [1] kan zou nog nader uitgezocht moeten worden. Hierbij geldt - net als RWS al opgemerkt heeft - dat er nog uitgezocht / besproken moet worden wat er precies wel of niet in een aanlevering van een bestand met monitoringresultaat moet zitten, voor Geluidproductieplafondobjecten waar een vrijstelling voor geldt.

**Comment by skornsekj** [comment]
@PB-GNM Nav van reacties van RWS en Prorail stel ik voor één onderdeel van het wijzigingsverzoek aan te passen.
De kardinaliteit van attribuut monitoringwaarde blijft zoals die is: [0..1]. Het voorstel om dat veranderen naar [1] vervalt.

**Comment by PB-GNM** [comment]
Vanwege bovenstaande discussie is het verzoek om de kardinaliteit van attribuut monitoringswaarde op 1 te zetten uit [het voorstel](https://github.com/Geonovum/IMG/issues/203#issue-1874998211) gehaald.

**Comment by PB-GNM** [comment]
Expertgroep 14-9 ondersteunt het doorvoeren van deze wijziging.
Dan wel met de waarden -199.9 en 199.9. Zie ook bug #201.

Ook is besproken of er niet 2 subtypen monitoringsresultaat gemaakt zouden moeten worden. Eén voor BGE-monitoringswaarden en één voor GPP-monitoringswaarden. Hier moet nog nader over nagedacht worden.
Hier wordt een apart issue van gemaakt dat nog niet wordt opgenomen in versie 3.1.

**Comment by PB-GNM** [comment]
Verwerkt in versie 3.1.
