### ISSUE TITLE
Definitie Brug aanpassen (SDIMG-xxx, WELT-yyy)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#204]
# Aanleiding wijziging
De huidige definitie voor IMG-objecttype Brug is gekopieerd van de IMGEO-attribuutwaarde Brug. Deze is beperkt tot overgangen over water, maar binnen IMG worden alle type overgangen eigenlijk bedoeld met Brug. 

# Voorgestelde wijziging

Het is beter om de definitie voor IMGEO-objecttype Overbruggingsdeel te gebruiken, want dat dekt de lading beter.
**Onderdeel van een beweegbare of vaste verbinding tussen twee punten, die door water, een weg of anderszins gescheiden zijn, dat essentieel is voor de constructie.**
Aanpassen van de objectnaam Brug naar Overbruggingsdeel is niet gewenst gezien de grote impact. Dat zou een X-wijziging zijn.

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
-Wie gaat er wat van merken? **Data providers, softwareleveranciers**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Ja**
-Is er een herlevering nodig naar de CVGG? **Nee**
-Heeft het impact op het xml-schema? **Nee, alleen een commentaar veld wijzigt met een definitie en dat heeft geen invloed op software.**
-Is het backward compatible in de zin van validatie op het schema? **Ja**
-Heeft het impact op de regels in IMG? **Nee**
-Heeft het impact op de validatieregels voor de CVGG? **Nee**
-Heeft het impact op de omgevingsregeling? **Nee**
-Is het een X, Y, of Z wijziging? **Z**

# Toelichting
Dit heeft een relatie met #200

**Comment by JO-RIVM** [comment]
Onze akoestische expert(s) hebben gezegd dat er geen specifieke definitie bij geluid is en willen uitgaan van een algemeen aanvaarde definitie zoals de volgende:

Een brug is een vaste of beweegbare verbinding voor het verkeer, tussen twee punten die gescheiden zijn door een rivier, kanaal, kloof, dal, weg, spoorweg of een ander obstakel. (https://www.bruggenstichting.nl/informatief/wat-is-een-brug).

**Comment by PB-GNM** [comment]
Adviesgroep 12-3-2024: Voorgestelde definitie: _Een brug is een vaste of beweegbare verbinding voor het verkeer over een obstakel._
