### ISSUE TITLE
CODELIJST::materieelsoorten

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#21]
# Samenvatting
Op dit moment bestaat nog geen uniforme en limitatieve lijst. ProRail heeft wel een volledige lijst?
Van materieelsoort moet je hoe dan ook weten in welke **_spoorvoertuigcategorie_** het zit. Bijlage IV van het RMV-spoor somt de materieelsoorten als onderdeel van de spoorvoertuigcategorieën op, maar deze lijst is niet volgens iedereen volledig. Volgens sommige partijen variëren de in de praktijk gehanteerde lijsten onderling, o.a. vanwege toepassing voor verschillende doeleinden.

**Vragen**
 - Is materieelsoort nodig voor de GPP-berekening?
 - Naar welke waardelijst moet het informatiemodel verwijzen?
 - Welk type waardelijst wordt hiervoor gebruikt in het informatiemodel?
 - Wat is het standpunt van de wetgever ten aanzien van de materieelsoortlijst?

 # Voorgestelde oplossing
- De waarden in uit de lijst moeten tenminste ingedeeld kunnen worden in een **spoorvoertuigcategorie**
 - Je hebt een **emissiewaarde** nodig
 - Overzicht van **emissiekengetallen per materieelsoort**
 - Voor lokaal spoor heb je **één lijst** nodig met alle materieelsoorten
 - Een stukje van het lokale spoormaterieel zit wel in de lijst van ProRail
 - Dit moet in **één lijst** komen

Voorstel: waardelijst materieelsoort opvoeren, maar dan meer als een referentielijst(?) waar dan de spoorvoertuigcategorie aan is toegevoegd.

# Beslissing
 -	De lijst met materieelsoort is noodzakelijk: voor de GPP-berekening/doen van akoestisch onderzoek.
 -	Materieelsoort is meer dan alleen namenlijst:  (remsysteem, maximumsnelheid, voertuigcategorie en aantal bakken)
- **Staat nog wel open hoe we dit gaan opnemen, hoe de lijst eruit gaat zien en wie de lijst beheert.**

**Comment by joerivanes** [comment]
In overleg met RIVM is besloten dat het voor de CVGG geen toegevoegde waarde is om deze lijst met materieelsoorten op te nemen in het geluidregister.
