### ISSUE TITLE
DATATYPE:Measure - voor decibelwaarden dB of dB(A)?

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#22]
# Samenvatting
Het datatype **_Measure_** legt de **_eenheid_** en de **_waarde_** van een attribuut vast. Voor de decibelwaarden is nog niet besloten welke eenheid dat precies is. Vanuit historie eerst etmaalwaarden (oud) en later Lden  (nieuw). Inhoudelijk zijn dat allemaal gewogen eenheden (db(A)), maar dat wordt in de registers opgenomen als dB. Behalve voor industrie

**Vragen**
- Leggen we voor alle attributen met een waarde in decibel _**dB**_ of _**dB(A)**_ vast?
- In hoeveel decimalen leggen we die waarde vast?
- Hoe worden dB's bij Industrie vastgelegd? 

# Voorgestelde oplossing
 - Eenheid: dB (overal in het model)
 - Decimalen: 2
 - Voor industrie gelden uitzonderingen @joerivanes ?

**Comment by joerivanes** [comment]
Alles is in dB(A), maar wordt gewoon dB voor gebruikt. Het is vanzelfsprekend dat A filter is toegepast op alle dB waardes. (werd duidelijk uit werksessie industrie)

**Comment by joerivanes** [comment]
Verholpen door herziening van model alles in dB
