### ISSUE TITLE
Attribuut Geluidproductieplafondobject.vaststellingVanRechtswege optioneel maken (SDIMG-141, WELT-yyy)

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#220]
# Aanleiding wijziging
Dit wijzigingsverzoek is aangeleverd vanuit het Ministerie van IenW met de volgende motivatie:
- Bij elk gpp moet ingevuld worden of hij wel of niet van rechtswege is vastgesteld, dat is belastend voor partijen waarvoor deze mogelijkheid sowieso niet bestaat.
- Wanneer een documentverwijzing wordt aangeleverd, is duidelijk dat ‘vaststellingVanRechtswege’ = nee, dus dan voegt het invullen van dit attribuut geen informatie toe.

# Voorgestelde wijziging
Attribuut Geluidproductieplafondobject.vaststellingVanRechtswege optioneel maken.

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
-Wie gaat er wat van merken? **Data providers, softwareleveranciers**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
-Is er een herlevering nodig naar de CVGG? **Nee**
-Heeft het impact op het xml-schema? **Ja**
-Is het backward compatible in de zin van validatie op het schema? **Ja**
-Heeft het impact op de regels in IMG en de validatieregels voor de CVGG? **Ja:**

> -  Als ‘Documentverwijzing’ ontbreekt, moet ‘vaststellingVanRechtswege’ ‘ja’ zijn.
> -  Als ‘vaststellingVanRechtswege’ = nee, dan moet er minimaal één Documentverwijzing zijn. 

- Heeft het impact op de omgevingsregeling? **Nee**
-Is het een X, Y, of Z wijziging? **Y**

# Toelichting
Zoals aangegeven bij #219 kan voor rijkswegen en hoofdspoorwegen ook een link naar artikel 11.45 Wm worden opgenomen in plaats van een ‘ja’ bij ‘vaststellingVanRechtswege’, in dat geval is dit attribuut ook voor deze geluidbronsoorten optioneel (want overbodig geworden).

**Comment by GerdadeVries23** [comment]
De validatieregels hoeven niet noodzakelijk in het IMG te worden opgenomen. Ze kunnen ook alleen als waarschuwende validaties alleen in de Cvgg worden opgenomen.

**Comment by skornsekj** [comment]
@PB-GNM @GerdadeVries23 
Ter info. In de CVGG hebben we inmiddels de volgende 2 validatieregels als waarschuwing geimplementeerd. Lijkt me goed dat de issues / oplossing in IMG daar zoveel mogelijk op aansluiten. 

- CVGG177: Wanneer geluidbron is provinciale weg, industrieterrein of lokale spoorweg, is vaststelling van rechtswege juridisch niet mogelijk. Geluidproductieplafond.VastellingVanRechtwege moet 'false' zijn.
- CVGG178: Wanneer Geluidproductieplafond.VastellingVanRechtwege is 'false' moet het objecttype Geluidproductieplafond een xlink met objecttype Documentverwijzing bevatten.

**Comment by PB-GNM** [comment]
Het lijkt ons niet verstandig om dit attribuut optioneel te maken. Dan ontstaat er naast de 2 waarden "True" en "False" ook nog de optie dat het veld "Null" bevat. Daarmee moeten ook de bestaande regels hierop gecontroleerd worden.
Bovendien lijkt het niet veel werk om "True" of "False" in te vullen. Vermoedelijk 1 vinkje. Eventueel zou wel al vast "False" als default ingesteld kunnen worden. Ook kan het in de betrokken applicaties automatisch de waarde ingesteld kunnen worden op basis van de geldende regels en het bestaan van documentverwijzingen en de vraag of het om hoofdspoornet en rijkswegen gaat of niet.
@GerdadeVries23 : Is het goed als we het beperken tot het opnemen van een defaultwaarde "False" ?

**Comment by skornsekj** [comment]
@PB-GNM Ik vraag me af of je een default waarde kunt opnemen in een Informatiemodel? Of bedoel je iets anders?

**Comment by PB-GNM** [comment]
> @PB-GNM Ik vraag me af of je een default waarde kunt opnemen in een Informatiemodel? Of bedoel je iets anders?

@skornsekj In Enterprise Architect heet het "Initial Value" (zie afbeelding). We moeten nog wel testen hoe dit dan ook in het xsd-schema terechtkomt.
![image](https://github.com/user-attachments/assets/ee1d076a-f4a0-4d82-9848-49a3eeafab24)

**Comment by wilkoquak** [comment]
Een default waarde in het UML zorgt voor een verschil zorgt ervoor dat in de uitwisseling het attribuut optioneel wordt en dat je dan bedoelt dat het attribuut in de werkelijkheid wel een waar de heeft. Maar ik ben geen voorstander van deze constructie.

Het GML een technisch uitwisselmodel waar je zo expliciet mogelijke moet zijn.  Een waarde true of false blijft het duidelijkst. Je maakt het er niet duidelijker op door te zeggen: als je niks invult bedoel je false.

De door @skornsekj voorgestelde regel maakt dat helemaal duidelijk en in software is het dan wel zo te regelen dat de juiste waarde automatisch wordt ingevuld voor partijen voor wie de keuze niet bestaat.

**Comment by GerdadeVries23** [comment]
Gelet op de commentaren wil ik mijn voorstel wel intrekken. Het probleem was dat er makkelijk fouten mee kunnen worden gemaakt, maar dit wordt ook ondervangen door de extra toelichting en de validatieregels.

**Comment by PB-GNM** [comment]
> Gelet op de commentaren wil ik mijn voorstel wel intrekken. Het probleem was dat er makkelijk fouten mee kunnen worden gemaakt, maar dit wordt ook ondervangen door de extra toelichting en de validatieregels.

Na overleg met RIVM op 9-10-2024 is besloten dit verzoek niet te gaan uitvoeren vanwege genoemde bezwaren in dit issue.
