### ISSUE TITLE
Eén extra attribuut voor verschil monitoringswaarde GPP

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/IMG#229]
# Aanleiding wijziging
Dit verzoek is ingediend door RWS met helpdesknummer SDIMG-156 en met de volgende motivatie:
Voor de burger is het handig om in het geval van GPP bij de monitoring ook de delta te zien tussen het monitoringsresultaat (de monitoringswaarde) en een vergunde ruimte. Daarom is een extra veld gewenst bij een MonitoringsresultaatGPP, zodat de burger de geluidsruimte/overschrijding eenvoudig kan zien.  

# Voorgestelde wijziging
- Voeg een verplicht attribuut verschilMonitoringswaarde toe aan MonitoringsresultaatGPP. Hierin zit het verschil tussen de absoluteMonitoringswaarde en het GPP.
- Voeg een verplicht attribuut verschilMonitoringswaardeLnight toe aan MonitoringsresultaatIndustrie. 

De eindsituatie na verwerking van issue #205 en dit issue:
![afbeelding](https://github.com/user-attachments/assets/74063dc4-a8f4-4f61-a2b8-efc845b746e7)

# Impactanalyse
Geef hier een indicatie van de impact van de wijziging:
-Wie gaat er wat van merken? **Data providers, softwareleveranciers**
-Veranderen definities van objecten in de standaard zodanig dat de wijziging impact heeft op de uit te wisselen gegevens? **Nee**
-Is er een herlevering nodig naar de CVGG? **Nee, want er zijn nog geen leveringen gedaan**
-Heeft het impact op het xml-schema? **Ja**
-Is het backward compatible in de zin van validatie op het schema? **Nee**
-Heeft het impact op de regels in IMG? **Nee**
-Heeft het impact op de validatieregels voor de CVGG? **Nee**
-Heeft het impact op de omgevingsregeling? **Nee**
-Is het een X, Y, of Z wijziging? **Y**

# Toelichting
Het gaat hier nadrukkelijk om het verschil zoals dat gerapporteerd is.
Dat kan afwijken van wat er uit een berekening zou kunnen komen.

**Comment by skornsekj** [comment]
Ik stel voor het nieuwe attribuut verplicht te maken. Het heeft denk ik alleen meerwaarde als iedere bronhouder deze informatie aanbied, en niet de ene bronhouder wel en de andere niet.

**Comment by PB-GNM** [comment]
> Ik stel voor het nieuwe attribuut verplicht te maken. Het heeft denk ik alleen meerwaarde als iedere bronhouder deze informatie aanbied, en niet de ene bronhouder wel en de andere niet.

Het heeft nu kardinaliteit {1} , dus het is verplicht.

**Comment by JO-RIVM** [comment]
Wijzigingsverzoek die met monitoringsresultaat te maken heeft:
Thijs Ruiter RWS: Het gaat om een extra veld bij de monitoring namelijk ook de delta zodat de geluidsruimte/overschrijding weer gegeven kan worden in de CVGG tussen de vergunde ruimte en het monitoringsresultaat.
Dorien Lolkema RIVM Product Owner CVGG: Eenduidigheid van gegevens vraagt dat gegevens maar een keer aangeleverd worden. Het verschil tussen plafondwaarde en monitoringswaarde moet daarom NIET aangeleverd worden. Immers, dit verschil volgt al uit de plafondwaarde en de monitoringswaarde. Voor het tonen van dit verschil (de geluidruimte/overschrijding) in de CVGG kan een verzoek ingediend worden welke de CVGG graag oppakt

**Comment by GerdadeVries23** [comment]
Het verschil tussen plafondwaarde en monitoringswaarde is niet een gegeven dat verplicht aangeleverd moet worden aan het geluidregister (artikel 11.52 Bkl). Het is ook niet wenselijk zoals Dorien beargumenteert. In het monitoringsverslag moet wel beoordeeld worden in hoeverre aan de geluidproductieplafonds wordt voldaan, en moet worden aangegeven welke maatregelen getroffen worden die gericht zijn op het voldoen aan een geluidproductieplafond. Hoe hierover wordt gerapporteerd is vrijgelaten, en dat kan natuurlijk met het weergeven van een verschilwaarde. Bij de aanlevering aan de Cvgg hoort ook een link naar het monitoringsverslag, zodat daar eventueel wel de verschilwaarden te vinden zijn.

**Comment by wilkoquak** [comment]
In de adviesgroep van 24 oktober is besloten dat het verschil bij GPP niet aangeleverd hoeft te worden, maar indien gewenst kan worden uitgerekend door de CVGG. Dit wijzigverzoek wordt dus niet doorgezet.
