### ISSUE TITLE
OBJECT::[meerdere]:hoogte - welke waarden, waar vastleggen?

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#24]
# Samenvatting
Verschillende objecten in de modellen GPP-weg/-spoor/-industrie en BGE-weg/-spoor, bevatten hoogte-informatie. Er is discussie over welke hoogte-informatie waar en op welke manier vastgelegd moet worden.

Het gaat voor GPP-wegen om hoogte-informatie van de volgende objecten:
 - Rijlijn
 - Andere maatregel
 - Afschermend object (zie ook issue #72)
 - WegObstakel (provincies)

Overig
 - Algemeen (zie ook issue #61)
 - Referentiepunten (zie ook issue #73) 
 - Gebouwen (industrie) (zie ook issue #15 )

**Vragen**
 - Welk type hoogte vertegenwoordigt de z-waarde in de geometrie?
 - Kan de maaiveldhoogte ten opzichte van N.A.P. gehanteerd worden?
 - Is een apart attribuute van het afschermend object nodig?
 - Wat is het verschil tussen de attributen geometrieTop en -Voet en z- en m-waarde?
 - In het rekenhart worden de z- en m-waarden bij elkaar opgeteld.

# Voorgestelde oplossing
Uitbespreking met software-leveranciers:
 - Voor ieder overdrachtsobject in principe:
 - 3D-geometrie: x,y (locatie) en z voor (absolute) hoogte t.o.v. NAP

**Comment by joerivanes** [comment]
Verwerkt in informatiemodel
