### ISSUE TITLE
DATATYPE::Measure - eenheden en decimalen voor niet-geluidwaarden

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#25]
# Samenvatting
Het datatype **_Measure_** legt de **_eenheid_** en de **_waarde_** van een attribuut vast. Voor alle niet-geluidwaarden is nog niet definitief besloten welke eenheid dat precies is.

Voor GPP-wegen gaat het in elk geval om de volgende attributen:
 - Breedte (Diffractor)
 - Hoogte  (Diffractor)
 - Hellingshoek (AfschermendObject) (zie ook: issue #41)

**Vragen**
 - Wat is de eenheid van de waarde van tenminste de bovenstaande attributen?
 - In hoeveel decimalen leggen we die waarden vast?

# Voorgestelde oplossing

**Helllingshoek**
 - Naar **links** hellend scherm (_**t.o.v. de digitaliseerrichting**_) = **negatieve waarde (-)** 
 - Naar **rechts** hellend scherm (**_t.o.v. de digitaliseerrichting_**) = **positieve waarde (+)** 
 - eenheid: graden,
 - decimalen: 0

**Breedte en Hoogte** (Diffractor)
 - eenheid: meter
 - decimalen: 2

**Comment by joerivanes** [comment]
Ik ben het eens met deze verdeling. Waar kan dit worden verwerkt?

**Comment by joerivanes** [comment]
@lvdbrink hoe verwerken we dit? Als tagged waardes bijvoorbeeld, of in properties, of regels?

**Comment by Gtrouborst** [comment]
Voor alle getalswaarden (inclusief geluidwaarden) zijn formele patronen opgesteld waarin exact is vastgelegd welke waarden er gelden.

**Comment by Gtrouborst** [comment]
Overzicht van opgenomen reguliere expressies in het model:

``` regex
(?# Algemeen voorbeeld syntax [altijd] twee cijfers voor de komma en één cijfer achter de komma)
^[0-9]{2}\,[0-9]$

(?# Hele decibellen [industrie])
^[0-9]{1,2}$

(?# schermen met hoek van -90 tot +90 graden en een 0, zonder +/- teken)
(^0)|(^[+-][0-8]{1,2}$)|(^[+-][0-9][0]$)

(?# Waardenbereik van 0,00 tot 1,00)
(^0\,[0-9]{2}$)|(^1\,0{2}$)

(?# intensiteitSpoor: 0,0 - 999,9)
^[0-9]{1,3}\,[0-9]$

(?# positie van en tot 0 - 99999...n)
^[0-9]{1,}$

(?# snelheidSpoor: 0 - 999)
^[0-9]{1,3}$

(?# plafondcorrectiewaardeWeg (nu 0,0 of 1,5 maar kan varieren in de toekomst)
^[0-9]\,[0-9]$

(?# BGE: 0,0 - 99,9)
^[0-9]{1,2}\,[0-9]$

(?# intensiteitWeg: 0,00 - 9999,99)
^[0-9]{1,4}\,[0-9]{2}$

(?# snelheidWeg: 0 - 999)
^[0-9]{1,3}$

(?# FactorPerOctaafband: 0,00 - 1,00)
(^0\,[0-9]{2}$)|(^1\,0{2}$)

(?# WaardeOctaafband: 0,00 - 999,99)
^[0-9]{1,3}\,[0-9]{2}$

(?# breedte diffractor: 0,00 - 999,99)
^[0-9]{1,3}\,[0-9]{2}$

(?# absorptiefractie: 0,00 - 1,00)
(^0\,[0-9]{2}$)|(^1\,0{2}$)

(?# monitoringswaarde 0,0 - 99,9)
^[0-9]{1,2}\,[0-9]$

(?# referentiepunt: 3,5 - 4,5)
(^3\,[5-9]$)|(^4\,[0-5]$)

(?# geluidproductieplafond: 0,0 - 99,9)
^[0-9]{1,2}\,[0-9]$

(?# plafondcorrectiewaardeSpoor: -99,9 - 99,9)
(^\-[0-9]{1,2}\,[0-9]$)|(^[0-9]{1,2}\,[0-9]$)

(?# double list: -999,99 - 999,99)
(^\-[0-9]{1,3}\,[0-9]{2}$)|(^0\,[0-9]{2}$)|(^[0-9]{1,3}\,[0-9]{2}$)

(?# OIN/HRN:)
^[1-9]{20}$

(?# basisgeluidemissiewaarde: 0,0 - 999,9)
^[0-9]{1,3}\,[0-9]$
```
