### ISSUE TITLE
OBJECT::Monitoringswaarde - Tijdelijke ontheffing en vrijstelling

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#29]
# Samenvatting
De huidige geluidregisters GPP-spoor en GPP-weg kennen onder andere een **_tijdelijke ontheffing_** en een **_vrijstelling_**.

**Tijdelijke ontheffing**
Op een GPP kan een tijdelijke ontheffing gelden (TM_Period). Nog uitgezocht moet worden of er dan wel monitoringswaarden (moeten) worden vastgelegd.

**Vrijstelling**
Een andere situatie is dat een GPP wordt vastgesteld voor een nog aan te leggen nieuwe weg. In dat geval wordt er op dat traject nog niet gereden. Er kan dus ook nog niet gemonitord worden. Er is een vrijstelling van de monitoringsverplichting. In dat geval kan een GPP geen monitoringswaarde hebben, vandaar nu de multipliciteit: 0..*

**Vragen**

1. Komen deze typen beiden terug in de nieuwe wet- en regelgeving?
2. Zo ja, onder welke naamgeving?
3. Welke informatie leggen we daarvan vast?
4. Waar leggen we deze informatie vast?
5. Wat is de werking van een dergelijke toepassing?
6. Zijn de tijdelijke ontheffing en vrijstelling op alle domeinen van toepassing?
7. Kan de situatie zoals genoemd onder vrijstelling ook vastgelegd worden met een TM_Period?
8. Is dit een generieke situatie, d.w.z.: hebben spoor en industrie en BGE's hier ook mee te maken? Indien niet het geval: dan is er een regel nodig.

# Voorgestelde oplossing
**[LET OP]**: Wijzigingen in het model hebben betrekking op alle domeinen!
**[LET OP]**: Uitzoeken of dit voor alle domeinen van toepassing is.

Een **_vrijstelling_** kan op dit moment door het bevoegd gezag worden opgenomen als onderdeel van het besluit of als een apart besluit (zie: bovengrens kardinaliteit in de relatie tussen de objecten **_Geluidproductieplafond_** --> **_Besluit_**).

Attribuut _**tijdelijkeNietNalevingsplicht**_ hernoemen naar **_tijdelijkeOntheffing_**

# Beslissing
Zowel de tijdelijke ontheffing als de vrijstelling moeten in het model worden opgenomen.
De tijdelijke ontheffing kan een maximale overschreidingsmarge hebben, maar die hoeft niet in het model.

**Comment by Gtrouborst** [comment]
# Samenvatting
In aanvulling op bovenstaande issue is het verzoek om bij een ontheffing ook de tijdelijke ontheffingswaarde op te nemen.

# Voorgestelde oplossing
Attribuut **_ontheffingswaarde_** opnemen

**Comment by joerivanes** [comment]
Verholpen door herziening van model
