### ISSUE TITLE
Attribuut: Snelheden

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#3]
Er zijn 3 typen snelheid genoemd:

1. maximale snelheid
2. rekensnelheid
3. werkelijke snelheid

Vragen:

- Welke snelheid/snelheden zijn relevant voor het model?
- Hoe zou het datatype eruit moeten zien?
- Hoe vaak komt het datatype voor?

**Comment by Gtrouborst** [comment]
Voor het model is *alleen* de **representatief te achten snelheid** relevant. Dat is de snelheid zoals die in de wet is vastgelegd. Dit kan de maximale snelheid zijn, of een correctie daarop. Dit is vertaald naar het attribuut: **representatieveSnelheid**

Uit de documentatie van het geluidregister van RWS kwam een vaste lijst met voorgedefinieerde rekensnelheden. Besloten is om aan het attribuut snelheid geen waardelijst te geven, maar een integer.

**Comment by Gtrouborst** [comment]
> Dit kan de maximale snelheid zijn, of een correctie daarop

In het laatste geval staat nog de vraag open of de wens is om een toelichting op te kunnen nemen in het model

**Comment by Gtrouborst** [comment]
> Hoe zou het datatype eruit moeten zien?

Datatype **Snelheden** wordt op vergelijkbare wijze vormgegeven als het datatype **Intensiteiten**. Een gestructureerd datatype met de attributen:

- **representatieveSnelheid**: float(2)
- **voertuigcategorie**: VoertuigType (enum)
- **dagdeel**: Dagdeel (enum)

**Comment by Gtrouborst** [comment]
> Hoe vaak komt het datatype voor?

Er zijn **drie** **dagdelen** (dag, avond en nacht) en **drie** **voertuigcategorieën** (licht, middel en zwaar). Elk object **Rijlijn** heeft voor het attribuut **Snelheden** exact **9 waarden** (multipliciteit: **9..9**)

**Comment by joerivanes** [comment]
Oud
