### ISSUE TITLE
OBJECT::Geluidaandachtsgebied - Relatie met Beperkingengebied in Omgevingswet

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#30]
# Samenvatting
**_Geluidaandachtsgebieden_** moeten/kunnen worden vastgelegd in een aantal instrumenten oftewel besluittypen die hun basis hebben in de **_Omgevingswet_**. In het Informatiemodel Omgevingswet hebben we voor de Geluidaandachtsgebieden een type **_Gebiedsaanwijzing_**. Er is dus al in voorzien. Niet exact het zelfde als Beperkingengebied, maar wel **_vergelijkbaar_**.

# Voorgestelde oplossing
Zou goed zijn om de aansluiting tussen beide projecten en informatiemodellen te zoeken om beide krachtiger te maken en inzichtelijk te houden voor werkveld en gebruikers.

**Comment by wilkoquak** [comment]
Goed punt.  De twee klasses lijken al aardig op elkaar. Voorstel is om in de documentatie de relatie tussen de twee de documenteren.

**Comment by PB-GNM** [comment]
Dit onderwerp is aan de orde gekomen bij https://github.com/Geonovum/IMG/tree/gh-pages/END
Het hoort daarom hier niet meer thuis en wordt gesloten.
