### ISSUE TITLE
OBJECT::Obstakel - wel/niet in informatiemodel

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#36]
# Samenvatting

Emissieverhogende elementen zoals de typen die binnen het object obstakels vallen, zijn bewust uit het reken- en meetvoorschrift van de GPP-berekening weggelaten. Voor de GPP-berekening neem je obstakels namelijk niet mee, maar voor de berekening van de geluidbelasting wel. Daarom is er vanuit provincies behoefte om de obstakels mee te nemen in de voorziening.

Op basis van de huidige wet- en regelgeving is het object **Obstakels** **geen brongegeven** (je mag het niet meenemen in de GPP-berekening) maar een **omgevingskenmerk**. Ze _mogen_ meegenomen worden in de berekening van het GAG. Obstakels zouden een aparte positie in het model moeten krijgen als je ze in de huidige situatie (optioneel) wilt faciliteren. Pas als apart object, kan Obstakels optioneel gemaakt worden. De provincies zouden graag zien dat obstakels wel in het reken- en meetvoorschrift worden opgenomen als onderdeel van de GPP-berekening.

**Emissieverhogende elementen**

- Drempel
- Minirotonde
- Kruispunten (Eerste en tweede orde en (on)gelijkwaardig)

# Voorgestelde oplossing
 - Overzicht maken van **_geluidbrongegevens_**, **_dienstverleningsgegevens_**, **_overige gegevens_**
 - Besluiten of Obstakels in de op te leveren versie van het IMGeluid al een plek krijgen
 - Relatie van Obstakels met Rekenobjecten verwijderen.
 - Alleen relatie met andere gegevens o.b.v. geometrie
 - Obstakels op de '**wensenlijst**' zetten

**Comment by PB-GNM** [comment]
Uiteindelijk is de gekozen oplossing na overleg:
Optrektoeslag opnieuw gemodelleerd. Aparte klassen toegevoegd voor obstakels en kruispunten: Optrektoeslagpunt en optioneel Optrektoeslagvlak. Enumeratie toegevoegd: Kruispuntkental (=qwaarde) (issue IMG-82)
