### ISSUE TITLE
RELATIE::Monitoringswaarde>Rekenobject - Meeleveren rekengegevens

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#37]
# Samenvatting
In het informatiemodel ligt een relatie tussen het object **Monitoringswaarde** en **Rekenbobject**. Deze relatie biedt optioneel de mogelijkheid om naaste de verplichte monitoringswaarde ook de daarvoor gebruikte **onderliggende rekengegevens** mee te leveren.

**Vraag**
 - Klopt dit, of kan de relatie weg (zie ook: issue #80)

# Voorgestelde oplossing
 - Relatie kan blijven en kardinaliteit is goed
 - RWS wil deze gegevens graag mee kunnen leveren
 - De provincies hebben hier op dit moment nog geen zicht op
 - Dit zal niet voor elke provincie hetzelfde zijn
 - Vanuit beide partijen behoefte om in het model die optie te bieden.

[**LET OP**]: Dit betekent niet autmatisch dat de CVGG dit gaat faciliteren. Deze discussie loopt nog

**Comment by joerivanes** [comment]
Buiten Scope informatiemodel
