### ISSUE TITLE
Attribuut: Intensiteiten

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#4]
Vragen:
- Welke **definitie** hanteren we hier voor waarden uit de enumeratie Dagdeel?
- Uit welke **bron** is de **definitie** afkomstig?
- Welke **voertuigcategorieën** zijn relevant voor het model?
- Hoe zou het **datatype** eruit moeten zien?
- Hoe vaak komt het **datatype** voor?

**Comment by Gtrouborst** [comment]
> Welke voertuigcategorieën zijn relevant voor het model?

De **wet** onderscheidt **drie voertuigcategorieën**: licht, middel en zwaar. Het is denkbaar dat dit in de toekomst wordt uitgebreid met andere categorieën. Er is besloten om een **enumeratie** toe te passen en bij uitbreiding een wijziging van het model te maken.

**Comment by Gtrouborst** [comment]
>Hoe vaak komt het datatype voor?

Er zijn **drie dagdelen** (dag, avond en nacht) en **drie voertuigcategorieën** (licht, middel en zwaar). Elk object **Rijlijn** heeft voor het attribuut **Intensiteiten** exact **9 waarden** (multipliciteit: **9..9**)

**Comment by joerivanes** [comment]
Oud
