### ISSUE TITLE
CODELIJST::Cwegdek

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#40]
# Samenvatting
Het attribuut **wegdektype** in het object **_Rijlijn_** verwijst naar de codelijst **Cwegdek**. De codelijst wordt extern beheerd door Infomil en is daarom niet integraal opgenomen in het model, maar als [link naar de website](https://www.infomil.nl/onderwerpen/geluid/regelgeving/wet-geluidhinder/wegverkeerslawaai/akoestisch-rapport/cwegdek/), waar een Excel-bestand gedownload kan worden. Deze lijst wijzigt regelmatig. 

 -	Is er nagedacht over m.n. niet generieke deel
 -	Er zijn ook een aantal generieke deklagen die niet fabrikantgebonden zijn
 -	Wil de wet- of regelgeving daar nog iets in voorschrijven?
 -	Kan zijn dat de lijst limitatiever wordt

**Vragen**
- Hoe landt deze codelijst precies in het model?
- Zijn er cijfercodes die verwijzen naar de wegdektypen (voorkeur vanuit bronhouders)?
- Of is het een geschreven lijst met namen van wegdektypen?
- Kunnen er ook typen uit de lijst verdwijnen?
- Wat gebeurt er met reeds ingevoerde typen die later wijzigen?

# Voorgestelde oplossing
 - Link naar Infomil behouden
 - Bij implementatie (bouw) keuze maken tussen cijfercodes of namen
 - In AREG-overleg overeengekomen:
 	 - Er wordt een **nieuwe** (limitatieve) **lijst** ontwikkeld;
 	 - In **toelichting** van de codelijst opnemen: standaardcategorieën verplichten
 	 - Andere **naamgeving** codelijst: voorstel = **standaardcategorieën**

# Beslissing

[**LET OP**]: issue nog niet sluiten
  -	Type waardelijst nog wel de vraag: **codelijst of enumeratie**?
  -	Attribuutnaam wijzigen in: **_standaardcategorieënwegdektype_**
  -	Er komt nog een prioritering of selectie van verplichte lijstonderdelen
  -	Alleen naam en toelichting wijzigen.

**Comment by lvdbrink** [comment]
@Gtrouborst wordt de Cwegdek codelijst volgens de laatste inzichten opgenomen als link naar de infomil website? 

Dan is het type waardelijst ``codelijst``.

**Comment by joerivanes** [comment]
Issue voor RIVM

**Comment by joerivanes** [comment]
In overleg met RIVM besloten naar de externe waardelijst te verwijzen (codelijst). Er moeten nog plannen worden gemaakt voor het beheer van de cWegdek waardelijst. Er zijn ook plannen om de indeling van deze lijst aan te passen.
