### ISSUE TITLE
OBJECT::Besluit.linkNaarBesluit

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#44]
# Samenvatting
Het **besluit** dat ten grondslag ligt aan een **geluidproductieplafond** wordt niet als document aangeleverd, maar als **link**(URI). De vraag is **waar**, door **wie** en in **welk publicatieformaat** de documenten gepubliceerd worden. 

Er is een **LVBB** in ontwikkeling. Daar zouden de besluiten in moeten komen. Het verdient niet de voorkeur om de CVGG daarvan los te trekken. Tegelijkertijd zijn veel bronhouders bang dat de URI's wijzigen, waardoor de link naar een besluit breekt. Verder bestaat er een bureau verkeersvoorzieningen waar eveneens alle besluiten gepubliceerd worden. 

# Voorgestelde oplossing
 - Alle documenten (als PDF?) in de **CVGG** opnemen
 - In de **LVBB** opnemen (hoe gaan ze daarom met links?)
 - Bij **bureau verkeersvoorzieningen** (naam?) opnemen

**Comment by joerivanes** [comment]
Nog geen informatie over, maakt niet uit voor informatiemodel.

**Comment by joerivanes** [comment]
Beslissing voor bouwteam CVGG
