### ISSUE TITLE
BGE-modellen: relaties

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#47]
# Samenvatting
In GPP-modellen zijn een aantal relaties weggehaald, die in de BGE-modellen nog wel zitten. 

# Voorgestelde oplossing
Leg beide modellen nog een keer goed naast elkaar om te zien welke wijzigingen er hebben plaatsgevonden.

**Comment by joerivanes** [comment]
Verholpen door herziening van model
