### ISSUE TITLE
Relatie met bestaande modellen

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#5]
Er zijn verschillende modellen die objecten registreren die mogelijk aansluiten bij de benodigde onderdelen voor het informatiemodel geluid. Met betrekking tot wegen gaat het in elk geval om de volgende modellen:
- IMBGT/IMGEO
- IMBOR
- IMWV
- NWB

Er is besloten om bovenstaande modellen niet in het informatiemodel geluid op te nemen, omdat:
- **Geen enkele bron sluit** op dit moment (naadloos) **aan** bij de realiteit van het domein geluid,
- Er een **expliciete wens** is om **dataproviders** de **vrijheid** te **geven** om hun inwinning- en aanleversysteem te handhaven.

### Actie
Aanvankelijk zou het model *wel* de mogelijkheid bieden (optioneel) om **informatie over** de **herkomst van de rekengegevens** en **geometrie** vast te leggen. Hierdoor is duidelijk welke gegevens aan de berekening ten grondslag liggen. Bovendien biedt dit de mogelijkheid om een passieve **link** met **bestaande registraties** te leggen.

**Comment by Gtrouborst** [comment]
### Update_01
Dit is echter in een later stadium herzien, omdat:

- deze stap al intern plaatsvindt bij de dataproviders/Geomilieu (?) en een opname ervan in het IMG een **herhaling** zou zijn, waardoor:
- het een onnodige 'verzwaring van het systeem' zou zijn (administratieve lasten)

Dit betekent dat de gestructureerde datatypes **HerkomstRekengegevens** en **HerkomstGeometrie** zijn komen te vervallen en er binnen het model **_geen referentie naar andere modellen_** wordt gemaakt.

**Comment by Gtrouborst** [comment]
### Update_02
**Verwijzing** naar **herkomst berekening** graag **wél** als optioneel opnemen **in model**. Hieraan blijkt bij nader inzien toch behoefte. Iets dergelijks geeft inzicht en kan bijdragen aan het vertrouwen dat men in de data heeft.

**Comment by skornsekj** [comment]
**Update_03**
Verwijzing naar **herkomst geometrie** graag wel als optioneel opnemen in model.

**Comment by joerivanes** [comment]
Oud
