### ISSUE TITLE
 OBJECT::Geluidgegevenscollectie- Koppeling geluidgegevenscollectie met rest informatiemodel

### ISSUE THREAD

**Issue by joerivanes** [Geonovum/IMG#54]
# Samenvatting issue
Object Geluidgegevenscollectie is een centraal object waar historie in wordt bijgehouden en het is daarom belangrijk dat het object op een juiste manier verwerkt wordt in het informatiemodel geluid. Dit object is belangrijk voor het berichtenverkeer.

# Voorgestelde oplossing
- Relatie leggen met Geluidproductieplafond?
- Misschien meer koppelingen nodig?
- Wat moet het object precies en op welke manier vastleggen?

**Comment by joerivanes** [comment]
Bespreken met bouwteam, welke info moet erin?

**Comment by lvdbrink** [comment]
Als we nog wijzigingen gaan aanbrengen in de kern van het informatiemodel (zie issue #80), kunnen we op dat moment ook nadenken over de plek van de collectie klasse in relatie tot andere hoofdklassen in het model.

**Comment by joerivanes** [comment]
Verholpen door herziening van model
