### ISSUE TITLE
Object::Rijlijn

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#6]
### Vragen (nog uitwerken)
- toch Wegvak (ja/nee)
- type geometrie (ja/nee)
- linear referencing (ja/nee)

### Losse bevindingen (nog uitwerken)
- op welk niveau de lijn specificeren/op welk niveau zijn de attributen van toepassing?
- wat is de definitie?
- welke geometrie sluit het beste aan (LineString/MultiLineString, Linear Referencing/Dynamic Segmentation)?

ESRI over verschillende geometrieën: http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/shapes/types.htm
GisStackExchange over MultiLineString voor wegen:
https://gis.stackexchange.com/questions/24606/what-is-a-multilinestring

Specifieke vraag over een wegen(netwerk). Is er in het geval van geluid sprake van/behoefte aan een **netwerktopologie**? Het lijkt erop dat een **LineString** ook gebruikt kan worden om segmenten met verschillende eigenschappen een eigen 'string' te geven.

De properties in het model zijn van toepassing op alle **LineStrings** binnen de **MultiLineString**, dus kun je beter werken met **LineString** en **multipliciteit** >1.
Als je kijkt naar het geluidregister dan zie je eigenlijk dat het sommige lijnen niet met elkaar verbonden zijn: in dat geval zou het zelfs gaan om een **LineSegment** i.p.v. **LineString**. Dat laatste heb je wel minimaal nodig om lineaire referentie te kunnen toepassen.

Als ik het goed begrijp is een **Curve** niet van toepassing.
[**LET OP**] Dit is achterhaald: het model gebruikt GM_Curve (ISO19107)!
Binnen lijnen heb je:
- LineSegment (verbinding van twee punten)
- LineString (aaneenschakeling van LineSegments)
- MultiLineString (verzameling van LineStrings, al dan niet met elkaar verbonden)

En dan hebben we ook nog Linear Referencing/Dynamic Segmentation (voorbeeld in INSPIRE)

- OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture, p. 24 (v.1.2.1): (http://portal.opengeospatial.org/files/?artifact_id=25355)
- INSPIRE- transportation: from the INSPIRE Generic Conceptual Model p.95 (https://inspire.ec.europa.eu/file/1419/download?token=SJENygxP)

Je zou ook kunnen zeggen een wegvak is een generalisatie van een rijlijn en draagt als zodanig alle gemeenschappelijk eigenschappen:

**Wegvak**
- wegdektype
- hellingshoek
- bronhoogte

**Rijlijn**
- snelheden
- intensiteiten
- plafondcorrectiewaarde
- geometrie

**Comment by joerivanes** [comment]
Oud
