### ISSUE TITLE
OBJECT:ALGEMEEN:geometrie/hoogte - Hoe gaat hoogte worden opgenomen in IMG?

### ISSUE THREAD

**Issue by joerivanes** [Geonovum/IMG#61]
# Samenvatting issue
Hoogte is een langlopende discussie. Verschillende software pakketten hebben een andere benadering. Door analisten van IMG moet worden besloten op welke manier hoogte gaat worden opgenomen zodat hierna softwareleveranciers hier ook bij betrokken kunnen worden.

Zie ook issue #24

# Voorgestelde oplossing
**1 ALGEMEEN**
 -	Je kan voorschrijven dat een geometrie RD
 -	Overal moet je aangeven of geometrie hoogte kan hebben en binnen welk coördinatenstelsel
 -	Algemeen advies vanuit Geonovum is om hoogte in NAP vast te leggen

**2 GELUIDSCHERM**

**_Optie 1_**
 -	Geluidscherm
 -	_x_ en _y_ van de voet
 -	_z_ van de top
 -	m relatieve hoogte in apart attribuut
 -	_z_ en m moeten dezelfde modelleerrichting
 -	Vooral heel softwarevriendelijk

**_Optie 2_**
 -	GeometrieTop
 -	Extra attribuut gemiddeldeSchermhoogte
 -	Vooral vriendelijk voor onervaren gebruiker
 -	Heb je dan voet of top nodig?
 -	Of diezelfde constructie als onder **_optie 1_**

**_Optie 3_**
 -	Geometrie van top en voet
 -	Maar dan heb nog wel hellingshoek nodig
 -	Huidige situatie

**_Optie 4_**
 -	Geometrie surface
 -	Dan heb je geen hellingshoek en schermhoogte nodig
 -	Softwaretechnisch is perfect verticaal lastig

**_VRAGEN_**
 -	Schermvoet nodig? Waarvoor?
 -	Gesegmenteerde schermen (schermen opgebouwd uit verschillende delen om een gebogen scherm te modelleeren)
	
**3 REFERENTIEPUNT**

**_Optie 1_**
 -	3D-geometrie, met z-waarde in NAP, RD+NAP (7415) in regels opnemen
 -	Optioneel hoogtereferentiepunt om hoogte tov van maaiveld, heeft puur informatieve waarde

**_Optie 2_**
 - 	Alleen geometrie met z-waarde tov NAP
 -	Dit adviseert Geonovum/RIVM

**4 GELUIDBRONINDUSTRIE.absoluteHoogte**
 -	Liever andere naam, want 'absoluut' is abstract
 -	Zelfde aanpak als voor referentiepunten
 -	Moet wel te herleiden zijn naar de geometrie van de geluidbron
 -	Een bron kan bijvoorbeeld op of in een gebouw zitten, maar ook in open maaiveld
 -	Als alle geluidbronnen, overdrachtsobjecten allemaal een OGC-geom met hoogte tov NAP, dan kun je ze ook plaatsten tov van elkaar.
 -	Maaiveld maakt het softwaretechnisch waarschijnlijk veel lastiger.
 -	Dus een 3D punt met _z_ tov NAP
 -	'absoluteHoogte' kan weg
 -	Als een punt niet in een gebouw zit, hoe kun je dan reflectie tov de grondvlak beschrijven?
 -	Je moe thoogte van het object waar de eerstre reflectie plaatsvindt weten
 -	Softwareleveranciers gebruiken maaiveld (van buiten systematiek) om objecten te positioneren

**5 GEBOUW**
 -	Gemodelleerd als een vlak van de top van eht gebouw
 -	AbsoluteHoogte weglaten
 -	Geometrie: hoogte in _z_ tov NAP
 -	Surface is het dak van het gebouw
 -	Dat is altijd vlak, dus gelijkblijvende z-hoogte moet overal hetzelde zijn

**6 VEGETATIEGEBIED**
 -	Zelfde aanpak als gebouw

**7 PROCESINSTALLATIEGEBIED**
 -	Zelfde aanpak als gebouw

**8 BODEMVLAK**
 -	Wordt gedrapeerd op AHN, dus DTM van maken?
 -	_x_, _y_, geen hoogte

**9 HOOGTELIJNEN**
 -	_x_, _y_, z

**10 KUNSTWERKEN**
 -	Bij Maarten navragen of die hoogte hebben
 -	Indien 3D, dan _x_,_y_,z
 -	Anders (2D), dan alleen _x_, _y_

**11 RIJLIJN**
 -	_x_,_y_,z

**12 GEOSPOORTAK**
 -	Hoe zit hoogte er nu in
 -	LET OP: voor omzetten van dynamisch naar statisch lijnmodel NIET opknippen op hoogtekilometrering
 -	Dus _x_,_y_,_z_ per vertex/node/vormpunt 

**13 DIFFRACTOR**
 -	Type geometrie (vlak/lijn)
 -	3D?

**14 GELUIDCONTOUREN BIJ CUMULATIEF**
 -	Geen hoogte

**Comment by joerivanes** [comment]
Bespreken in meeting

**Comment by joerivanes** [comment]
#73

**Comment by lvdbrink** [comment]
Ik heb dit met Jantien Stoter besproken. 

**Bij 2 GELUIDSSCHERM**
Jantien adviseert een optie 1a:

- Een 3D lijn van de top
- De software kan deze totaan het maaiveld naar beneden trekken. 
- Relatieve hoogte is dan niet nodig.
- Complexiteiten zoals schermen met hellingshoek en zwevende schermen worden nu niet ondersteund waarschijnlijk dus zouden we deze in imgeluid voorlopig ook niet moeten ondersteunen?
- Jantien vraagt bovenstaande nog na bij geluidsexpert.

**Bij 3 REFERENTIEPUNT**
Optie 1 is zinnig. De software kan hoogte tov maaiveld uitrekenen en het heeft wel toegevoegde waarde, zij het alleen informatief. Dus Jantien adviseert optie 1.

**Bij 5 GEBOUW**
In de huidige werkwijze wordt een gebouw gerepresenteerd als 2D vlakgeometrie plus hoogte. Jantien adviseert dit: zo is het nu en dit is eenvoudiger. 

Voor gebouwen zijn er nog wat extra aandachtspunten: 
- Waar worden gebouwen uit gehaald? Wat is een gebouw: i.e. is het een BAG pand? BGT bouwwerken zoals silo's, die niet in de BAG zitten, kunnen ook een rol spelen. Hoe zit het met uitzonderlijke situaties zoals bv utrechtse werfkelders? Wij moeten in de definitie van Gebouw hier wel eea over zeggen.
- Gebouwen moeten soms nog nader worden opgedeeld als het dak verschillende hoogtes (verspringingen) heeft. Voor lokale analyses bv op wijkniveau of per industriegebied is dit nodig. Voor globale analyses niet. 
- Wat is de hoogte? De hoogtereferentie kan verschillen: bv hoogste dakrand, hoogste punt, enz. Zie INSPIRE http://inspire.ec.europa.eu/codelist/ElevationReferenceValue. Dit wellicht opnemen bij gebouw als extra informatie die ingevuld moet worden. Welke gebouwhoogte wordt gekozen hangt nl mede af van de use case.

**Overig**
Hoogtelijnen, kunstwerken, rijlijnen, geospoortakken: 3D lijnen.

**Comment by TheoVerheij** [comment]
Jantien geeft aan  dat hellingshoek en zwevende schermen nu niet worden ondersteund. Dat is deels waar.

**Hellende schermen:**
Het nieuwe rekenvoorschrift welke dit jaar samen met het CVGG wordt afgerond geeft de mogelijkheid om met hellende schermen te rekenen. Met name een partij als RWS (bronhouder rijkswegen) zal dit gaan opnemen in de brondata waarmee zij de GPP's zullen gaan berekenen. Ik ben van mening dat het informatiemodel dit al wel moet ondersteunen.

**Zwevende schermen**
Het rekenvoorschrift is een 2.5D voorschrift. Zo gezien worden zwevende schermen niet ondersteund. Maar om modellen te kunnen maken met kruisende (snel)wegen is het noodzakelijk om deze vlag te hebben. Huidige marktsoftware (in ieder geval Geomilieu en WinHavik) hebben deze optie is hun 
 software zitten en deze wordt ook gebruikt om de GPP's van snelwegen te berekenen. Wil je in staat zijn berekende GPP-waarden te reproduceren, dan is deze vlag noodzakelijk.

**Gebouwen**
Deze spelen alleen voor Industrie. Daar hebben we te maken met een enorme historie aan bestaande modellen welke de basis zullen vormen van de data welke wordt aangeleverd. Deze gebouwen komen dus niet uit BAG of BGT, maar uit modellen welke al 10-tallen jaren bestaan. Op basis van deze modellen zijn vergunningen afgegeven en zijn zones bewaakt. Deze modellen zullen ook niete worden aangepast voordat ze aan het CVGG worden aangeboden. Het IMG zal dus bestaande, in de praktijk veelvuldig toegepaste, modellering moeten ondersteunen. De hoogte van een gebouw is ook niet de hoogte welke binnen bijvoorbeeld INSPIRE is gedefinieerd, maar is de hoogte welke binnen het rekenvoorschrift (HMRI) staat gedefinieerd.

**Comment by jstoter** [comment]
Ik had aangegeven dat ik (als niet-geluid expert) geen ervaring heb met zwevende en hellende geluidschermen, alleen met de simpele versie. Ik weet daarom niet hoe in de praktijk wordt omgegaan met zwevende/helllende schermen en gaf aan dat hiervoor de ervaring van een geluidsexpert nodig is (dit geldt trouwens ook voor mijn andere opmerkingen aangaande hoogte). De aanvullingen van Theo Verhey zijn daarom welkom en waardevol.

**Comment by joerivanes** [comment]
# Vastgestelde oplossing

**1 ALGEMEEN**
 -	Beslissingen zijn gemaakt op basis van advies van hoogte experts van Geonovum/ RIVM en op basis van advies van geluidsoftware leveranciers.
-      

**2 GELUIDSCHERM**

**_Gekozen oplossing: Optie 1_**
 -	_x_ en _y_ van de voet.
 -	_z_ van de top.
 -	Lijst met m relatieve hoogte in apart attribuut.
 -	_z_ en m moeten dezelfde modelleerrichting.
-      status zwevend opnemen.
	
**3 REFERENTIEPUNT**

**_Gekozen oplossing: Optie 1_**
 -	3D-geometrie, met z-waarde in NAP, RD+NAP (7415) in regels opnemen.
 -	relatieve hoogte tov van maaiveld opnemen.

**4 GELUIDBRONINDUSTRIE**
**_Gekozen oplossing:_**
 -	Zelfde aanpak als bij referentiepunt
-      Relatieve hoogte heeft een andere definitie: hoogte van eerste reflectie.

**5 GEBOUW**
**_Gekozen oplossing:_**
 -	Gemodelleerd als een vlak van de top van het gebouw
 -	AbsoluteHoogte weglaten
 -	Geometrie: hoogte in _z_ tov NAP
 -	Surface is het dak van het gebouw
 -	Dat is altijd vlak, dus gelijkblijvende z-hoogte moet overal hetzelde zijn
-      Relatieve (m hoogte) opnemen in double list die moet corresponderen met coördinaten van surface geometrie. 

**6 VEGETATIEGEBIED**
**_Gekozen oplossing:_**
 -	Zelfde aanpak als gebouw

**7 PROCESINSTALLATIEGEBIED**
**_Gekozen oplossing:_**
 -	Zelfde aanpak als gebouw

**8 BODEMVLAK**
**_Gekozen oplossing:_**
 -	_x_, _y_, geen hoogte

**9 HOOGTELIJNEN**
**_Gekozen oplossing:_**
 -	_x_, _y_, z (3D lijnen) 
-      De vraag is nog of het altijd absorberend is.

**10 KUNSTWERKEN**
**_Gekozen oplossing:_**
 -	Nog navraag bij Pro-rail

**11 RIJLIJN**
**_Gekozen oplossing:_**
 -	_x_,_y_,z. 
-      Op de plek waar maailveld afwijkt van hoogte baan bijvoorbeeld op een brug kan double-list worden gebruikt met relatieve hoogtes tov maaiveld, maar er kan ook voor worden gekozen om hoogtelijnen te gebruiken.

**12 GEOSPOORTAK**
**_Gekozen oplossing:_**
 -	Hetzelfde als rijlijn.

**13 DIFFRACTOR**
**_Gekozen oplossing:_**
 -	Type geometrie (vlak/lijn)
 -	3D
-      status is zwevend opnemen

**14 GELUIDCONTOUREN BIJ CUMULATIEF**
 -	Geen hoogte

**Comment by TheoVerheij** [comment]
Voor de volledigheid: een geluidscherm heeft voor weg (en spoor) ook een hellingshoek als attribuut.

**Comment by joerivanes** [comment]
Verwerkt in informatiemodel en check uitgevoerd
