### ISSUE TITLE
OBJECT::Geluidaandachtsgebied - INSPIRE

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#65]
# Samenvatting
Het **Geluidaandachtsgebied** valt onder de **INSPIRE-verplichting** (thema: **Area Management** [AM]). Daarom wordt onderzocht welke eisen dit stelt aan de vastlegging van dit gebied in het IMGeluid en in hoeverre dit verschilt ten opzichte van de eisen die er vanuit de CVGG liggen.

# Voorgestelde oplossing
Het lijkt er vooralsnog op dat de meeste onderdelen die nu in het IMGeluid vastgelegd worden gemapt kunnen worden voor INSPIRE. Hier en daar zijn beschieden aanvullingen/aanpassingen nodig. Hieronder een overzicht, geredeneerd vanuit het AM-model. De eventueel nodige aanpassingen worden nog niet doorgevoerd omdat (zie punt: 2.1) nog moet worden uitgezocht wat de authentieke bron wordt voor het Geluidaandachtsgebied (GAG).

### 1.1 inspireID: identifier
**Beschikbaar** via **_Geluidaandachtsgebied.identificatie_**
 - **Vraag**: IMG gebruikt straks NEN3610ID’s, die lijken aan de specificatie te voldoen. Klopt dat? 
 - **Antwoord**: Op de INSPIRE-wiki staan de vereisten aangegeven voor de INSPIRE-id, zie hiervoor https://wiki.geonovum.nl/index.php?title=INSPIRE_ID.

### 1.2 Geometry: GM_object
**Beschikbaar** via **_GAG.geometrie_**
 - IMG gebruikt straks inderdaad GM_surface/GM_Multi-surface

### 1.3 zoneType: ZoneTypeCode
**Ontbreekt in IMGeluid**
 - Zou dan waarde ‘**noise restriction zone**’ moeten zijn
 - Deze waarde geldt voor de complete dataset straks
 - **Vraag**: Wat is een logische plek in het model om dit vast te leggen? 
 - **Antwoord**": Het is de vraag of je dit in het model moet vastleggen. In een mapping kun je aangeven dat alle objecten een ‘noise restriction zone’ zijn. Je kunt met de tool Hale studio (https://www.wetransform.to/products/halestudio/) mappings maken naar de INSPIRE modellen. Dus je kunt dan jullie model inladen en mappen naar het INSPIRE model. Je hebt dan meteen je transformatiemodel klaar ipv een onderstaande mapping overzicht.
 - **Vraag**: Of gebeurt dat pas als er een INSPIRE-dataset van gemaakt wordt?
 - **Antwoord**: zie vorige antwoord

### 1.4 environmentalDomain
**Ontbreekt in IMGeluid**
 - Zou dan waarde ‘**noise**’ moeten zijn
 - Deze waarde geldt voor de complete dataset straks
 - **Vraag**: Wat is een logische plek in het model om dit vast te leggen?
 - **Antwoord**: Zie antwoord onder 1.3. Dus bij mapping aangeven dat domain ‘**noise**’ is.

### 1.5 designationPerdiod
**Beschikbaar** via **_Vastlegging.beginGeldigheid_** of .eindGeldigheid
 - Deze informatie leggen we nu wel vast, maar niet met TM_period, maar met losse begin- en einddatum.
 - Dat is een andere structuur (validFrom/-To, maar gebruikt wel (net als IMG) DateTime als datatype.
 - Dit kun je één-op-één mappen. Daar is geen conversie voor nodig.

### 1.6 competentAuthority
**Beschikbaar** via **_Aanlevering.herkomstAanlevering_**

### 1.7 beginLifespanVersion
**Beschikbaar** via **_Aanlevering.tijdstipRegistratie_**

### 2.1 name
**Ontbreekt in IMGeluid**
 - We houden geen naam bij van het GAG, maar wel geluidbronsoort (zie: 2.4)
 - **Vraag**: Wat is de vereiste hier precies? Het datatype (CharacterString) suggereert een vrij tekstveld.
 - **Antwoord** Indien het GAG officieel vastgelegd wordt in een Ow-besluit, dan worden deze gegevens al vastgelegd in OZON (dat hoeft dan dus niet meer in de CVGG). OZON is al aangemerkt voor INSPIRE, waardoor de aanmerking dan ook betrekkingheeft op het GAG. Daarom de vraag: wat is de authentieke bron voor de GAG? Waar wordt de GAG vastgesteld? Via het CVGG of via OZON. Als het laatste het geval is, dan is eigenlijk OZON de bron voor deze INSPIRE-dataset. Dit punt wordt nog verder uitgezocht, maar geldt voor alle punten onder **DocumentCitation** en **LegislationCitition**
 - Het IMG hanteert enkel en alleen een verwijzing naar het document d.m.v. een URL

### 2.2 date: CI-date
**Ontbreekt in IMGeluid**
 - **Vraag**: Welke datum kan hier opgenomen worden? 
 - **Vraag**: En welke CI_dateTypeCode? Want informatie daarover wordt niet vastgelegd in IMG
 - **Antwoord**: Zie antwoord onder punt 2.1

### 2.3 link: URL
**Beschikbaar** via **_Besluit.linkNaarBesluit_**

### 2.4 specialisedZoneType
 - Komt overeen met geluidbronsoort. Het betreft een _noiserestrictionzone_ voor bijvoorbeeld Rijks- of provinciale wegen
 - Nog uitzoeken of de lijst één-op-één aansluit bij INSPIRE

### 3.1 level: LegistlationLevelValue
**Ontbreekt in IMGeluid**
 - Zou dan waarde ‘**national**’ moeten zijn
 - Deze waarde geldt voor de complete dataset straks
 - **Vraag**: Wat is een logische plek in het model om dit vast te leggen?
 - **Antwoord**: Zie antwoorden onder punten 1.3 en 2.1
 - **Vraag**: Of gebeurt dat pas als er een INSPIRE-dataset van gemaakt wordt?
 - **Antwoord**: Zie antwoorden onder punten 1.3 en 2.1a

**Comment by joerivanes** [comment]
Moet nog worden verwerkt na consultatie

**Comment by lvdbrink** [comment]
**Ad 2.4 specialisedZoneType**

Dit is een optioneel attribuut in INSPIRE; met een codelijst **SpecialisedZoneTypeCode** waarvan de inhoud niet in INSPIRE is gedefinieerd. Hierbij staat aangegeven dat 

> For some ManagementRestrictionOrRegulationZones each zone may be further specialised. This is used to indicate that additional controls (activities or measures)may be in force depending on its specialised type.

en 

> This value should be derived from a relevant domain-specific controlled vocabulary, where available.

We kunnen dus hier de geluidbronsoort één op één voor gebruiken. De ljist sluit aan bij INSPIRE (i.e. is een meer specifieke uitbreiding van wat er in INSPIRE staat).

**Comment by lvdbrink** [comment]
@joerivanes heb jij enig idee of onderstaande (1 van de punten uit dit issue) al is uitgezocht? 

> Daarom de vraag: wat is de authentieke bron voor de GAG? Waar wordt de GAG vastgesteld? Via het CVGG of via OZON. Als het laatste het geval is, dan is eigenlijk OZON de bron voor deze INSPIRE-dataset. Dit punt wordt nog verder uitgezocht

Het hangt van het antwoord op die vraag af of er nog een wijziging nodig is van het informatiemodel om INSPIRE conform te zijn. Als CVGG de authentieke bron voor het geluidaandachtsgebied wordt, is het nodig om bij `Documentverwijzing `naast de `URL `ook `naam `en `datum `van het document op te nemen.

**Comment by joerivanes** [comment]
@lvdbrink het antwoord is: CVGG wordt de authentieke bron voor een GAG, Zie doorgestuurde emails voor onderbouwing/bevestiging

**Comment by lvdbrink** [comment]
Dat betekent dat er in het informatiemodel een wijziging nodig is om INSPIRE conform te zijn. 

Bij de klasse `Documentverwijzing`: 
- een attribuutsoort `naam` met als definitie 'de officiele naam van het document waarnaar verwezen wordt' en kardinaliteit 1..1. Deze mapt dan op INSPIRE `DocumentCitation.name`
- de attribuutsoort `datumInwerkingtreding` moet kardinaliteit 1..1 krijgen. Deze mapt dan op INSPIRE `DocumentCitation.date`.

@joerivanes wil jij dit doorvoeren?

**Comment by joerivanes** [comment]
@lvdbrink Kan jij checken of deze issue nu goed verwerkt is?

**Comment by lvdbrink** [comment]
Is verwerkt.
