### ISSUE TITLE
DATATYPE::Octaafband - 31Hz optioneel maken

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#67]
# Samenvatting
De domeinen weg en spoor kennen geen 31Hz in hun octaafband. Deze is alleen van toepassing op het domein industrie. 

# Voorgestelde oplossing
Het data-element **band31Hz optioneel maken** of een default-waarde meegeven (welke waarde?)
Regel toevoegen: geldt alleen voor het domein industrie

**Comment by joerivanes** [comment]
# Oplossing:
Opgelost met regel in informatiemodel
