### ISSUE TITLE
Attribuut: Wegdektype

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#7]
Het attribuut wegdektype is op de waardelijst die door RWS [hier ](https://www.infomil.nl/onderwerpen/geluid/regelgeving/wet-geluidhinder/wegverkeerslawaai/akoestisch-rapport/cwegdek/) wordt beschreven. Deze waardenlijst wordt **extern beheerd** en is bovendien **uitbreidbaar**. Daarom in het model opgenomen als **codelijst**. In het conceptmodel zijn voor de leesbaarheid wel waarden toegevoegd, maar in het logisch model niet. Dit volgt uit onderstaande passage uit het Metamodel voor Informatiemodellering (MIM): 

> _In tegenstelling echter tot de referentielijst wordt een codelist niet in het informatiemodel beschreven, omdat de definitie en semantiek geheel in de externe waardenlijst staat en niet (nader) geduid hoeft te worden in het informatiemodel zelf. **Een codelist heeft in het informatiemodel** daarom **geen attributen** (en zou voor de definitie alleen hoeven te refereren naar de definitie bij de extern gepubliceerde waardenlijst, maar voor het gemak is de definitie wel opgenomen als metagegeven in dit metamodel)_ ([link](https://docs.geostandaarden.nl/mim/mim10/#waardenlijsten)).

**Comment by joerivanes** [comment]
Oud
