### ISSUE TITLE
OBJECT::Geluidscherm.geometrie

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#72]
# Samenvatting
Het **huidige object** kent **twee lijn-geometrieën**: één voor de **top** van het scherm en één voor de **voet** van het **scherm**. De schermtop is verplicht. Deze geometrie heeft **vier coördinaten**: _x_, _y_, _z_ en _m_. In het nieuwe Reken- en Meetvoorschrift wordt ook de **hellingshoek** van een scherm meegenomen. In GML zou je een eigen CRS moeten definiëren om die vierde waarde te kunnen gebruiken.

Al met al een complex geheel. Daarom is in overleg met de software-leveranciers nagedacht over een logischer structuur, zoals hieronder weergegeven. Hierbij bepalen volgende attributen de driedimensionale positie van een scherm:
 - **geometrieTop**;
 - **hellingshoek**;
 - **hoogteAfscherming**

# Voorgestelde oplossing

Onderstaande oplossing **voorleggen aan klankbordgroep**

**geometrie**
 - Naam: _geometrieTop_
 - Type: _polyline_ (_GM_Curve_)
 - Locatie: _x_, _y_ van de voet van het scherm (heb je nodig i.c.m. met helling, die draait om de as van de voet; en dus niet om de as van de top)
 - Hoogte (absoluut): _z_-waarde van de top van het scherm in meters t.o.v. NAP
 - Hoogte (relatief): _m_-waarde, wordt buiten geometrie opgeslagen als apart attribuut in een lijst met getallen (datatype: _double list_)
 - [**LET OP**]: In de publieke download van ProRail zijn **schermen** als **3D-vlakken** gemodelleerd, met **NAP in millimeters**.

**hellingshoek**
 - zie: issue #25

**hoogteAfscherming**
 - Naam: hoogteAfscherming (hergebruik van naam die al in het model stond voor ander, inmiddels vervallen doeleinde)
 - HoogteAfscherming: aftrekken van geometrie top z-waarde.
 - Voor schermvoethoogte (relatief) een doublelist: maaiveldhoogte (aftrekken van z-waarde in geometrie)
 - Regel: de lijst bevat hetzelfde aantal waarden als coordinaatparen in geometrie
 - Regel: zelfde volgorde als digitaliseerrichting van de geometrie
 - Regel: hoogteAFschermening is optioneel veld, maar MOET ingevuld zijn als het een zwevend scherm betreft.
 - Een hellingshoek heeft betrekking op de schermtop.
 - Z is top scherm en absoluut tov nap
 - M is de relatieve hoogte ten opzichte van de schermtop

**Comment by joerivanes** [comment]
#61

**Comment by joerivanes** [comment]
Aangepast in het IM

**Comment by PB-GNM** [comment]
Namens Thijs Ruiter:
ArcgisPro en QGIS kennen geen doublelist. Ik kan die dus niet invullen in ons systeem. Achteraf toevoegen in de GML is geen doen als je meer dan 3000 schermitems hebt.  

Daarnaast is er nog een probleem dat het scherm en de weg de zelfde vertex punten moeten hebben in het XY vlak omdat je anders de weg omhoog of omlaag kan laten gaan maar het scherm, door een andere locatie van de vertex, daardoor boven de weg zweeft of niet volledig afschermt. Het scherm staat altijd x meter boven de weg en die gaat in gelijke hoogte mee met het maailveld van de weg. Zeker bij een dalend maaiveld van de weg met verschillende vertex punten tussen scherm en wegdeel kan het dus voorkomen dat de weg onder het scherm door kijkt.

**Comment by PB-GNM** [comment]
Hopelijk ter verduidelijking:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/80040145/152360734-66bc4205-dce6-41f8-947b-be25bc591b48.png">

**Comment by PB-GNM** [comment]
Reactie van Wilko:
Punt van aandacht is dat de modellering van een geluidscherm altijd een abstractie van de werkelijkheid blijft. Zie bijvoorbeeld het volgende geluidscherm. In zo’n geval ga ik ervan uit dat voor hoogte en hellingshoek van het scherm een akoestisch realistische waarde wordt gekozen 
![image](https://user-images.githubusercontent.com/80040145/152771364-188ed6c7-7cde-44a4-a638-dd716fc13206.png)

**Comment by wilkoquak** [comment]
Overigens is het niet alleen bij geluidscherm het geval dat er een boven-geometrie en een onder-geometrie is maar bijvoorbeeld ook bij Wegdelen die fly-over zijn. Indien er bij dit issue voor een oplossing wordt gekozen dient het aanbeveling om te kijken of dezelfde oplossing bij wegdelen etc. (Wegdelen, Bouwwerken, Spoorbaandelen) gebruikt kan worden.

**Comment by PB-GNM** [comment]
Besluit 14-3-2022: Er is voor gekozen om de punten in een U vorm toe te voegen waarbij begonnen wordt met de punten bovenaan het scherm die corresponderen met de punten onderaan het scherm. Omdat de helft van de punten boven- en de helft van de punten onderaan het scherm zitten is een onderscheid tussen voet en top van het scherm mogelijk. 

Er wordt hiermee wel een uitzondering gemaakt op de algemene eis dat het 2,5 D is, want dat is deze oplossing niet.

**Comment by GerdadeVries23** [comment]
Ik dacht dat dit issue nog open stond. Hij is niet behandeld in de Adviesgroep, alleen in een subgroep, waar Thijs niet bij was. Ik zou graag willen weten wat de impact is van deze wijziging voor de verschillende bronhouders / stakeholders. Ik heb van RWS begrepen dat de impact voor hen behoorlijk groot is als de wijziging nog dit jaar wordt doorgevoerd, en veel minder als de wijziging volgend jaar wordt doorgevoerd. Graag reacties van andere bronhouders. En is er bij iemand een noodzaak om dit nog dit jaar te doen?

**Comment by PB-GNM** [comment]
# Aanleiding
Dit wijzigingsvoorstel komt voort uit de melding dat GIS-software niet goed overweg kan met het gebruik van een Double list zoals in versie 1.2 is voorgeschreven. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/80040145/152360734-66bc4205-dce6-41f8-947b-be25bc591b48.png">

# Wijzigingsverzoek
Her wijzigingsverzoek is verschillende malen aangepast. Het wijzigingsverzoek bevat nu de inzichten zoals bekend op 29 juni 2022:
 - De bovenkant van een scherm (De groene punten) wordt als een losse geometrie genaamd bovenkantScherm aangeleverd.
 - Als sprake is van een zwevend scherm wordt de onderkant van het scherm als geometrie genaamd onderkantScherm aangeleverd, dit zijn de blauwe punten).
 - onderkantScherm heeft evenveel punten als bovenkantScherm, met dezelfde x en y coördianaten, alleen de z-coordinaat is steeds anders. De z-coordinaat bevat de onderkant van het scherm in meters boven NAP.
 -  Double-list voor attribuut schermhoogte die het probleem veroorzaakt vervalt.
 
 ![image](https://user-images.githubusercontent.com/2814052/176631688-a1564763-9a62-4531-b0d6-72ebf4b2f15f.png)

Opmerkingen:
 - het is niet altijd mogelijk om te achterhalen of een scherm zwevend is op basis van het feit dat de onderkant is meegegeven. Het attribuut statusZwevend blijft dus in het model.
 - Van de vraag of deze wijziging op alle andere plaatsen moet worden doorgevoerd waar een DoubleList gebruikt wordt is een apart issue van gemaakt: #174 

# Impactanalyse

 - Deze wijziging heeft alleen impact op partijen die Geluidschermdelen aanleveren: RWS en Prorail
 - Deze wijziging heeft geen impact op de semantiek van het model
 - De wijziging resulteert wel in niet backwards-compatible wijziging in het xml-schema als het attribuut schermhoogte ook echt verwijderd wordt, maar dat kan eventueel ook later, want het veld is niet verplicht. In dat laatste geval is het wel backwards-compatible.

**Comment by PB-GNM** [comment]
In de Adviesgroep van 30-5-2022 is vastgesteld dat Rijkswaterstaat het eens zijn met de technische oplossing.

De wijziging is daarom doorgevoerd in versie 2.0, waarbij het attribuut Geluidschermdeel.schermhoogte is verwijderd en in de toelichting van Geluidschermdeel.geometrie is aangegeven hoe deze opgenomen moet worden als liggende U.

**Comment by wilkoquak** [comment]
Het wijzigingsvoorstel aangepast aan de inzichten en overleggen tussen Prorail, RWS, RIVM en Geonovum

**Comment by skornsekj** [comment]
@wilkoquak 

- Kun je voor de volledigheid nog benoemen in het verzoek waar de x,y van beiden geometrieën betrekking op hebben. Dat is m.i de ligging van de onderkant van het geluidschermdeel. 
- De geluidschermen worden, naar RWS en Prorail, ook geleverd door de provincies.
- Het attribuut geluidwerendemaatregel is met de introductie van een apart object 'flyover' (ander wijzigingsverzoek) waarschijnlijk niet meer nodig

**Comment by ThijsRuiterRWS** [comment]
Let op. Het gaat hier expliciet om een multipart object. We gaan dus niet 2 lijnen invoeren maar in het systeem komt een lijn met een part1 en part2 die de boven en onderkant van het afschermende object beschrijft. Zie onderstaand figuur.

![image](https://user-images.githubusercontent.com/88136917/176883251-ea9657cd-89d7-410d-802b-91234b41239d.png)

Het attribuut geluidwerendemaatregel is inderdaad niet meer nodig als we een los object krijgen genaamd "flyover" of "taluudlijnen".

**Comment by wilkoquak** [comment]
@ThijsRuiterRWS : Het is wat mij betreft een prima implementatiekeuze om de boven en de onderkant in een multipart object te stoppen en dan de bovenkant in part1 en de onderkant in part2. Om in de uitwisseling expliciet duidelijk te maken dat het om de bovenkant en de onderkant gaat staan de bovenkant en de onderkant nu als twee eigenschappen van hetzelfde object gemodelleerd. Je hebt dus de juiste gegevens in je database, het is alleen een kwestie van net iets anders wegschrijven.

**Comment by wilkoquak** [comment]
Met publicatie van release def-im-img-20220705 kan dit issue worden afgesloten.

**Comment by wilkoquak** [comment]
Het huidige model staat nu toe om een scherm te maken met statusZwevend=true maar geen onderkant mee te geven. Dit is een onwenselijke situatie waarin de standaard nog duidelijkheid moet gaan bieden.

**Comment by wilkoquak** [comment]
Na navraag bij de softwareleveranceris blijkt de ene software het punt door te trekken tot de ondergrond waardoor de status zwevend redundant is.  De andere software leveranciers verwacht een waarde voor onderkantScherm bij geluidschermZwevend = True. 

Om het IMG aan te laten sluiten op beide is gaan we een regel toevoegen die ervoor zorgt dat statusZweven=true en geen onderkantScherm niet is toegestaan.

**Comment by PB-GNM** [comment]
We stellen voor dit als regel op te nemen op het niveau van het object (Geluidschermdeel) waar beide betrokken attributen onder vallen.

**Comment by skornsekj** [comment]
Suggestie: Geluidschermdeel.onderkantscherm is verplicht indien statusZwevend=true is.
