### ISSUE TITLE
OBJECT::Geluidproductieplafond.referentiepunt - hoogte

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#73]
# Samenvatting
Specifieke eisen aan de hoogte van het referentiepunt. Er zit een marge van een 0,5 meter op.

# Voorgestelde oplossing
 - geometrie: punt
 - x,y (locatie) en z-waarde = absolute hoogte t.o.v. NAP
 - ligt tussen 3,5 en 4,5 meter boven maailveld

**Comment by joerivanes** [comment]
Verwerkt in het model
