### ISSUE TITLE
OBJECT::Geluidscherm.absorptiewaarde - Definitie, functie, naamgeving

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#75]
# Samenvatting
**Absorptiewaarde**: een informatief gegeven dat heel handig is voor initiatiefnemers. **Onduidelijk** is of deze waarde **wel** of **niet** **bepalend** is voor de **hoogte** van het **geluidproductieplafond**. Eéngetalswaarde die het **absorptievermogen** van een **geluidscherm** uitdrukt. Voor de invulling van dit attribuut komen in [artikel 8.7 van het Reken- en Meetvoorschrift](https://wetten.overheid.nl/BWBR0031722/2020-01-01) twee mogelijkheden voorbij:

1. de niveaureductie van de **_geluidsisolatie_**: &Delta;_L<sub>R</sub>_ (Zie ook issue #41)
2. de niveaureductie van **_geluidsabsorptie_**: _DL_&alpha;

# Voorgestelde oplossing
Voor definitieve beslissing nog informatie uit RMV en bronhouders nodig. Er moeten nog twee keuzes gemaakt worden:
1. Attribuut opnemen in het informatiemodel?
2. Indien ja, welke van de twee typen geluidsreductiewaarden?
3. Wie levert dit gegeven?
4. Nog bespreken met juristen

**Comment by joerivanes** [comment]
Verholpen door herziening van model
