### ISSUE TITLE
OBJECT::Rijlijn.intensiteit/snelheid - multipliciteit

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#79]
# Samenvatting
De gegevensgroepen **intensiteit** en **snelheid** hebben elk 9 attribuutsoorten, die elk ingevuld moeten worden. Nu staat de kardinaliteit van beide gegevensgroepen ook op 9..9. Dat klopt niet (dubbelop). Dat betekent namelijk dat de hele set van 9 waarden, ook nog eens 9 keer voor moet komen.

# Voorgestelde oplossing

- De kardinaliteit van beide gegevensgroepen binnen het object Rijlijn vervangen voor 1..1.
- Mogelijk speelt dit ook bij spoor!

**Comment by joerivanes** [comment]
Verholpen door herziening van model
