### ISSUE TITLE
#8 Hoogtebeschrijving terrein als TIN

### ISSUE THREAD

**Issue by jstoter** [Geonovum/IMG#8]
Op dit moment wordt in geluidsimulaties de hoogtebeschrijving van terrein gedaan via 3D lijnen.
Wellicht dat het in de (nabije) toekomst mogelijk wordt om geluidssimulaties uit te voeren op TINs die de hoogte van het terrein presenteren. Dit zal doen (ook) moeten worden ondersteund door IM Geluid.

**Comment by TheoVerheij** [comment]
Het CVGG is bedoeld om brondata aan te leveren. GPP-Weg en GPP-Rail zijn/worden berekend met hoogtelijnen en industrie gebruikt over het algemeen geen bodemmodel. In deze gevallen is er dus geen sprake van het gebruik van TIN's. Deze zijn wellicht interessant voor het berekenen van actuele geluidbelastingen, maar dit valt buiten de scope van het CVGG.
Ik zie dan ook geen reden om TIN's toe te voegen.

**Comment by joerivanes** [comment]
verwerkt
