### ISSUE TITLE
OBJECT::SpoorGPP - Noodzaak object

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#82]
# Samenvatting
Voor GPP Spoor is subklasse (specialisatie) van het generieke object Geluidproductieplafond gemaakt, omdat er aanvullende eigenschappen nodig zouden zijn. Hierover lijkt echter discusse

# Voorgestelde oplossing
Tijdens klankbordsessie GPP-spoor voorleggen:
 - Is dit object nodig (met name in het kader van GPP-berekening)?
 - Indien ja: zijn dan ook alle genoemde attributen nodig?

# Beslissing
- Te hoog detailniveau hier moet je het publiek niet mee gaan vermoeien
- Wel een relevant gegeven voor adviesbureaus, maar die krijgen deze gegevens via een ander proces sowieos van ProRial, dus dat hoeft niet via deze weg. 
- Kortom: geen apart object (specialisatie).
- Geen dunne lijnen
- Indien de toekomst nog relevant wordt om opbouw van het GPP te onderbouwen met onderliggende waarden is het advies van ProRail om andere attribuutnamen te gebruiken, namelijk: **_Lden<sub>Bewegend</sub>_** en **_Lden<sub>Stilstaand</sub>_**

[**LET OP**]: Duplicatie van issue #88

**Comment by joerivanes** [comment]
Verholpen door herziening van model
