### ISSUE TITLE
OBJECT::GeluidschermSpoor.tophoekvorm - Overeenkomst/verschil met profieltype?

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#83]
# Samenvatting

Dit **attribuut** lijkt dezelfde rol te vervullen als het attribuut **profieltype** in de superklasse **Geluidscherm.** Namelijk: 

   > Vormaanduiding van het afschermend object

# Voorgestelde oplossing

- Uit klankbordsessie met adviesbureaus spoor blijkt inderdaad dat dit attribuut dezelfde functie vervult als profielcorrectie, en dus niet apart nodig is. Er kan gebruikt gemaakt worden van het attribuut: profieltype (scherp, stompt, perron, etc.)
- Controleren bij ProRail

# Beslissing
- Het gaat inderdaad om dezelfde informatie.
- Besloten is om profielcorrectie te gebruiken

**Comment by joerivanes** [comment]
Verholpen door herziening van model
