### ISSUE TITLE
OBJECT::GeluidschermSpoor.reflectiefactor

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#84]
# Samenvatting
Schermen langs het hoofdspoor hebben zowel voor de linker- als de rechterzijde van het scherm een reflectiefactor. Maar de meeste schermen zijn gemodelleerd als volledig absorberende schermen (100%). Op basis van het Reken- en Meetvoorschrift hebben de schermen daarom de waarde '0'. 

# Voorgestelde oplossing
Voor spoor kan gewoon gebruik gemaakt worden van de reflectiefactoren zoals die in de superklasse zijn opgenomen.

**Comment by joerivanes** [comment]
Verholpen door herziening van model
