### ISSUE TITLE
OBJECT::HoogtelijnSpoor - Gedefinieerde lijnen

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#86]
# Samenvatting
ProRail ontwikkelt voorgedefinieerde hoogtelijnen en onderscheidt de volgende hoogtelijntypen:

- Ballastbedlijn
- Kantaardebaanlijn
- Teentalludlijn
- Referentiepuntenlijn
- Tunnelbaklijn

# Voorgestelde oplossing
Een HoogtelijnSpoor kan zowel een tallud als een tunnelbak beschrijven. Welke hoogtelijntypen voor mogen komen, is afhankelijk van het type. Daarom heeft dit object ook een attribuut Hoogtelijnobjecttype

Indien hoogtelijnobjecttype = **talud**, dan zijn mogelijke waarden:
- ballastbedlijn
- kantaardebaanlijn
- teentalludlijn
- referentiepuntenlijn

Indien hoogtelijnobjectype = **tunnelbak**, mogelijk waarden:
- tunnelbaklijn
- teentalludlijn
- referentiepuntenlijn

[**LET OP**]: Definities enumeratiewaarden ontbreken nog!

[**LET OP**]: Tunnelbak nu feitelijk twee maal gemodelleerd, namelijk als kunstwerk en als hoogtelijn
Bij ProRail navragen!

**Comment by joerivanes** [comment]
Verholpen door herziening van model
