### ISSUE TITLE
OBJECT::Geospoortak

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#87]
# Samenvatting
 -	Boog wel uit dynamic gessegmenteerde lijnen af te leiden, maar niet uit homogene baanvakken
 -	Indien homogeen baanvakken: een attribuut boogstraal: measure in meters, hele getallen
 -	Lengte van de wissel nodig? Of als duidelijk is waaruit dat afgeleid kan worden
 -	Kan niet uit geometrie, want GM_Curve houdt op op de splitsing van de wissel
 -	Of wissel compleet vastleggen
 -	Type wissel 
 -	Alle stukjes in de wissel hebben dezelfde objectnaam (dus objectnaam relevant)
 -	Software: lengte nodig van voor- tot achterlas
 -	Hoort plafondcorrectiewaarde te hebben (in dB's)

# Voorgestelde oplossing
-	Attribuut Smeerinstallatie: weghalen, geen verplicht gegeven voor de berekening
 -	Ruimte bieden voor ID van ProRail i.v.m. herleidbaarheid, dat kan het vrije veld van emissie- en overdrachtsobject zijn.
 -	KmvanTot:nodig ter indicatie, met name voor terugrekening
 -	Geometrie (x,y,z) nodig
 -	Ieder wisselbeen is een aparte spoortak
 -	Het wisselbeen heb je niet nodig voor de GPP-berekening
 -	Akoestisch doe je niks met wisselkantcode: niet nodig
 -	Als het een geospoort een wissel is, legt dat ook een beperking op de bovenbouwcategorieën
 -	Objectnaam ook niet nodig voor, bovendien past deze informatie al in emissie- dan wel overdrachtsobject
 -	Objectnaam wordt de nieuwe samengestelde code (uniforme ID met historie)
 -	Je kunt dus ook de hele spoortak selecteren
 -	Dit is ook de link naar je intensiteiten etc.
 -	Geomilieu en Winhavik reken(den) in centimets
 -	ProRail levert aan in milimeters: hoe dan ook
 -	Formeel is het een kilometrering, en in measure neem je al eenheid op, dus misschien Van Tot ...
 -	Kilometrering als vak-attribuut (op die manier zit het volgens mij in de M-waarde van een linear referenced geometry in ISO)
 -	Geospoortak is een hartlijn
 -	mmVan/-Tot is alleen nodig voor dynamisch lijnenmodel of om daar naartoe terug te rekenen

**Comment by joerivanes** [comment]
Behoort niet tot huidige scope wel wens
