### ISSUE TITLE
OBJECT::SpoorGPP.cDunneLijn & .geluidwaarde

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#88]
# Samenvatting
Er zijn spoorlijnen waarop weinig verkeer is waardoor de geluidproductie lager is dan **52dB**. Dit worden dunne lijnen genoemd. Hiervoor is het GPP op 52dB vastgesteld. Er is dus een **verschil tussen** de **berekende geluidsproductie** en het **geluidproductieplafond**. Dat verschil wordt uitgedrukt met het attribuut **c-dunnelijn** (ook wel de _dunnelijntoeslag_). Dat attribuut gaat gepaard met het attribuut **geluidwaarde** (dat de feitelijk berekende geluidproductie bevat.  Met andere woorden: _GPP_ - _geluidwaarde_ = _c-dunnelijn_.

Echter, de vraag is of deze attributen nodig zijn in de CVGG. 

# Voorgestelde oplossing
Met RIVM en ProRail overleggen in hoeverre dit attribuut nodig is in de CVGG.

[**LET OP**]: Duplicatie van issue #82

**Comment by joerivanes** [comment]
Attributen bleken overbodig
