### ISSUE TITLE
OBJECT::Monitoringswaarde - Nalevingsverslag

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#89]
# Samenvatting
Vanuit zowel de klankborgroep GPP-weg als GPP-spoor is de behoefte geuit om ook een link naar het nalevingsverslag op te nemen.

# Voorgestelde oplossing
 - Nog een keer goed kijken naar kardinaliteit van de attributen
 - Partijen moeten sowieso al altijd een nalevingsverslag leveren, dus die informatie bestaat al
 - Maar het nalevingsverslag is één verslag dat op meerdere (of alle) monitoringswaarden van toepassing is
 - Het kan dus zijn, dus dat wil je niet per monitoringswaarde vastleggen
 - _Op welke plek in het model hoort de schrfitelijke/kwalitatieve onderbouwing thuis?_
 - Het kan zijn dat het voorgestelde supertype hiervoor een oplossing biedt (zie issue #80)

**Verschil met de schriftelijke onderbouwing voor BGE's**
 - Is dit wat anders dan de functie van het attribuut schriftelijkeOnderbouwing (zie issue #12)
 - In BGE sluit een schriftelijke onderbouwen de monitoringswaarde uit: het is of-of (zie vorige punt)
 - In plaats van een monitoringswaarde kun je een schriftelijke onderbouwen opvoeren, waarin je kunt aantonen dat het niet nodig is om te monitoren (BGE)

# Beslissing
 - Link opnemen naar nalevingsverslag is akkoord
 - Naam algemeniseren: monitoringsverslag
 - Nalevingsverslag kan ook een schriftelijke kwalitatieve onderbouwing zijn
 - Een kwalitatieve onderbouwing kan binnen gemeenten op bepaalde wegen worden toegepast, terwijl op andere wegen wel een BGE-waarde beschikbaar is.

**Comment by joerivanes** [comment]
Verholpen door herziening van model
