### ISSUE TITLE
OBJECT::Geluidaandachtsgebied - Verschil in aan- en uitlevering

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#90]
# Samenvatting
Voor de aanlevering van GAG's kunnen bevoegd gezagen alleen het GAG voor hun grondgebied aanleveren. De juridische definitie van een GAG stelt dat het één gebied is. Niet duidelijk is of het gebied uit verschillende deelgebieden mag bestaan, of dat het dataobject daadwerkelijk 'uit één stuk' moet bestaan. Indien dat laatste het geval is, moet er nagedacht worden over de verschillende manieren waarop een GAG in de aan- en uitlevering gemodelleerd moet worden.

# Voorgestelde oplossing
...

**Comment by joerivanes** [comment]
Valt buiten scope informatiemodel
