### ISSUE TITLE
OBJECT::Geospoortak.geometrie - Statisch of Dynamisch lijnenmodel?

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#91]
# Samenvatting

### Datastructuur: homogene baanvakken vs. linear referencing

- De structuur huidige download (linear referenced) is niet heel toegankelijk
- Dus in de praktijk halen gebruikers (adviesbureaus) de dataset vaak eerst door Geomilieu/WinHavik halen om het in homogene baanvakken op te knippen
- Niet alle partijen hebben problemen met het lezen van de dataset. Over het algemeent redden de grote bureaus zich wel omdat zij hier tools voor hebben geschreven, maar de kleinere adviesbureaus en en gemeenten zullen waarschijnlijk de voorkeur hebben voor homogene baanvakken omdat standaard GIS-pakketten deze structuur ondersteunen
- Dynamische segmentatie levert een zeer mooie dataset op, maar voor het doel (Het doen van akoestische berekeningen) blijkt het in de praktijk niet handig
- Grote bureaus redden zich wel, want die hebben hun tools
- Maar voor kleinere bureaus en gemeenten zal er een voorkeur voorzijn voor homogene baanvakken
- De inhoud van het model verandert niet met de keuze van de structuur
- Gebruikers kunnen niet eigenhandig die homogene baanvakken maken (aanname)

# Voorgestelde oplossing
- Vanuit ProRail wordt de mogelijkheid onderzocht om homogene baanvakken te leveren. Voorstel is om hierop voor te sorteren in het model
- Vanuit beheerders lokaal spoor is er geen **eenuidige voorkeur.**
- Voorstel is om homogene baanvakken voor zowel GPP als BGE te hanteren in deze versie van het informatiemodel

**Comment by joerivanes** [comment]
verwerkt
