### ISSUE TITLE
OBJECT::RijlijnBGE/SpoortakBGE.[verschillende attributen]

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#92]
# Samenvatting
De rekenobjecten uit de BGE-modellen zijn geïnspireerd op de bestaande geluidregisters van het hoofd(spoor)wegennet (GPP). Vanuit de klankbordgroep BGE-weg kwam de vraag **_welke objecten_** en **_attributen_** voor de BGE-berekening _daadwerkelijk nodig_ zijn en/of versimpeld kunnen worden. Het object spoortak heeft een **_intensiteit_**, een **_snelheid_** en een **_bovenbouw_**. Maar heb je van de bovenbouw bijvoorbeeld de **_spoorstaafruwheid_** nodig? 

# Voorgestelde oplossing
Wat staat er in de **AREG** en het **Reken- en Meetvoorschrift**?

**Comment by joerivanes** [comment]
Kijken wat hierover uit consultatie komt

**Comment by PB-GNM** [comment]
Spoorstaafruwheid is opgenomen in het model.
Er is niets uit de consultatie gekomen. 
Er waren geen reacties op en dus sluiten we dit issue.
