### ISSUE TITLE
GEGEVENSGROEP::Bovenbouw.spoorstaafruwheid

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#93]
# Samenvatting

In het huidige heeft het attribuut **_spoorstaafruwheid_** een datatype **_measure_** (één eenheid en één getal), maar dit attribuut moet een lijst met getallen als dataset hebben, gebasseerd op **_golflengte_** en **_snelheid_**. Daarnaast is dit een optioneel gegeven.

[**LET OP**]: Voor BGE's zal er veel minder variatie zijn dan op het hoofdspoor. 

**Vragen**

- Wat is het datatype (hoe ziet de datastructuur) van **spoorstaafruwheid** eruit?
- Is dit een gegeven dat gebruikt wordt voor de GPP-berekening?
- Zo niet, hoe relevant is het dan om dit mee te nemen?

# Voorgestelde oplossing
Datatype aanpassen o.b.v. van input vanuit AREG en softwareleveranciers

**Comment by joerivanes** [comment]
Naar nieuwe inzichten uit gesprek met RIVM bleek dat voor spoorstaafruwheid een keuze kan worden gemaakt voor gebruik te maken van de 3 standaard amplitudes per golflengte of om zelf spoorstaafruwheid te meten per golflengte. Het informatiemodel is aangepast om beide mogelijkheden te ondersteunen.
