### ISSUE TITLE
OBJECT::Vastlegging.geluidbron en .onderwerp

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#94]
# Samenvatting
In de eerste fase van het project is bedacht om een **_attribuut geluidbron_** aan het **_object Vastlegging_** mee te geven. Hiermee geef je aan wat het **onderwerp** is van de aangeleverde gegevens. Dit is wat anders dan de juridische term **_geluidbronsoort_**, die specifiek van toepassing is op het **_Geluidaandachtsgebied_**. 

Het meegeven van het attribuut onderwerp kwam voort uit de mogelijkheid dat een Vastlegging/Besluit ook alleen op monitoring van toepassing kon zijn. Het idee was dat je met dit attribuut dan kunt aangeven of het een 'standaard' besluit gaat of om een aanvullend besluit dat betrekking heeft op monitoring. Tijdens meerdere klankbordoverleggen is aangegeven dat dit overbodig is. Als er een apart besluit is opgenomen over de monitoring, dan kun je dat zien omdat er twee keer een object besluit is opgenomen (of twee keer een URL) en dat is voldoende.

**Vraag**
 - Moet je die **bovengrens** van de **kardinaliteit** niet **opnemen op attribuutniveau** in plaats van op relatieniveau?

# Voorgestelde oplossing
Het lijkt er nu op dat zowel het attribuut **geluidbron** als **onderwerp** inmiddels **overbodig** zijn. Je kunt immers aan de aanlevering zien welke partij de gegevens geleverd heeft. Daaruit kun je afleiden of het om bijvoorbeeld Rijks-, of provinciale wegen gaat.

- Attributen geluidbron en onderwerp uit het model halen. 
- Controleren of uit het object Aanlevering inderdaad de benodigde informatie te halen valt.

- Met bouwteam bespreken

**Comment by joerivanes** [comment]
Verholpen door herziening van model
