### ISSUE TITLE
UNION::OINOfHRN

### ISSUE THREAD

**Issue by Gtrouborst** [Geonovum/IMG#95]
# Samenvatting

OIN = Organisatie-identificatienummer
HRN = Handelsregisternummer

Uit dit [document](https://www.logius.nl/sites/default/files/public/bestanden/diensten/DigiKoppeling/Standaarden/Digikoppeling-Identificatie-en-Authenticatie.pdf 
)Het blijkt dat beiden een zelfde formaat hanteren met 20 cijfers. Voor het informatiemodel lijkt het voldoende om één attribuut te hebben waar of een OIN of een HRN in staat. Hoeft dan volgens mij geen UNION te zijn. 

# Voorgestelde oplossing

**Comment by joerivanes** [comment]
Union aangepast naar datatype. Datatype gespecificeerd conform document bijlage

**Comment by joerivanes** [comment]
@dgreefhorst

**Comment by joerivanes** [comment]
@lvdbrink

**Comment by joerivanes** [comment]
Alleen OIN bleek nodig te zijn
